"""Union types of concrete command definitions."""

from typing import Union

from pydantic import Field
from typing_extensions import Annotated

from . import (
    calibration,
    heater_shaker,
    magnetic_module,
    temperature_module,
    thermocycler,
)
from .aspirate import (
    Aspirate,
    AspirateCommandType,
    AspirateCreate,
    AspirateParams,
    AspirateResult,
)
from .aspirate_in_place import (
    AspirateInPlace,
    AspirateInPlaceCommandType,
    AspirateInPlaceCreate,
    AspirateInPlaceParams,
    AspirateInPlaceResult,
)
from .blow_out import (
    BlowOut,
    BlowOutCommandType,
    BlowOutCreate,
    BlowOutParams,
    BlowOutResult,
)
from .blow_out_in_place import (
    BlowOutInPlace,
    BlowOutInPlaceCommandType,
    BlowOutInPlaceCreate,
    BlowOutInPlaceParams,
    BlowOutInPlaceResult,
)
from .command import DefinedErrorData
from .comment import (
    Comment,
    CommentCommandType,
    CommentCreate,
    CommentParams,
    CommentResult,
)
from .configure_for_volume import (
    ConfigureForVolume,
    ConfigureForVolumeCommandType,
    ConfigureForVolumeCreate,
    ConfigureForVolumeParams,
    ConfigureForVolumePrivateResult,
    ConfigureForVolumeResult,
)
from .configure_nozzle_layout import (
    ConfigureNozzleLayout,
    ConfigureNozzleLayoutCommandType,
    ConfigureNozzleLayoutCreate,
    ConfigureNozzleLayoutParams,
    ConfigureNozzleLayoutPrivateResult,
    ConfigureNozzleLayoutResult,
)
from .custom import Custom, CustomCommandType, CustomCreate, CustomParams, CustomResult
from .dispense import (
    Dispense,
    DispenseCommandType,
    DispenseCreate,
    DispenseParams,
    DispenseResult,
)
from .dispense_in_place import (
    DispenseInPlace,
    DispenseInPlaceCommandType,
    DispenseInPlaceCreate,
    DispenseInPlaceParams,
    DispenseInPlaceResult,
)
from .drop_tip import (
    DropTip,
    DropTipCommandType,
    DropTipCreate,
    DropTipParams,
    DropTipResult,
)
from .drop_tip_in_place import (
    DropTipInPlace,
    DropTipInPlaceCommandType,
    DropTipInPlaceCreate,
    DropTipInPlaceParams,
    DropTipInPlaceResult,
)
from .get_tip_presence import (
    GetTipPresence,
    GetTipPresenceCommandType,
    GetTipPresenceCreate,
    GetTipPresenceParams,
    GetTipPresenceResult,
)
from .home import Home, HomeCommandType, HomeCreate, HomeParams, HomeResult
from .load_labware import (
    LoadLabware,
    LoadLabwareCommandType,
    LoadLabwareCreate,
    LoadLabwareParams,
    LoadLabwareResult,
)
from .load_liquid import (
    LoadLiquid,
    LoadLiquidCommandType,
    LoadLiquidCreate,
    LoadLiquidParams,
    LoadLiquidResult,
)
from .load_module import (
    LoadModule,
    LoadModuleCommandType,
    LoadModuleCreate,
    LoadModuleParams,
    LoadModuleResult,
)
from .load_pipette import (
    LoadPipette,
    LoadPipetteCommandType,
    LoadPipetteCreate,
    LoadPipetteParams,
    LoadPipettePrivateResult,
    LoadPipetteResult,
)
from .move_labware import (
    MoveLabware,
    MoveLabwareCommandType,
    MoveLabwareCreate,
    MoveLabwareParams,
    MoveLabwareResult,
)
from .move_relative import (
    MoveRelative,
    MoveRelativeCommandType,
    MoveRelativeCreate,
    MoveRelativeParams,
    MoveRelativeResult,
)
from .move_to_addressable_area import (
    MoveToAddressableArea,
    MoveToAddressableAreaCommandType,
    MoveToAddressableAreaCreate,
    MoveToAddressableAreaParams,
    MoveToAddressableAreaResult,
)
from .move_to_addressable_area_for_drop_tip import (
    MoveToAddressableAreaForDropTip,
    MoveToAddressableAreaForDropTipCommandType,
    MoveToAddressableAreaForDropTipCreate,
    MoveToAddressableAreaForDropTipParams,
    MoveToAddressableAreaForDropTipResult,
)
from .move_to_coordinates import (
    MoveToCoordinates,
    MoveToCoordinatesCommandType,
    MoveToCoordinatesCreate,
    MoveToCoordinatesParams,
    MoveToCoordinatesResult,
)
from .move_to_well import (
    MoveToWell,
    MoveToWellCommandType,
    MoveToWellCreate,
    MoveToWellParams,
    MoveToWellResult,
)
from .pick_up_tip import (
    PickUpTip,
    PickUpTipCommandType,
    PickUpTipCreate,
    PickUpTipParams,
    PickUpTipResult,
    TipPhysicallyMissingError,
    TipPhysicallyMissingErrorInternalData,
)
from .prepare_to_aspirate import (
    PrepareToAspirate,
    PrepareToAspirateCommandType,
    PrepareToAspirateCreate,
    PrepareToAspirateParams,
    PrepareToAspirateResult,
)
from .reload_labware import (
    ReloadLabware,
    ReloadLabwareCommandType,
    ReloadLabwareCreate,
    ReloadLabwareParams,
    ReloadLabwareResult,
)
from .retract_axis import (
    RetractAxis,
    RetractAxisCommandType,
    RetractAxisCreate,
    RetractAxisParams,
    RetractAxisResult,
)
from .save_position import (
    SavePosition,
    SavePositionCommandType,
    SavePositionCreate,
    SavePositionParams,
    SavePositionResult,
)
from .set_rail_lights import (
    SetRailLights,
    SetRailLightsCommandType,
    SetRailLightsCreate,
    SetRailLightsParams,
    SetRailLightsResult,
)
from .set_status_bar import (
    SetStatusBar,
    SetStatusBarCommandType,
    SetStatusBarCreate,
    SetStatusBarParams,
    SetStatusBarResult,
)
from .touch_tip import (
    TouchTip,
    TouchTipCommandType,
    TouchTipCreate,
    TouchTipParams,
    TouchTipResult,
)
from .verify_tip_presence import (
    VerifyTipPresence,
    VerifyTipPresenceCommandType,
    VerifyTipPresenceCreate,
    VerifyTipPresenceParams,
    VerifyTipPresenceResult,
)
from .wait_for_duration import (
    WaitForDuration,
    WaitForDurationCommandType,
    WaitForDurationCreate,
    WaitForDurationParams,
    WaitForDurationResult,
)
from .wait_for_resume import (
    WaitForResume,
    WaitForResumeCommandType,
    WaitForResumeCreate,
    WaitForResumeParams,
    WaitForResumeResult,
)

Command = Annotated[
    Union[
        Aspirate,
        AspirateInPlace,
        Comment,
        Custom,
        Dispense,
        DispenseInPlace,
        BlowOut,
        BlowOutInPlace,
        ConfigureForVolume,
        ConfigureNozzleLayout,
        DropTip,
        DropTipInPlace,
        Home,
        RetractAxis,
        LoadLabware,
        ReloadLabware,
        LoadLiquid,
        LoadModule,
        LoadPipette,
        MoveLabware,
        MoveRelative,
        MoveToCoordinates,
        MoveToWell,
        MoveToAddressableArea,
        MoveToAddressableAreaForDropTip,
        PrepareToAspirate,
        WaitForResume,
        WaitForDuration,
        PickUpTip,
        SavePosition,
        SetRailLights,
        TouchTip,
        SetStatusBar,
        VerifyTipPresence,
        GetTipPresence,
        heater_shaker.WaitForTemperature,
        heater_shaker.SetTargetTemperature,
        heater_shaker.DeactivateHeater,
        heater_shaker.SetAndWaitForShakeSpeed,
        heater_shaker.DeactivateShaker,
        heater_shaker.OpenLabwareLatch,
        heater_shaker.CloseLabwareLatch,
        magnetic_module.Disengage,
        magnetic_module.Engage,
        temperature_module.SetTargetTemperature,
        temperature_module.WaitForTemperature,
        temperature_module.DeactivateTemperature,
        thermocycler.SetTargetBlockTemperature,
        thermocycler.WaitForBlockTemperature,
        thermocycler.SetTargetLidTemperature,
        thermocycler.WaitForLidTemperature,
        thermocycler.DeactivateBlock,
        thermocycler.DeactivateLid,
        thermocycler.OpenLid,
        thermocycler.CloseLid,
        thermocycler.RunProfile,
        calibration.CalibrateGripper,
        calibration.CalibratePipette,
        calibration.CalibrateModule,
        calibration.MoveToMaintenancePosition,
    ],
    Field(discriminator="commandType"),
]

CommandParams = Union[
    AspirateParams,
    AspirateInPlaceParams,
    CommentParams,
    ConfigureForVolumeParams,
    ConfigureNozzleLayoutParams,
    CustomParams,
    DispenseParams,
    DispenseInPlaceParams,
    BlowOutParams,
    BlowOutInPlaceParams,
    DropTipParams,
    DropTipInPlaceParams,
    HomeParams,
    RetractAxisParams,
    LoadLabwareParams,
    ReloadLabwareParams,
    LoadLiquidParams,
    LoadModuleParams,
    LoadPipetteParams,
    MoveLabwareParams,
    MoveRelativeParams,
    MoveToCoordinatesParams,
    MoveToWellParams,
    MoveToAddressableAreaParams,
    MoveToAddressableAreaForDropTipParams,
    PrepareToAspirateParams,
    WaitForResumeParams,
    WaitForDurationParams,
    PickUpTipParams,
    SavePositionParams,
    SetRailLightsParams,
    TouchTipParams,
    SetStatusBarParams,
    VerifyTipPresenceParams,
    GetTipPresenceParams,
    heater_shaker.WaitForTemperatureParams,
    heater_shaker.SetTargetTemperatureParams,
    heater_shaker.DeactivateHeaterParams,
    heater_shaker.SetAndWaitForShakeSpeedParams,
    heater_shaker.DeactivateShakerParams,
    heater_shaker.OpenLabwareLatchParams,
    heater_shaker.CloseLabwareLatchParams,
    magnetic_module.DisengageParams,
    magnetic_module.EngageParams,
    temperature_module.SetTargetTemperatureParams,
    temperature_module.WaitForTemperatureParams,
    temperature_module.DeactivateTemperatureParams,
    thermocycler.SetTargetBlockTemperatureParams,
    thermocycler.WaitForBlockTemperatureParams,
    thermocycler.SetTargetLidTemperatureParams,
    thermocycler.WaitForLidTemperatureParams,
    thermocycler.DeactivateBlockParams,
    thermocycler.DeactivateLidParams,
    thermocycler.OpenLidParams,
    thermocycler.CloseLidParams,
    thermocycler.RunProfileParams,
    thermocycler.RunProfileStepParams,
    calibration.CalibrateGripperParams,
    calibration.CalibratePipetteParams,
    calibration.CalibrateModuleParams,
    calibration.MoveToMaintenancePositionParams,
]

CommandType = Union[
    AspirateCommandType,
    AspirateInPlaceCommandType,
    CommentCommandType,
    ConfigureForVolumeCommandType,
    ConfigureNozzleLayoutCommandType,
    CustomCommandType,
    DispenseCommandType,
    DispenseInPlaceCommandType,
    BlowOutCommandType,
    BlowOutInPlaceCommandType,
    DropTipCommandType,
    DropTipInPlaceCommandType,
    HomeCommandType,
    RetractAxisCommandType,
    LoadLabwareCommandType,
    ReloadLabwareCommandType,
    LoadLiquidCommandType,
    LoadModuleCommandType,
    LoadPipetteCommandType,
    MoveLabwareCommandType,
    MoveRelativeCommandType,
    MoveToCoordinatesCommandType,
    MoveToWellCommandType,
    MoveToAddressableAreaCommandType,
    MoveToAddressableAreaForDropTipCommandType,
    PrepareToAspirateCommandType,
    WaitForResumeCommandType,
    WaitForDurationCommandType,
    PickUpTipCommandType,
    SavePositionCommandType,
    SetRailLightsCommandType,
    TouchTipCommandType,
    SetStatusBarCommandType,
    VerifyTipPresenceCommandType,
    GetTipPresenceCommandType,
    heater_shaker.WaitForTemperatureCommandType,
    heater_shaker.SetTargetTemperatureCommandType,
    heater_shaker.DeactivateHeaterCommandType,
    heater_shaker.SetAndWaitForShakeSpeedCommandType,
    heater_shaker.DeactivateShakerCommandType,
    heater_shaker.OpenLabwareLatchCommandType,
    heater_shaker.CloseLabwareLatchCommandType,
    magnetic_module.DisengageCommandType,
    magnetic_module.EngageCommandType,
    temperature_module.SetTargetTemperatureCommandType,
    temperature_module.WaitForTemperatureCommandType,
    temperature_module.DeactivateTemperatureCommandType,
    thermocycler.SetTargetBlockTemperatureCommandType,
    thermocycler.WaitForBlockTemperatureCommandType,
    thermocycler.SetTargetLidTemperatureCommandType,
    thermocycler.WaitForLidTemperatureCommandType,
    thermocycler.DeactivateBlockCommandType,
    thermocycler.DeactivateLidCommandType,
    thermocycler.OpenLidCommandType,
    thermocycler.CloseLidCommandType,
    thermocycler.RunProfileCommandType,
    calibration.CalibrateGripperCommandType,
    calibration.CalibratePipetteCommandType,
    calibration.CalibrateModuleCommandType,
    calibration.MoveToMaintenancePositionCommandType,
]

CommandCreate = Annotated[
    Union[
        AspirateCreate,
        AspirateInPlaceCreate,
        CommentCreate,
        ConfigureForVolumeCreate,
        ConfigureNozzleLayoutCreate,
        CustomCreate,
        DispenseCreate,
        DispenseInPlaceCreate,
        BlowOutCreate,
        BlowOutInPlaceCreate,
        DropTipCreate,
        DropTipInPlaceCreate,
        HomeCreate,
        RetractAxisCreate,
        LoadLabwareCreate,
        ReloadLabwareCreate,
        LoadLiquidCreate,
        LoadModuleCreate,
        LoadPipetteCreate,
        MoveLabwareCreate,
        MoveRelativeCreate,
        MoveToCoordinatesCreate,
        MoveToWellCreate,
        MoveToAddressableAreaCreate,
        MoveToAddressableAreaForDropTipCreate,
        PrepareToAspirateCreate,
        WaitForResumeCreate,
        WaitForDurationCreate,
        PickUpTipCreate,
        SavePositionCreate,
        SetRailLightsCreate,
        TouchTipCreate,
        SetStatusBarCreate,
        VerifyTipPresenceCreate,
        GetTipPresenceCreate,
        heater_shaker.WaitForTemperatureCreate,
        heater_shaker.SetTargetTemperatureCreate,
        heater_shaker.DeactivateHeaterCreate,
        heater_shaker.SetAndWaitForShakeSpeedCreate,
        heater_shaker.DeactivateShakerCreate,
        heater_shaker.OpenLabwareLatchCreate,
        heater_shaker.CloseLabwareLatchCreate,
        magnetic_module.DisengageCreate,
        magnetic_module.EngageCreate,
        temperature_module.SetTargetTemperatureCreate,
        temperature_module.WaitForTemperatureCreate,
        temperature_module.DeactivateTemperatureCreate,
        thermocycler.SetTargetBlockTemperatureCreate,
        thermocycler.WaitForBlockTemperatureCreate,
        thermocycler.SetTargetLidTemperatureCreate,
        thermocycler.WaitForLidTemperatureCreate,
        thermocycler.DeactivateBlockCreate,
        thermocycler.DeactivateLidCreate,
        thermocycler.OpenLidCreate,
        thermocycler.CloseLidCreate,
        thermocycler.RunProfileCreate,
        calibration.CalibrateGripperCreate,
        calibration.CalibratePipetteCreate,
        calibration.CalibrateModuleCreate,
        calibration.MoveToMaintenancePositionCreate,
    ],
    Field(discriminator="commandType"),
]

CommandResult = Union[
    AspirateResult,
    AspirateInPlaceResult,
    CommentResult,
    ConfigureForVolumeResult,
    ConfigureNozzleLayoutResult,
    CustomResult,
    DispenseResult,
    DispenseInPlaceResult,
    BlowOutResult,
    BlowOutInPlaceResult,
    DropTipResult,
    DropTipInPlaceResult,
    HomeResult,
    RetractAxisResult,
    LoadLabwareResult,
    ReloadLabwareResult,
    LoadLiquidResult,
    LoadModuleResult,
    LoadPipetteResult,
    MoveLabwareResult,
    MoveRelativeResult,
    MoveToCoordinatesResult,
    MoveToWellResult,
    MoveToAddressableAreaResult,
    MoveToAddressableAreaForDropTipResult,
    PrepareToAspirateResult,
    WaitForResumeResult,
    WaitForDurationResult,
    PickUpTipResult,
    SavePositionResult,
    SetRailLightsResult,
    TouchTipResult,
    SetStatusBarResult,
    VerifyTipPresenceResult,
    GetTipPresenceResult,
    heater_shaker.WaitForTemperatureResult,
    heater_shaker.SetTargetTemperatureResult,
    heater_shaker.DeactivateHeaterResult,
    heater_shaker.SetAndWaitForShakeSpeedResult,
    heater_shaker.DeactivateShakerResult,
    heater_shaker.OpenLabwareLatchResult,
    heater_shaker.CloseLabwareLatchResult,
    magnetic_module.DisengageResult,
    magnetic_module.EngageResult,
    temperature_module.SetTargetTemperatureResult,
    temperature_module.WaitForTemperatureResult,
    temperature_module.DeactivateTemperatureResult,
    thermocycler.SetTargetBlockTemperatureResult,
    thermocycler.WaitForBlockTemperatureResult,
    thermocycler.SetTargetLidTemperatureResult,
    thermocycler.WaitForLidTemperatureResult,
    thermocycler.DeactivateBlockResult,
    thermocycler.DeactivateLidResult,
    thermocycler.OpenLidResult,
    thermocycler.CloseLidResult,
    thermocycler.RunProfileResult,
    calibration.CalibrateGripperResult,
    calibration.CalibratePipetteResult,
    calibration.CalibrateModuleResult,
    calibration.MoveToMaintenancePositionResult,
]

CommandPrivateResult = Union[
    None,
    LoadPipettePrivateResult,
    ConfigureForVolumePrivateResult,
    ConfigureNozzleLayoutPrivateResult,
]

# All `DefinedErrorData`s that implementations will actually return in practice.
# There's just one right now, but this will eventually be a Union.
CommandDefinedErrorData = DefinedErrorData[
    TipPhysicallyMissingError, TipPhysicallyMissingErrorInternalData
]
