"""Union types of concrete command definitions."""

from collections.abc import Collection
from typing import Annotated, Type, Union, get_type_hints

from pydantic import Field, TypeAdapter

from . import (
    absorbance_reader,
    calibration,
    flex_stacker,
    heater_shaker,
    magnetic_module,
    robot,
    temperature_module,
    thermocycler,
    unsafe,
)
from .air_gap_in_place import (
    AirGapInPlace,
    AirGapInPlaceCommandType,
    AirGapInPlaceCreate,
    AirGapInPlaceParams,
    AirGapInPlaceResult,
)
from .aspirate import (
    Aspirate,
    AspirateCommandType,
    AspirateCreate,
    AspirateParams,
    AspirateResult,
)
from .aspirate_in_place import (
    AspirateInPlace,
    AspirateInPlaceCommandType,
    AspirateInPlaceCreate,
    AspirateInPlaceParams,
    AspirateInPlaceResult,
)
from .aspirate_while_tracking import (
    AspirateWhileTracking,
    AspirateWhileTrackingCommandType,
    AspirateWhileTrackingCreate,
    AspirateWhileTrackingParams,
    AspirateWhileTrackingResult,
)
from .blow_out import (
    BlowOut,
    BlowOutCommandType,
    BlowOutCreate,
    BlowOutParams,
    BlowOutResult,
)
from .blow_out_in_place import (
    BlowOutInPlace,
    BlowOutInPlaceCommandType,
    BlowOutInPlaceCreate,
    BlowOutInPlaceParams,
    BlowOutInPlaceResult,
)
from .capture_image import (
    CaptureImage,
    CaptureImageCommandType,
    CaptureImageCreate,
    CaptureImageParams,
    CaptureImageResult,
)
from .command import DefinedErrorData
from .comment import (
    Comment,
    CommentCommandType,
    CommentCreate,
    CommentParams,
    CommentResult,
)
from .configure_for_volume import (
    ConfigureForVolume,
    ConfigureForVolumeCommandType,
    ConfigureForVolumeCreate,
    ConfigureForVolumeParams,
    ConfigureForVolumeResult,
)
from .configure_nozzle_layout import (
    ConfigureNozzleLayout,
    ConfigureNozzleLayoutCommandType,
    ConfigureNozzleLayoutCreate,
    ConfigureNozzleLayoutParams,
    ConfigureNozzleLayoutResult,
)
from .create_timer import (
    CreateTimer,
    CreateTimerCommandType,
    CreateTimerCreate,
    CreateTimerParams,
    CreateTimerResult,
)
from .custom import (
    Custom,
    CustomCommandType,
    CustomCreate,
    CustomParams,
    CustomResult,
)
from .dispense import (
    Dispense,
    DispenseCommandType,
    DispenseCreate,
    DispenseParams,
    DispenseResult,
)
from .dispense_in_place import (
    DispenseInPlace,
    DispenseInPlaceCommandType,
    DispenseInPlaceCreate,
    DispenseInPlaceParams,
    DispenseInPlaceResult,
)
from .dispense_while_tracking import (
    DispenseWhileTracking,
    DispenseWhileTrackingCommandType,
    DispenseWhileTrackingCreate,
    DispenseWhileTrackingParams,
    DispenseWhileTrackingResult,
)
from .drop_tip import (
    DropTip,
    DropTipCommandType,
    DropTipCreate,
    DropTipParams,
    DropTipResult,
)
from .drop_tip_in_place import (
    DropTipInPlace,
    DropTipInPlaceCommandType,
    DropTipInPlaceCreate,
    DropTipInPlaceParams,
    DropTipInPlaceResult,
)
from .flex_stacker.common import (
    FlexStackerHopperError,
    FlexStackerLabwareRetrieveError,
    FlexStackerLabwareStoreError,
    FlexStackerShuttleError,
    FlexStackerShuttleOccupiedError,
    FlexStackerStallOrCollisionError,
)
from .get_next_tip import (
    GetNextTip,
    GetNextTipCommandType,
    GetNextTipCreate,
    GetNextTipParams,
    GetNextTipResult,
)
from .get_tip_presence import (
    GetTipPresence,
    GetTipPresenceCommandType,
    GetTipPresenceCreate,
    GetTipPresenceParams,
    GetTipPresenceResult,
)
from .home import (
    Home,
    HomeCommandType,
    HomeCreate,
    HomeParams,
    HomeResult,
)
from .identify_module import (
    IdentifyModule,
    IdentifyModuleCommandType,
    IdentifyModuleCreate,
    IdentifyModuleParams,
    IdentifyModuleResult,
)
from .liquid_probe import (
    LiquidProbe,
    LiquidProbeCommandType,
    LiquidProbeCreate,
    LiquidProbeParams,
    LiquidProbeResult,
    TryLiquidProbe,
    TryLiquidProbeCommandType,
    TryLiquidProbeCreate,
    TryLiquidProbeParams,
    TryLiquidProbeResult,
)
from .load_labware import (
    LoadLabware,
    LoadLabwareCommandType,
    LoadLabwareCreate,
    LoadLabwareParams,
    LoadLabwareResult,
)
from .load_lid import (
    LoadLid,
    LoadLidCommandType,
    LoadLidCreate,
    LoadLidParams,
    LoadLidResult,
)
from .load_lid_stack import (
    LoadLidStack,
    LoadLidStackCommandType,
    LoadLidStackCreate,
    LoadLidStackParams,
    LoadLidStackResult,
)
from .load_liquid import (
    LoadLiquid,
    LoadLiquidCommandType,
    LoadLiquidCreate,
    LoadLiquidParams,
    LoadLiquidResult,
)
from .load_liquid_class import (
    LoadLiquidClass,
    LoadLiquidClassCommandType,
    LoadLiquidClassCreate,
    LoadLiquidClassParams,
    LoadLiquidClassResult,
)
from .load_module import (
    LoadModule,
    LoadModuleCommandType,
    LoadModuleCreate,
    LoadModuleParams,
    LoadModuleResult,
)
from .load_pipette import (
    LoadPipette,
    LoadPipetteCommandType,
    LoadPipetteCreate,
    LoadPipetteParams,
    LoadPipetteResult,
)
from .move_labware import (
    GripperMovementError,
    MoveLabware,
    MoveLabwareCommandType,
    MoveLabwareCreate,
    MoveLabwareParams,
    MoveLabwareResult,
)
from .move_relative import (
    MoveRelative,
    MoveRelativeCommandType,
    MoveRelativeCreate,
    MoveRelativeParams,
    MoveRelativeResult,
)
from .move_to_addressable_area import (
    MoveToAddressableArea,
    MoveToAddressableAreaCommandType,
    MoveToAddressableAreaCreate,
    MoveToAddressableAreaParams,
    MoveToAddressableAreaResult,
)
from .move_to_addressable_area_for_drop_tip import (
    MoveToAddressableAreaForDropTip,
    MoveToAddressableAreaForDropTipCommandType,
    MoveToAddressableAreaForDropTipCreate,
    MoveToAddressableAreaForDropTipParams,
    MoveToAddressableAreaForDropTipResult,
)
from .move_to_coordinates import (
    MoveToCoordinates,
    MoveToCoordinatesCommandType,
    MoveToCoordinatesCreate,
    MoveToCoordinatesParams,
    MoveToCoordinatesResult,
)
from .move_to_well import (
    MoveToWell,
    MoveToWellCommandType,
    MoveToWellCreate,
    MoveToWellParams,
    MoveToWellResult,
)
from .movement_common import StallOrCollisionError
from .pick_up_tip import (
    PickUpTip,
    PickUpTipCommandType,
    PickUpTipCreate,
    PickUpTipParams,
    PickUpTipResult,
    TipPhysicallyMissingError,
)
from .pipetting_common import (
    LiquidNotFoundError,
    OverpressureError,
    TipPhysicallyAttachedError,
)
from .prepare_to_aspirate import (
    PrepareToAspirate,
    PrepareToAspirateCommandType,
    PrepareToAspirateCreate,
    PrepareToAspirateParams,
    PrepareToAspirateResult,
)
from .pressure_dispense import (
    PressureDispense,
    PressureDispenseCommandType,
    PressureDispenseCreate,
    PressureDispenseParams,
    PressureDispenseResult,
)
from .reload_labware import (
    ReloadLabware,
    ReloadLabwareCommandType,
    ReloadLabwareCreate,
    ReloadLabwareParams,
    ReloadLabwareResult,
)
from .retract_axis import (
    RetractAxis,
    RetractAxisCommandType,
    RetractAxisCreate,
    RetractAxisParams,
    RetractAxisResult,
)
from .save_position import (
    SavePosition,
    SavePositionCommandType,
    SavePositionCreate,
    SavePositionParams,
    SavePositionResult,
)
from .seal_pipette_to_tip import (
    SealPipetteToTip,
    SealPipetteToTipCommandType,
    SealPipetteToTipCreate,
    SealPipetteToTipParams,
    SealPipetteToTipResult,
)
from .set_rail_lights import (
    SetRailLights,
    SetRailLightsCommandType,
    SetRailLightsCreate,
    SetRailLightsParams,
    SetRailLightsResult,
)
from .set_status_bar import (
    SetStatusBar,
    SetStatusBarCommandType,
    SetStatusBarCreate,
    SetStatusBarParams,
    SetStatusBarResult,
)
from .set_tip_state import (
    SetTipState,
    SetTipStateCommandType,
    SetTipStateCreate,
    SetTipStateParams,
    SetTipStateResult,
)
from .touch_tip import (
    TouchTip,
    TouchTipCommandType,
    TouchTipCreate,
    TouchTipParams,
    TouchTipResult,
)
from .unseal_pipette_from_tip import (
    UnsealPipetteFromTip,
    UnsealPipetteFromTipCommandType,
    UnsealPipetteFromTipCreate,
    UnsealPipetteFromTipParams,
    UnsealPipetteFromTipResult,
)
from .verify_tip_presence import (
    VerifyTipPresence,
    VerifyTipPresenceCommandType,
    VerifyTipPresenceCreate,
    VerifyTipPresenceParams,
    VerifyTipPresenceResult,
)
from .wait_for_duration import (
    WaitForDuration,
    WaitForDurationCommandType,
    WaitForDurationCreate,
    WaitForDurationParams,
    WaitForDurationResult,
)
from .wait_for_resume import (
    WaitForResume,
    WaitForResumeCommandType,
    WaitForResumeCreate,
    WaitForResumeParams,
    WaitForResumeResult,
)
from .wait_for_tasks import (
    WaitForTasks,
    WaitForTasksCommandType,
    WaitForTasksCreate,
    WaitForTasksParams,
    WaitForTasksResult,
)
from opentrons.util.get_union_elements import get_union_elements

Command = Annotated[
    Union[
        AirGapInPlace,
        Aspirate,
        AspirateInPlace,
        AspirateWhileTracking,
        Comment,
        Custom,
        Dispense,
        DispenseInPlace,
        DispenseWhileTracking,
        BlowOut,
        BlowOutInPlace,
        ConfigureForVolume,
        ConfigureNozzleLayout,
        DropTip,
        DropTipInPlace,
        Home,
        RetractAxis,
        LoadLabware,
        ReloadLabware,
        LoadLiquid,
        LoadLiquidClass,
        LoadModule,
        IdentifyModule,
        LoadPipette,
        LoadLidStack,
        LoadLid,
        MoveLabware,
        MoveRelative,
        MoveToCoordinates,
        MoveToWell,
        MoveToAddressableArea,
        MoveToAddressableAreaForDropTip,
        PrepareToAspirate,
        WaitForResume,
        WaitForDuration,
        WaitForTasks,
        CreateTimer,
        PickUpTip,
        SavePosition,
        SetRailLights,
        TouchTip,
        SetStatusBar,
        VerifyTipPresence,
        GetTipPresence,
        GetNextTip,
        SetTipState,
        LiquidProbe,
        TryLiquidProbe,
        SealPipetteToTip,
        PressureDispense,
        UnsealPipetteFromTip,
        CaptureImage,
        heater_shaker.WaitForTemperature,
        heater_shaker.SetTargetTemperature,
        heater_shaker.DeactivateHeater,
        heater_shaker.SetAndWaitForShakeSpeed,
        heater_shaker.SetShakeSpeed,
        heater_shaker.DeactivateShaker,
        heater_shaker.OpenLabwareLatch,
        heater_shaker.CloseLabwareLatch,
        magnetic_module.Disengage,
        magnetic_module.Engage,
        temperature_module.SetTargetTemperature,
        temperature_module.WaitForTemperature,
        temperature_module.DeactivateTemperature,
        thermocycler.SetTargetBlockTemperature,
        thermocycler.WaitForBlockTemperature,
        thermocycler.SetTargetLidTemperature,
        thermocycler.WaitForLidTemperature,
        thermocycler.DeactivateBlock,
        thermocycler.DeactivateLid,
        thermocycler.OpenLid,
        thermocycler.CloseLid,
        thermocycler.RunProfile,
        thermocycler.StartRunExtendedProfile,
        thermocycler.RunExtendedProfile,
        absorbance_reader.CloseLid,
        absorbance_reader.OpenLid,
        absorbance_reader.Initialize,
        absorbance_reader.ReadAbsorbance,
        flex_stacker.Retrieve,
        flex_stacker.Store,
        flex_stacker.SetStoredLabware,
        flex_stacker.Fill,
        flex_stacker.Empty,
        calibration.CalibrateGripper,
        calibration.CalibratePipette,
        calibration.CalibrateModule,
        calibration.MoveToMaintenancePosition,
        unsafe.UnsafeBlowOutInPlace,
        unsafe.UnsafeDropTipInPlace,
        unsafe.UpdatePositionEstimators,
        unsafe.UnsafeEngageAxes,
        unsafe.UnsafeUngripLabware,
        unsafe.UnsafePlaceLabware,
        unsafe.UnsafeFlexStackerManualRetrieve,
        unsafe.UnsafeFlexStackerCloseLatch,
        unsafe.UnsafeFlexStackerOpenLatch,
        unsafe.UnsafeFlexStackerPrepareShuttle,
        robot.MoveTo,
        robot.MoveAxesRelative,
        robot.MoveAxesTo,
        robot.OpenGripperJaw,
        robot.CloseGripperJaw,
    ],
    Field(discriminator="commandType"),
]

CommandParams = Union[
    AirGapInPlaceParams,
    AspirateParams,
    AspirateWhileTrackingParams,
    AspirateInPlaceParams,
    CommentParams,
    ConfigureForVolumeParams,
    ConfigureNozzleLayoutParams,
    CustomParams,
    DispenseParams,
    DispenseInPlaceParams,
    DispenseWhileTrackingParams,
    BlowOutParams,
    BlowOutInPlaceParams,
    DropTipParams,
    DropTipInPlaceParams,
    HomeParams,
    RetractAxisParams,
    LoadLabwareParams,
    LoadLidStackParams,
    LoadLidParams,
    ReloadLabwareParams,
    LoadLiquidParams,
    LoadLiquidClassParams,
    LoadModuleParams,
    IdentifyModuleParams,
    LoadPipetteParams,
    MoveLabwareParams,
    MoveRelativeParams,
    MoveToCoordinatesParams,
    MoveToWellParams,
    MoveToAddressableAreaParams,
    MoveToAddressableAreaForDropTipParams,
    PrepareToAspirateParams,
    WaitForResumeParams,
    WaitForDurationParams,
    WaitForTasksParams,
    CreateTimerParams,
    PickUpTipParams,
    SavePositionParams,
    SetRailLightsParams,
    TouchTipParams,
    SetStatusBarParams,
    VerifyTipPresenceParams,
    GetTipPresenceParams,
    GetNextTipParams,
    SetTipStateParams,
    LiquidProbeParams,
    TryLiquidProbeParams,
    SealPipetteToTipParams,
    PressureDispenseParams,
    UnsealPipetteFromTipParams,
    CaptureImageParams,
    heater_shaker.WaitForTemperatureParams,
    heater_shaker.SetTargetTemperatureParams,
    heater_shaker.DeactivateHeaterParams,
    heater_shaker.SetAndWaitForShakeSpeedParams,
    heater_shaker.SetShakeSpeedParams,
    heater_shaker.DeactivateShakerParams,
    heater_shaker.OpenLabwareLatchParams,
    heater_shaker.CloseLabwareLatchParams,
    magnetic_module.DisengageParams,
    magnetic_module.EngageParams,
    temperature_module.SetTargetTemperatureParams,
    temperature_module.WaitForTemperatureParams,
    temperature_module.DeactivateTemperatureParams,
    thermocycler.SetTargetBlockTemperatureParams,
    thermocycler.WaitForBlockTemperatureParams,
    thermocycler.SetTargetLidTemperatureParams,
    thermocycler.WaitForLidTemperatureParams,
    thermocycler.DeactivateBlockParams,
    thermocycler.DeactivateLidParams,
    thermocycler.OpenLidParams,
    thermocycler.CloseLidParams,
    thermocycler.RunProfileParams,
    thermocycler.StartRunExtendedProfileParams,
    thermocycler.RunExtendedProfileParams,
    absorbance_reader.CloseLidParams,
    absorbance_reader.OpenLidParams,
    absorbance_reader.InitializeParams,
    absorbance_reader.ReadAbsorbanceParams,
    flex_stacker.RetrieveParams,
    flex_stacker.StoreParams,
    flex_stacker.SetStoredLabwareParams,
    flex_stacker.FillParams,
    flex_stacker.EmptyParams,
    calibration.CalibrateGripperParams,
    calibration.CalibratePipetteParams,
    calibration.CalibrateModuleParams,
    calibration.MoveToMaintenancePositionParams,
    unsafe.UnsafeBlowOutInPlaceParams,
    unsafe.UnsafeDropTipInPlaceParams,
    unsafe.UpdatePositionEstimatorsParams,
    unsafe.UnsafeEngageAxesParams,
    unsafe.UnsafeUngripLabwareParams,
    unsafe.UnsafePlaceLabwareParams,
    unsafe.UnsafeFlexStackerManualRetrieveParams,
    unsafe.UnsafeFlexStackerCloseLatchParams,
    unsafe.UnsafeFlexStackerOpenLatchParams,
    unsafe.UnsafeFlexStackerPrepareShuttleParams,
    robot.MoveAxesRelativeParams,
    robot.MoveAxesToParams,
    robot.MoveToParams,
    robot.OpenGripperJawParams,
    robot.CloseGripperJawParams,
]

CommandType = Union[
    AirGapInPlaceCommandType,
    AspirateCommandType,
    AspirateWhileTrackingCommandType,
    AspirateInPlaceCommandType,
    CommentCommandType,
    ConfigureForVolumeCommandType,
    ConfigureNozzleLayoutCommandType,
    CustomCommandType,
    DispenseCommandType,
    DispenseInPlaceCommandType,
    DispenseWhileTrackingCommandType,
    BlowOutCommandType,
    BlowOutInPlaceCommandType,
    DropTipCommandType,
    DropTipInPlaceCommandType,
    HomeCommandType,
    RetractAxisCommandType,
    LoadLabwareCommandType,
    ReloadLabwareCommandType,
    LoadLiquidCommandType,
    LoadLiquidClassCommandType,
    LoadModuleCommandType,
    IdentifyModuleCommandType,
    LoadPipetteCommandType,
    LoadLidStackCommandType,
    LoadLidCommandType,
    MoveLabwareCommandType,
    MoveRelativeCommandType,
    MoveToCoordinatesCommandType,
    MoveToWellCommandType,
    MoveToAddressableAreaCommandType,
    MoveToAddressableAreaForDropTipCommandType,
    PrepareToAspirateCommandType,
    WaitForResumeCommandType,
    WaitForDurationCommandType,
    WaitForTasksCommandType,
    CreateTimerCommandType,
    PickUpTipCommandType,
    SavePositionCommandType,
    SetRailLightsCommandType,
    TouchTipCommandType,
    SetStatusBarCommandType,
    VerifyTipPresenceCommandType,
    GetTipPresenceCommandType,
    GetNextTipCommandType,
    SetTipStateCommandType,
    LiquidProbeCommandType,
    TryLiquidProbeCommandType,
    SealPipetteToTipCommandType,
    PressureDispenseCommandType,
    UnsealPipetteFromTipCommandType,
    CaptureImageCommandType,
    heater_shaker.WaitForTemperatureCommandType,
    heater_shaker.SetTargetTemperatureCommandType,
    heater_shaker.DeactivateHeaterCommandType,
    heater_shaker.SetAndWaitForShakeSpeedCommandType,
    heater_shaker.SetShakeSpeedCommandType,
    heater_shaker.DeactivateShakerCommandType,
    heater_shaker.OpenLabwareLatchCommandType,
    heater_shaker.CloseLabwareLatchCommandType,
    magnetic_module.DisengageCommandType,
    magnetic_module.EngageCommandType,
    temperature_module.SetTargetTemperatureCommandType,
    temperature_module.WaitForTemperatureCommandType,
    temperature_module.DeactivateTemperatureCommandType,
    thermocycler.SetTargetBlockTemperatureCommandType,
    thermocycler.WaitForBlockTemperatureCommandType,
    thermocycler.SetTargetLidTemperatureCommandType,
    thermocycler.WaitForLidTemperatureCommandType,
    thermocycler.DeactivateBlockCommandType,
    thermocycler.DeactivateLidCommandType,
    thermocycler.OpenLidCommandType,
    thermocycler.CloseLidCommandType,
    thermocycler.RunProfileCommandType,
    thermocycler.StartRunExtendedProfileCommandType,
    thermocycler.RunExtendedProfileCommandType,
    absorbance_reader.CloseLidCommandType,
    absorbance_reader.OpenLidCommandType,
    absorbance_reader.InitializeCommandType,
    absorbance_reader.ReadAbsorbanceCommandType,
    flex_stacker.RetrieveCommandType,
    flex_stacker.StoreCommandType,
    flex_stacker.SetStoredLabwareCommandType,
    flex_stacker.FillCommandType,
    flex_stacker.EmptyCommandType,
    calibration.CalibrateGripperCommandType,
    calibration.CalibratePipetteCommandType,
    calibration.CalibrateModuleCommandType,
    calibration.MoveToMaintenancePositionCommandType,
    unsafe.UnsafeBlowOutInPlaceCommandType,
    unsafe.UnsafeDropTipInPlaceCommandType,
    unsafe.UpdatePositionEstimatorsCommandType,
    unsafe.UnsafeEngageAxesCommandType,
    unsafe.UnsafeUngripLabwareCommandType,
    unsafe.UnsafePlaceLabwareCommandType,
    unsafe.UnsafeFlexStackerManualRetrieveCommandType,
    unsafe.UnsafeFlexStackerCloseLatchCommandType,
    unsafe.UnsafeFlexStackerOpenLatchCommandType,
    unsafe.UnsafeFlexStackerPrepareShuttleCommandType,
    robot.MoveAxesRelativeCommandType,
    robot.MoveAxesToCommandType,
    robot.MoveToCommandType,
    robot.OpenGripperJawCommandType,
    robot.CloseGripperJawCommandType,
]

CommandCreate = Annotated[
    Union[
        AirGapInPlaceCreate,
        AspirateCreate,
        AspirateWhileTrackingCreate,
        AspirateInPlaceCreate,
        CommentCreate,
        ConfigureForVolumeCreate,
        ConfigureNozzleLayoutCreate,
        CustomCreate,
        DispenseCreate,
        DispenseInPlaceCreate,
        DispenseWhileTrackingCreate,
        BlowOutCreate,
        BlowOutInPlaceCreate,
        DropTipCreate,
        DropTipInPlaceCreate,
        HomeCreate,
        RetractAxisCreate,
        LoadLabwareCreate,
        ReloadLabwareCreate,
        LoadLiquidCreate,
        LoadLiquidClassCreate,
        LoadModuleCreate,
        IdentifyModuleCreate,
        LoadPipetteCreate,
        LoadLidStackCreate,
        LoadLidCreate,
        MoveLabwareCreate,
        MoveRelativeCreate,
        MoveToCoordinatesCreate,
        MoveToWellCreate,
        MoveToAddressableAreaCreate,
        MoveToAddressableAreaForDropTipCreate,
        PrepareToAspirateCreate,
        WaitForResumeCreate,
        WaitForDurationCreate,
        WaitForTasksCreate,
        CreateTimerCreate,
        PickUpTipCreate,
        SavePositionCreate,
        SetRailLightsCreate,
        TouchTipCreate,
        SetStatusBarCreate,
        VerifyTipPresenceCreate,
        GetTipPresenceCreate,
        GetNextTipCreate,
        SetTipStateCreate,
        LiquidProbeCreate,
        TryLiquidProbeCreate,
        SealPipetteToTipCreate,
        PressureDispenseCreate,
        UnsealPipetteFromTipCreate,
        CaptureImageCreate,
        heater_shaker.WaitForTemperatureCreate,
        heater_shaker.SetTargetTemperatureCreate,
        heater_shaker.DeactivateHeaterCreate,
        heater_shaker.SetAndWaitForShakeSpeedCreate,
        heater_shaker.SetShakeSpeedCreate,
        heater_shaker.DeactivateShakerCreate,
        heater_shaker.OpenLabwareLatchCreate,
        heater_shaker.CloseLabwareLatchCreate,
        magnetic_module.DisengageCreate,
        magnetic_module.EngageCreate,
        temperature_module.SetTargetTemperatureCreate,
        temperature_module.WaitForTemperatureCreate,
        temperature_module.DeactivateTemperatureCreate,
        thermocycler.SetTargetBlockTemperatureCreate,
        thermocycler.WaitForBlockTemperatureCreate,
        thermocycler.SetTargetLidTemperatureCreate,
        thermocycler.WaitForLidTemperatureCreate,
        thermocycler.DeactivateBlockCreate,
        thermocycler.DeactivateLidCreate,
        thermocycler.OpenLidCreate,
        thermocycler.CloseLidCreate,
        thermocycler.RunProfileCreate,
        thermocycler.StartRunExtendedProfileCreate,
        thermocycler.RunExtendedProfileCreate,
        absorbance_reader.CloseLidCreate,
        absorbance_reader.OpenLidCreate,
        absorbance_reader.InitializeCreate,
        absorbance_reader.ReadAbsorbanceCreate,
        flex_stacker.RetrieveCreate,
        flex_stacker.StoreCreate,
        flex_stacker.SetStoredLabwareCreate,
        flex_stacker.FillCreate,
        flex_stacker.EmptyCreate,
        calibration.CalibrateGripperCreate,
        calibration.CalibratePipetteCreate,
        calibration.CalibrateModuleCreate,
        calibration.MoveToMaintenancePositionCreate,
        unsafe.UnsafeBlowOutInPlaceCreate,
        unsafe.UnsafeDropTipInPlaceCreate,
        unsafe.UpdatePositionEstimatorsCreate,
        unsafe.UnsafeEngageAxesCreate,
        unsafe.UnsafeUngripLabwareCreate,
        unsafe.UnsafePlaceLabwareCreate,
        unsafe.UnsafeFlexStackerManualRetrieveCreate,
        unsafe.UnsafeFlexStackerCloseLatchCreate,
        unsafe.UnsafeFlexStackerOpenLatchCreate,
        unsafe.UnsafeFlexStackerPrepareShuttleCreate,
        robot.MoveAxesRelativeCreate,
        robot.MoveAxesToCreate,
        robot.MoveToCreate,
        robot.OpenGripperJawCreate,
        robot.CloseGripperJawCreate,
    ],
    Field(discriminator="commandType"),
]

# Each time a TypeAdapter is instantiated, it will construct a new validator and
# serializer. To improve performance, TypeAdapters are instantiated once.
# See https://docs.pydantic.dev/latest/concepts/performance/#typeadapter-instantiated-once
CommandCreateAdapter: TypeAdapter[CommandCreate] = TypeAdapter(CommandCreate)

CommandAdapter: TypeAdapter[Command] = TypeAdapter(Command)

CommandResult = Union[
    AirGapInPlaceResult,
    AspirateResult,
    AspirateWhileTrackingResult,
    AspirateInPlaceResult,
    CommentResult,
    ConfigureForVolumeResult,
    ConfigureNozzleLayoutResult,
    CustomResult,
    DispenseResult,
    DispenseInPlaceResult,
    DispenseWhileTrackingResult,
    BlowOutResult,
    BlowOutInPlaceResult,
    DropTipResult,
    DropTipInPlaceResult,
    HomeResult,
    RetractAxisResult,
    LoadLabwareResult,
    ReloadLabwareResult,
    LoadLiquidResult,
    LoadLiquidClassResult,
    LoadModuleResult,
    IdentifyModuleResult,
    LoadPipetteResult,
    LoadLidStackResult,
    LoadLidResult,
    MoveLabwareResult,
    MoveRelativeResult,
    MoveToCoordinatesResult,
    MoveToWellResult,
    MoveToAddressableAreaResult,
    MoveToAddressableAreaForDropTipResult,
    PrepareToAspirateResult,
    WaitForResumeResult,
    WaitForDurationResult,
    WaitForTasksResult,
    CreateTimerResult,
    PickUpTipResult,
    SavePositionResult,
    SetRailLightsResult,
    TouchTipResult,
    SetStatusBarResult,
    VerifyTipPresenceResult,
    GetTipPresenceResult,
    GetNextTipResult,
    SetTipStateResult,
    LiquidProbeResult,
    TryLiquidProbeResult,
    SealPipetteToTipResult,
    PressureDispenseResult,
    UnsealPipetteFromTipResult,
    CaptureImageResult,
    heater_shaker.WaitForTemperatureResult,
    heater_shaker.SetTargetTemperatureResult,
    heater_shaker.DeactivateHeaterResult,
    heater_shaker.SetAndWaitForShakeSpeedResult,
    heater_shaker.SetShakeSpeedResult,
    heater_shaker.DeactivateShakerResult,
    heater_shaker.OpenLabwareLatchResult,
    heater_shaker.CloseLabwareLatchResult,
    magnetic_module.DisengageResult,
    magnetic_module.EngageResult,
    temperature_module.SetTargetTemperatureResult,
    temperature_module.WaitForTemperatureResult,
    temperature_module.DeactivateTemperatureResult,
    thermocycler.SetTargetBlockTemperatureResult,
    thermocycler.WaitForBlockTemperatureResult,
    thermocycler.SetTargetLidTemperatureResult,
    thermocycler.WaitForLidTemperatureResult,
    thermocycler.DeactivateBlockResult,
    thermocycler.DeactivateLidResult,
    thermocycler.OpenLidResult,
    thermocycler.CloseLidResult,
    thermocycler.RunProfileResult,
    thermocycler.StartRunExtendedProfileResult,
    thermocycler.RunExtendedProfileResult,
    absorbance_reader.CloseLidResult,
    absorbance_reader.OpenLidResult,
    absorbance_reader.InitializeResult,
    absorbance_reader.ReadAbsorbanceResult,
    flex_stacker.RetrieveResult,
    flex_stacker.StoreResult,
    flex_stacker.SetStoredLabwareResult,
    flex_stacker.FillResult,
    flex_stacker.EmptyResult,
    calibration.CalibrateGripperResult,
    calibration.CalibratePipetteResult,
    calibration.CalibrateModuleResult,
    calibration.MoveToMaintenancePositionResult,
    unsafe.UnsafeBlowOutInPlaceResult,
    unsafe.UnsafeDropTipInPlaceResult,
    unsafe.UpdatePositionEstimatorsResult,
    unsafe.UnsafeEngageAxesResult,
    unsafe.UnsafeUngripLabwareResult,
    unsafe.UnsafePlaceLabwareResult,
    unsafe.UnsafeFlexStackerManualRetrieveResult,
    unsafe.UnsafeFlexStackerCloseLatchResult,
    unsafe.UnsafeFlexStackerOpenLatchResult,
    unsafe.UnsafeFlexStackerPrepareShuttleResult,
    robot.MoveAxesRelativeResult,
    robot.MoveAxesToResult,
    robot.MoveToResult,
    robot.OpenGripperJawResult,
    robot.CloseGripperJawResult,
]


# All `DefinedErrorData`s that implementations will actually return in practice.
CommandDefinedErrorData = Union[
    DefinedErrorData[TipPhysicallyMissingError],
    DefinedErrorData[TipPhysicallyAttachedError],
    DefinedErrorData[OverpressureError],
    DefinedErrorData[LiquidNotFoundError],
    DefinedErrorData[GripperMovementError],
    DefinedErrorData[StallOrCollisionError],
    DefinedErrorData[FlexStackerStallOrCollisionError],
    DefinedErrorData[FlexStackerShuttleError],
    DefinedErrorData[FlexStackerHopperError],
    DefinedErrorData[FlexStackerLabwareRetrieveError],
    DefinedErrorData[FlexStackerShuttleOccupiedError],
    DefinedErrorData[FlexStackerLabwareStoreError],
]


def _map_create_types_by_params_type(
    create_types: Collection[Type[CommandCreate]],
) -> dict[Type[CommandParams], Type[CommandCreate]]:
    def get_params_type(create_type: Type[CommandCreate]) -> Type[CommandParams]:
        return get_type_hints(create_type)["params"]  # type: ignore[no-any-return]

    result = {get_params_type(create_type): create_type for create_type in create_types}

    # This isn't an inherent requirement of opentrons.protocol_engine,
    # but this mapping is only useful to higher-level code if this holds true.
    assert len(result) == len(create_types), (
        "Param models should map to create models 1:1."
    )

    return result


CREATE_TYPES_BY_PARAMS_TYPE = _map_create_types_by_params_type(
    get_union_elements(CommandCreate)
)
"""A "reverse" mapping from each CommandParams type to its parent CommandCreate type."""
