import { Reducer } from 'redux';
import type { RootState as LabwareDefsRootState } from '../../labware-defs';
import { NormalizedAdditionalEquipmentById, NormalizedPipetteById } from '@opentrons/step-generation';
import { LoadFileAction } from '../../load-file';
import { SaveStepFormAction } from '../../ui/steps/actions/thunks';
import { ReplaceCustomLabwareDef } from '../../labware-defs/actions';
import { CreateDeckFixtureAction, DeleteDeckFixtureAction, ToggleIsGripperRequiredAction } from '../actions/additionalItems';
import { CreateModuleAction, DeleteModuleAction, DeletePipettesAction, EditModuleAction, SubstituteStepFormPipettesAction, ChangeBatchEditFieldAction, ResetBatchEditFieldChangesAction, SaveStepFormsMultiAction } from '../actions';
import type { CancelStepFormAction, ChangeFormInputAction, ChangeSavedStepFormAction, DeleteStepAction, DeleteMultipleStepsAction, PopulateFormAction, AddProfileCycleAction, AddProfileStepAction, DeleteProfileCycleAction, DeleteProfileStepAction, EditProfileCycleAction, EditProfileStepAction, FormPatch } from '../../steplist/actions';
import type { FormData, StepIdType, StepType } from '../../form-types';
import type { CreateContainerAction, DeleteContainerAction, DuplicateLabwareAction, SwapSlotContentsAction } from '../../labware-ingred/actions';
import type { AddStepAction, DuplicateStepAction, DuplicateMultipleStepsAction, SelectStepAction, SelectTerminalItemAction, SelectMultipleStepsAction } from '../../ui/steps/actions/types';
import type { NormalizedLabwareById, ModuleEntities } from '../types';
type FormState = FormData | null;
export type UnsavedFormActions = AddProfileCycleAction | AddStepAction | ChangeFormInputAction | PopulateFormAction | CancelStepFormAction | SaveStepFormAction | DeleteStepAction | DeleteMultipleStepsAction | CreateModuleAction | DeleteModuleAction | SelectTerminalItemAction | EditModuleAction | SubstituteStepFormPipettesAction | AddProfileStepAction | DeleteProfileStepAction | DeleteProfileCycleAction | EditProfileCycleAction | EditProfileStepAction | SelectMultipleStepsAction | ToggleIsGripperRequiredAction | CreateDeckFixtureAction | DeleteDeckFixtureAction;
export declare const unsavedForm: (rootState: RootState, action: UnsavedFormActions) => FormState;
export type SavedStepFormState = Record<StepIdType, FormData>;
export declare const initialDeckSetupStepForm: FormData;
export declare const initialSavedStepFormsState: SavedStepFormState;
export type SavedStepFormsActions = SaveStepFormAction | SaveStepFormsMultiAction | DeleteStepAction | DeleteMultipleStepsAction | LoadFileAction | CreateContainerAction | DeleteContainerAction | SubstituteStepFormPipettesAction | DeletePipettesAction | CreateModuleAction | DeleteModuleAction | DuplicateStepAction | DuplicateMultipleStepsAction | ChangeSavedStepFormAction | DuplicateLabwareAction | SwapSlotContentsAction | ReplaceCustomLabwareDef | EditModuleAction | ToggleIsGripperRequiredAction | CreateDeckFixtureAction | DeleteDeckFixtureAction;
export declare const _editModuleFormUpdate: ({ savedForm, moduleId, formId, rootState, nextModuleModel, }: {
    savedForm: FormData;
    moduleId: string;
    formId: string;
    rootState: RootState;
    nextModuleModel: string;
}) => FormData;
export declare const savedStepForms: (rootState: RootState, action: SavedStepFormsActions) => SavedStepFormState;
export type BatchEditFormChangesState = FormPatch;
type BatchEditFormActions = ChangeBatchEditFieldAction | ResetBatchEditFieldChangesAction | SaveStepFormsMultiAction | SelectStepAction | SelectMultipleStepsAction | DuplicateMultipleStepsAction | DeleteMultipleStepsAction;
export declare const batchEditFormChanges: (state: Partial<Record<string, unknown>> | undefined, action: BatchEditFormActions) => BatchEditFormChangesState;
export declare const labwareInvariantProperties: Reducer<NormalizedLabwareById, any>;
export declare const moduleInvariantProperties: Reducer<ModuleEntities, any>;
export declare const pipetteInvariantProperties: Reducer<NormalizedPipetteById, any>;
export declare const additionalEquipmentInvariantProperties: import("redux-actions").ReduxCompatibleReducer<NormalizedAdditionalEquipmentById, NormalizedAdditionalEquipmentById>;
export type OrderedStepIdsState = StepIdType[];
export declare const orderedStepIds: Reducer<OrderedStepIdsState, any>;
export type PresavedStepFormState = {
    stepType: StepType;
} | null;
export type PresavedStepFormAction = AddStepAction | CancelStepFormAction | DeleteStepAction | DeleteMultipleStepsAction | SaveStepFormAction | SelectTerminalItemAction | SelectStepAction | SelectMultipleStepsAction;
export declare const presavedStepForm: (state: PresavedStepFormState | undefined, action: PresavedStepFormAction) => PresavedStepFormState;
export interface RootState {
    orderedStepIds: OrderedStepIdsState;
    labwareDefs: LabwareDefsRootState;
    labwareInvariantProperties: NormalizedLabwareById;
    pipetteInvariantProperties: NormalizedPipetteById;
    moduleInvariantProperties: ModuleEntities;
    additionalEquipmentInvariantProperties: NormalizedAdditionalEquipmentById;
    presavedStepForm: PresavedStepFormState;
    savedStepForms: SavedStepFormState;
    unsavedForm: FormState;
    batchEditFormChanges: BatchEditFormChangesState;
}
export declare const rootReducer: Reducer<RootState, any>;
export {};
