export const SINGLE_CHANNEL_PIPETTE_WIDTH = 18.7
export const SINGLE_CHANNEL_PIPETTE_HEIGHT = 30.5

export const MULTI_CHANNEL_PIPETTE_WIDTH = 18.7
export const MULTI_CHANNEL_PIPETTE_HEIGHT = 90.3

export const MULTI_CHANNEL_CENTER_Y_NOZZLE = 13.3
export const MULTI_CHANNEL_Y_OFFSET = -2.5

export const NINETY_SIX_CHANNEL_PIPETTE_WIDTH = 117.7
