#! /bin/bash

# This script is used for diagnostics of Flex robot.

instructions() {
    echo "---- Instructions ----"
    echo "Script runs from host computer"
    echo "Ex."
    echo "./flex_diagnostics <action> <sub-action> <robot-ip>"
    echo ""
    echo "action = gather, create, set-ntp, migrate [backup|restore|analyze]"
    echo "gather = Gathers and SCPs all the data, state, and logs from the given robots"
    echo "create = Creates a Tarball on the robot with the data, state, logs, etc."
    echo "set-ntp = Sets the ntp server to the value specified or default."
    echo "migrate backup <source-ip> = Creates a migration tarball."
    echo "migrate restore <target-ip> <migration-tarball.tar.gz> = Transfers tarball to target, inflates it, and rebots the robot."
    echo "migrate backup-local <created_by> = Creates a migration tarball on a Flex."
    echo "migrate restore-local <migration-tarball.tar.gz> = Takes a tarball on the Flex, inflates it, and rebots the robot."
    echo "migrate analyze <migration-tarball.tar.gz> = Print the metadata of a migration tarball."
    echo "emmc-health report = Shows eMMC health (lifetime estimation, PRE_EOL, etc.) creates csv report on the host."
    echo "emmc-health report-local = Shows eMMC health (lifetime estimation, PRE_EOL, etc.) creates csv report on the Flex."
    echo "emmc-health analyze = Takes a csv report generated by the 'report' sub-action and ranks it by Lifetime."
    echo "robot-ip = list of robot ip addresses to perform action on."
    echo ""
}

DEFAULT_NTP="time.google.com"
FALLBACK_NTP="ntp.tencent.com"
FALLBACK_DNS="2001:da8::666 240c::6666"

# Script entry-point
main() {

    # make sure we have action and robot ips
    if [[ "$#" -gt 1 ]]; then
        ip_addresses=${@:2}
    else
        echo "Error, missing args"
        instructions
        exit 1
    fi

	case $1 in
		gather)
			echo "Gather Diagnostics data"
			gather "$ip_addresses"
            ;;
		create)
			echo "Create Diagnostics tarball"
			gather "no-scp" "$ip_addresses"
            ;;
        set-ntp)
            echo "Changing NTP settings"
            set_ntp "$ip_addresses"
            ;;
        migrate)
            migrate_main "${@:2}"
            ;;
        emmc-health)
            echo "Gathering eMMC Health"
            emmc_health_main "${@:2}"
            ;;
        *)
            echo "Invalid args: $@"
            instructions
            ;;
	esac

    echo "Finished"
}

# Gather logs from given ip addresses
gather() {

    # Determine if we should SCP the tarball
    scp_file=true
    ip_addresses=$@
    if [[ $1 =~ "no-scp" ]]; then
        scp_file=false
        ip_addresses="${@:2}"
    fi

    # Iterate through the ip addresses and gather data
    for ip in $ip_addresses; do
        echo "Gathering data for ${ip}, please wait..."
        ssh -q -o stricthostkeychecking=no -o userknownhostsfile=/dev/null \
            root@$ip 'bash -s' <<- 'EOF'

            serial=$(hostnamectl --static)
            today=$(date '+%Y_%m_%d_%H_%M_%S')
            diag_dir="./diag/${serial}_${today}"

            mkdir -p "${diag_dir}"
            mkdir -p "${diag_dir}/logs"
            mkdir -p "${diag_dir}/data"
            mkdir -p "${diag_dir}/system"
            mkdir -p "${diag_dir}/network"
            mkdir -p "${diag_dir}/server"

            echo "Created $diag_dir to hold data"

            cleanup() {
                echo "Cleaning up"
                rm -rf $diag_dir
            }

            set -eE -o pipefail
            trap cleanup ERR

            echo "Gathering /data files"
            cp -r /data/* $diag_dir/data/
            cp -r /etc/VERSION.json $diag_dir/data/
            cp -r /tmp/.config/Opentrons $diag_dir/data/
            echo $serial > $diag_dir/data/serial.txt

            echo "Gathering server files"
            cp -r /var/lib/opentrons-robot-server/ $diag_dir/server/
            cp -r /var/lib/opentrons-system-server/ $diag_dir/server/

            echo "Gathering logs"
            shopt -s extglob
            cp -r /var/log/!(journal) $diag_dir/logs/
            journalctl > $diag_dir/logs/journal.log
            dmesg > $diag_dir/logs/dmesg.log

            echo "Gathering system state"
            hostname > $diag_dir/system/hostname.txt
            uname -a > $diag_dir/system/uname.txt
            date > $diag_dir/system/datetime.txt
            timedatectl >> $diag_dir/system/datetime.txt || true
            uptime > $diag_dir/system/uptime.txt || true
            ps aux > $diag_dir/system/psaux.txt
            top -c -b -n 10 > $diag_dir/system/top.txt
            free -wl -c 10 -s 10 > $diag_dir/system/free.txt

            echo "Gathering network info"
            /sbin/ifconfig > $diag_dir/network/network.txt
            echo -e "\n\n" >> $diag_dir/network/network.txt
            /sbin/ip --details link show >> $diag_dir/network/network.txt
            echo -e "\n\n" >> $diag_dir/network/network.txt
            ( nmcli dev list || nmcli dev show ) 2>/dev/null |
                grep DNS >> $diag_dir/network/network.txt

            echo "Gathering NTP server info"
            echo -e "\n\n" >> $diag_dir/network/network.txt
            ping -c 2 -w 2 time.google.com >> $diag_dir/network/network.txt || true
            ping -c 2 -w 2 ntp.tencent.com >> $diag_dir/network/network.txt || true
            ping -c 2 -w 2 time.amazonaws.cn >> $diag_dir/network/network.txt || true

            echo "Downloading releases.json"
            wget https://builds.opentrons.com/ot3-oe/releases.json -P $diag_dir/network/

            echo "Gathering systemd service state"
            systemctl status > $diag_dir/system/services_overview.txt
            systemctl status 'opentrons*' >> $diag_dir/system/opentrons_services.txt || true

            if [ -d "$diag_dir" ]; then
                tarfile="${serial}_${today}_diag.tar.gz"
                echo "Creating Tarball ${tarfile}"
                tar -zcvf $tarfile -C ./diag .
            fi

            cleanup
EOF

        if $scp_file; then
            echo "SCP Tarball from $ip..."
            # pull the tarfile if successful
            scp -r -o stricthostkeychecking=no -o userknownhostsfile=/dev/null \
                root@$ip:*diag.tar.gz .

            # clean up
            ssh -q -o stricthostkeychecking=no -o userknownhostsfile=/dev/null \
                root@$ip 'rm -rf *diag*'
        fi
    done
}

set_ntp() {
     for ip in $@; do
        ssh -q -o stricthostkeychecking=no -o userknownhostsfile=/dev/null \
            root@$ip "NTP='$FALLBACK_NTP' DNS='$FALLBACK_DNS' bash -s" <<- 'EOF'

            cleanup() {
                echo "Cleaning up"
            }

            set -eE -o pipefail
            trap cleanup ERR

            serial=$(hostnamectl --static)
            today=$(date '+%Y_%m_%d_%H_%M_%S')
            filename="${serial}_${today}_ntp.txt"

            echo "Setting NTP address to $NTP"
            echo -e "timedatectl before setting NTP server\n" > $filename
            timedatectl >> $filename

            mount -o remount,rw /
            sed -i "s/#FallbackNTP=*/FallbackNTP=$NTP /" /etc/systemd/timesyncd.conf
            timedatectl set-ntp true
            systemctl restart systemd-timesyncd
            echo -e "\ntimedatectl after setting NTP server\n" >> $filename
            sleep 5
            timedatectl >> $filename

            echo "Setting DNS address to $DNS"
            echo -e "\n\n-----------------------------------------------" >> $filename
            echo -e "systemd-resolve status before setting DNS\n" >> $filename
            systemd-resolve --status >> $filename
            echo -e "\n\n-----------------------------------------------" >> $filename
            echo -e "\nSetting DNS server" >> $filename
            sed -i "s/#FallbackDNS=*/FallbackDNS='$DNS' /" /etc/systemd/resolved.conf
            echo -e "systemd-resolve status after setting DNS\n" >> $filename
            systemctl restart systemd-resolved
            sleep 5
            systemd-resolve --status >> $filename
EOF

    echo "Fetching NTP file output"
    scp -r -o stricthostkeychecking=no -o userknownhostsfile=/dev/null \
            root@$ip:*ntp.txt .

    # clean up
    ssh -q -o stricthostkeychecking=no -o userknownhostsfile=/dev/null \
        root@$ip 'rm -rf *ntp.txt'

    done
}

is_opentrons_flex() {
    [[ -f "/etc/VERSION.json" ]] || return 1
    [[ -d "/data" && -d "/userfs" ]] || return 1
    return 0
}

migrate_main() {
    if [[ "$#" -lt 1 ]]; then
        echo ""
        echo "Error: migrate requires a sub-action"
        echo "Usage:"
        echo "  ./flex_diagnostics migrate backup <source-ip> <created_by> [note]"
        echo "  ./flex_diagnostics migrate restore <target-ip> <migration-tarball.tar.gz>"
        echo "  ./flex_diagnostics migrate backup-local <created_by> [note]"
        echo "  ./flex_diagnostics migrate restore-local <migration-tarball.tar.gz>"
        echo "  ./flex_diagnostics migrate analyze <migration-tarball.tar.gz>"
        echo ""
        instructions
        exit 1
    fi

    local subcmd=$1
    shift

    case $subcmd in
        backup)
            if [[ -z "$1" || -z "$2" ]]; then
                echo "Error: 'backup' requires <source-ip> and <created_by>"
                exit 1
            fi
            migrate_backup false "$1" "$2" "${3:-}"
            ;;
        backup-local)
            if [[ -z "$1" ]]; then
                echo "Error: 'backup-local' requires <created_by>"
                exit 1
            fi
            migrate_backup true "$1" "$2" "${3:-}"
            ;;
        restore)
            if [[ -z "$2" ]]; then
                echo "Error: restore requires the path to a migration tarball"
                exit 1
            fi
            migrate_restore false "$1" "$2"
            ;;
        restore-local)
            if [[ -z "$1" ]]; then
                echo "Error: restore-local requires the path to a migration tarball"
                exit 1
            fi
            migrate_restore true "${1:-}"
            ;;
        analyze)
            if [[ -z "$1" ]]; then
                echo "Error: analyze requires path to a migration tarball"
                exit 1
            fi
            migrate_analyze "$1"
            ;;
        *)
            echo "Invalid migrate sub-action: $subcmd"
            ;;
    esac
}

migrate_backup() {
    local is_local=$1
    local ip=$2
    local created_by=$3
    local note="${4:-}"
    local output_dir="/tmp"
    if $is_local; then
        if ! is_opentrons_flex; then
            instructions
            echo "⚠️  Can't use local commands when not on the Flex."
            exit 1
        fi

        ip="localhost"
        created_by=$2
        note="${3:-}"
        output_dir=$(pwd)
    fi

    echo "=== Creating migration backup from $ip ==="
    echo "Created By : $created_by"
    echo "Note       : $note"

    ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        root@$ip 'bash -s' <<-EOF

        set -eE -o pipefail
        trap 'echo "Backup failed on robot"' ERR

        host_name=\$(hostnamectl --pretty)
        serial=\$(cat /var/serial 2>/dev/null || echo \$host_name)
        today=\$(date '+%Y_%m_%d_%H_%M_%S')
        backup_date=\$(date '+%Y-%m-%d %H:%M:%S %Z')
        tarfile="\${serial}_\${today}_migrate.tar.gz"

        # ==================== INCLUDE LIST ====================
        # Add or remove top-level directories/files you want to backup
        declare -a INCLUDES=(
            "/data"
            "/var/lib"
            "/userfs/etc"
        )

        # Add serial if it exists
        [ -f "/var/serial" ] && INCLUDES+=("/var/serial")

        # ==================== EXCLUDE LIST ====================
        # Paths to exclude (relative to /)
        declare -a EXCLUDES=(
            "data/ODD/__ot_system_update__"
            "*/Local Extension Settings"
            "*/Local Extension Settings/*"
            "data/ODD/Local*"
            "data/ODD/*.ldb"
            "data/ODD/Cache"
            "var/log"
            "var/lib/otupdate/downloads"
            "var/lib/opkg"
            "var/lib/opkg/*"
        )
        # =====================================================

        echo "Creating metadata file..."
        mkdir -p /tmp/migrate_metadata

        cat > /tmp/migrate_metadata/metadata_compact.json <<- METADATA
        {
          "created_by": "${created_by}",
          "backup_date": "\${backup_date}",
          "note": "${note}",
          "robot_serial": "\${serial}",
          "robot_name": "\${host_name}",
          "version_file": \$(cat /etc/VERSION.json 2>/dev/null | jq . || echo "null")
        }
METADATA

        # Pretty print the metadata JSON
        jq . /tmp/migrate_metadata/metadata_compact.json > /tmp/migrate_metadata/metadata.json
        cat /tmp/migrate_metadata/metadata.json

        # Build tar arguments
        declare -a tar_args=()
        for excl in "\${EXCLUDES[@]}"; do
            tar_args+=( --exclude="\${excl}" )
        done
        for inc in "\${INCLUDES[@]}"; do
            tar_args+=( "\${inc}" )
        done

        echo "Creating migration tarball..."
        tar -zcvf "$output_dir/\${tarfile}" \
            "\${tar_args[@]}" \
            -C /tmp/migrate_metadata metadata.json 2>&1

        echo "----------------------------------------"
        echo "Migration backup created: ${output_dir}/\$tarfile"
        ls -lh "${output_dir}/\$tarfile"

        rm -rf /tmp/migrate_metadata
EOF

    if ! $is_local; then
        echo "Downloading migration tarball to host..."
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            root@$ip:${output_dir}/*_migrate.tar.gz ./

        ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            root@$ip 'rm -f /tmp/*_migrate.tar.gz'
    fi

    echo "✅ Backup completed. Tarball saved locally."
}

migrate_restore() {
    local is_local=$1
    local ip=$2
    local tarball=$3
    if $is_local; then
        if ! is_opentrons_flex; then
            instructions
            echo "⚠️  Can't use local commands when not on the Flex."
            exit 1
        fi

        ip="localhost"
        tarball=$(realpath $2)
    fi

    if [[ ! -f "$tarball" ]]; then
        echo "Error: Tarball '$tarball' not found!"
        exit 1
    fi

    echo "=== Restoring migration data to $ip from $tarball ==="

    if tar -xOf "$tarball" metadata.json > /tmp/restore_metadata.json 2>/dev/null; then
        jq . /tmp/restore_metadata.json 2>/dev/null || cat /tmp/restore_metadata.json
        echo ""
    else
        echo "Warning: Could not extract metadata.json from tarball"
    fi

    echo "⚠️  WARNING: This will OVERWRITE data on the target robot:"
    echo "   • /data"
    echo "   • /userfs"
    echo "   • /var/lib/opentrons-robot-server"
    echo "   • /var/lib/opentrons-system-server"
    echo "   • Other user data"
    echo ""
    echo "Continue with restore? (y/N)"
    read -r confirm

    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Restore cancelled by user."
        rm -f /tmp/restore_metadata.json
        exit 1
    fi

    if ! $is_local; then
        echo "Uploading tarball to robot..."
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "$tarball" root@$ip:/tmp/
    fi

    echo "Running restore on robot..."

    ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        root@$ip 'bash -s' <<-EOF

        set -eE -o pipefail
        trap 'echo "Restore failed on robot!"' ERR

        if $is_local; then
            tarball=${tarball}
        else
            tarball=\$(ls /tmp/*_migrate.tar.gz 2>/dev/null)
        fi

        if [[ -z "\$tarball" ]]; then
            echo "Error: No migration tarball found: \$tarball"
            exit 1
        fi

        echo "Stopping Opentrons services..."
        systemctl stop opentrons-robot-server 2>/dev/null || true

        echo "Remounting root filesystem read-write..."
        mount -o remount,rw / || true

        echo "Extracting migration data..."
        tar -zxvf "\$tarball" \
        --exclude="metadata.json" \
        -C /

        echo "Migration data restored successfully."

        if [ "$is_local" = false ]; then
            echo "Cleaning up..."
            rm -f \$tarball
        fi

        echo ""
        echo "=== RESTARTING ROBOT ==="
        reboot
EOF

    rm -f /tmp/restore_metadata.json
    echo "✅ Restore completed on $ip"
}

migrate_analyze() {
    local tarball=$1

    if [[ ! -f "$tarball" ]]; then
        echo "Error: Tarball '$tarball' not found!"
        exit 1
    fi

    echo "=== Metadata Analysis for: $tarball ==="
    echo "File size: $(ls -lh "$tarball" | awk '{print $5}')"
    echo "----------------------------------------"

    if tar -xOf "$tarball" metadata.json > /tmp/migrate_metadata.json 2>/dev/null; then
        if command -v jq >/dev/null 2>&1; then
            jq . /tmp/migrate_metadata.json
        else
            cat /tmp/migrate_metadata.json
        fi
        rm -f /tmp/migrate_metadata.json
    else
        echo "❌ Could not find metadata.json in the tarball."
        echo "   This may not be a valid migration backup."
    fi
}


emmc_health_main() {
    if [[ "$#" -lt 1 ]]; then
        echo ""
        echo "Error: emmc-health requires a sub-action"
        echo "Usage:"
        echo "  ./flex_diagnostics emmc-health report <source-ip ...>"
        echo "  ./flex_diagnostics emmc-health report-local"
        echo "  ./flex_diagnostics emmc-health analyze <csv-file>"
        echo ""
        instructions
        exit 1
    fi

    local subcmd=$1
    shift

    case $subcmd in
        report)
            if [[ -z "$1" ]]; then
                echo "Error: 'report' requires <source-ip>"
                exit 1
            fi
            emmc_health_report false "${@:-}"
            ;;
        report-local)
            if [[ "$#" -ne 0 ]]; then
                echo "Error: 'report-local' takes no arguments."
                exit 1
            fi
            emmc_health_report true "${@:-}"
            ;;
        analyze)
            if [[ "$#" -ne 1 ]]; then
                echo "Error: 'analyze' requires 1 argument <emmc-health.csv>"
                exit 1
            fi
            emmc_health_analyze "$1"
            ;;
        *)
            echo "Invalid emmc-health sub-action: $subcmd"
            echo "Valid: analyze"
            exit 1
            ;;
    esac
}


hex_to_life() {
    case "$1" in
        0x01) echo "0% - 10%" ;;
        0x02) echo "10% - 20%" ;;
        0x03) echo "20% - 30%" ;;
        0x04) echo "30% - 40%" ;;
        0x05) echo "40% - 50%" ;;
        0x06) echo "50% - 60%" ;;
        0x07) echo "60% - 70%" ;;
        0x08) echo "70% - 80%" ;;
        0x09) echo "80% - 90%" ;;
        0x0a|0x0A) echo "90% - 100%" ;;
        0x0b|0x0B) echo "Exceeded" ;;
        *) echo "Unknown" ;;
    esac
}

emmc_health_report() {
    local is_local=$1
    local ip_addresses="${@:2}"
    if $is_local; then
        if ! is_opentrons_flex; then
            instructions
            echo "⚠️  Can't use local commands when not on the Flex."
            exit 1
        fi
        ip_addresses="localhost"
    fi
    today=$(date '+%Y_%m_%d_%H_%M_%S')
    local RESULTS_FILE="emmc-health_${today}.csv"
    echo "IP,Robot_Name,Serial,Max_Lifetime_Used_%,Journal_Size_GB,Top_Writer_Service,Top_Log_Lines_Last30min,Biggest_File,Top10_Files" > "$RESULTS_FILE"

    # Iterate through the ip addresses and gather data
    echo "=== Starting full diagnostics on $# robots ==="
    for ip in $ip_addresses; do
        echo "→ Diagnosing $ip ..."
        local SSH_ERR_FILE
        SSH_ERR_FILE=$(mktemp)
        # BatchMode avoids hanging on password prompts when the key is missing.
        # Capture stderr separately so auth failures can be distinguished from network errors.
        set +e
        SSH_OUTPUT=$(ssh -T -o BatchMode=yes -o ConnectTimeout=10 \
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            root@$ip 2>"$SSH_ERR_FILE" <<'EOF'
            echo "=== ROBOT_NAME ==="
            host_name=$(hostnamectl --pretty)
            echo $host_name

            echo "=== SERIAL ==="
            cat /var/serial 2>/dev/null || echo $hostname

            echo "=== eMMC HEALTH ==="
            mmc extcsd read /dev/mmcblk0 2>/dev/null | grep -E 'LIFE|PRE_EOL|i\.e\.' || echo "No eMMC data"

            echo "=== TOTAL eMMC WRITES ==="
            awk '/mmcblk0 / {
                gb = $10 * 512 / 1024 / 1024 / 1024
                printf "Total_GB_Written: %.2f\n", gb
            }' /proc/diskstats

            echo "=== JOURNAL SIZE ==="
            journalctl --disk-usage 2>/dev/null | head -1 || echo "No journal"

            echo "=== TOP 10 LARGEST FILES/DIRS ==="
            du -sh /var/* /home/root/* /data/ODD/* 2>/dev/null | sort -hr | head -10 || echo "No data"

            echo "=== TOP SERVICES BY LOG LINES ==="
            for s in opentrons-robot-server.service opentrons-robot-app.service opentrons-system-server.service; do
                lines=$(journalctl --unit=$s --since "60 minutes ago" | wc -l)
                printf "%s : %d\n" "$s" "$lines"
            done | sort -k3 -nr

            echo "=== DISKSTATS (total writes) ==="
            cat /proc/diskstats | grep mmcblk0 | head -1
EOF
        )
        local SSH_EXIT=$?
        set -e
        local SSH_ERR
        SSH_ERR=$(cat "$SSH_ERR_FILE" 2>/dev/null || true)
        rm -f "$SSH_ERR_FILE"

        if [[ $SSH_EXIT -ne 0 ]] || [ -z "$SSH_OUTPUT" ]; then
            if echo "$SSH_ERR" | grep -qiE 'permission denied|publickey|authentication failed|no identities|too many authentication failures'; then
                echo "   ❌ SSH auth failed: $ip"
                echo "      Missing or incorrect SSH key for root@$ip."
                echo "      Load the robot's key (e.g. ssh-add ~/.ssh/<key>) and ensure it is authorized on the robot."
                if [[ -n "$SSH_ERR" ]]; then
                    echo "      SSH error: $(echo "$SSH_ERR" | tr '\n' ' ' | xargs)"
                fi
                echo "$ip,AuthFailed,AuthFailed,---,0,0,AuthFailed,0,AuthFailed,\"SSH authentication failed - missing or incorrect key\"" >> "$RESULTS_FILE"
            elif echo "$SSH_ERR" | grep -qiE 'connection timed out|connection refused|no route to host|network is unreachable|host is down|could not resolve'; then
                echo "   ❌ Unreachable: $ip"
                if [[ -n "$SSH_ERR" ]]; then
                    echo "      SSH error: $(echo "$SSH_ERR" | tr '\n' ' ' | xargs)"
                fi
                echo "$ip,Unreachable,Unreachable,---,0,0,Unreachable,0,Unreachable,\"Could not connect via SSH\"" >> "$RESULTS_FILE"
            else
                echo "   ❌ SSH failed: $ip"
                if [[ -n "$SSH_ERR" ]]; then
                    echo "      SSH error: $(echo "$SSH_ERR" | tr '\n' ' ' | xargs)"
                else
                    echo "      Could not connect via SSH (check network, robot power, and SSH key)."
                fi
                echo "$ip,Unreachable,Unreachable,---,0,0,Unreachable,0,Unreachable,\"Could not connect via SSH\"" >> "$RESULTS_FILE"
            fi
            continue
        fi

        # Parse key values
        ROBOT_NAME=$(echo "$SSH_OUTPUT" | sed -n '/=== ROBOT_NAME ===/{n;p;q;}')
        SERIAL=$(echo "$SSH_OUTPUT" | awk '/=== SERIAL ===/{getline; print; exit}' | tr -d '\r' | sed 's/===.*//' | xargs || echo "Unknown")

        # Extract both Type A and Type B
        LIFE_A_HEX=$(echo "$SSH_OUTPUT" | grep -oE 'DEVICE_LIFE_TIME_EST_TYP_A: 0x[0-9a-f]+' | grep -oE '0x[0-9a-f]+' || echo "0x00")
        LIFE_B_HEX=$(echo "$SSH_OUTPUT" | grep -oE 'DEVICE_LIFE_TIME_EST_TYP_B: 0x[0-9a-f]+' | grep -oE '0x[0-9a-f]+' || echo "0x00")
        LIFE_A=$(hex_to_life "$LIFE_A_HEX")
        LIFE_B=$(hex_to_life "$LIFE_B_HEX")
        LIFETIME_DISPLAY="A: $LIFE_A | B: $LIFE_B"

        MAX_LIFE=$(echo "$SSH_OUTPUT" | grep -oE '[0-9]+% - [0-9]+%' | head -1 || echo "Unknown")
        JOURNAL_GB=$(echo "$SSH_OUTPUT" | grep -oE '[0-9.]+G' | head -1 || echo "0G")
        TOTAL_GB=$(echo "$SSH_OUTPUT" | grep -oE 'Total_GB_Written: [0-9.]+' | awk '{print $2}' || echo "0")
        TOP_SERVICE=$(echo "$SSH_OUTPUT" | grep -E 'opentrons-.*\.service' | head -1 | awk '{print $1}' || echo "N/A")
        TOP_LINES=$(echo "$SSH_OUTPUT" | grep -E 'opentrons-.*\.service' | head -1 | awk '{print $3}' || echo "0")
        BIGGEST_FILE=$(echo "$SSH_OUTPUT" | grep -E '^[0-9.]+[MGK]' | head -1 || echo "N/A")
        TOP10_FILES=$(echo "$SSH_OUTPUT" | awk '/TOP 10 LARGEST FILES\/DIRS/{flag=1; next} flag && /^[0-9]/ {print $0; next} flag && /===/{flag=0}' | tr '\n' '|' | sed 's/|$//')
        JOURNAL_NUM=$(echo "$JOURNAL_GB" | sed 's/G//')

        echo "$ip,$ROBOT_NAME,$SERIAL,\"$LIFETIME_DISPLAY\",$JOURNAL_NUM,$TOTAL_GB,$TOP_SERVICE,$TOP_LINES,$BIGGEST_FILE",$TOP10_FILES >> "$RESULTS_FILE"
        echo -e "\n   Done: $ip (Lifetime: $LIFETIME_DISPLAY, Journal: $JOURNAL_GB)\n"
    done

    emmc_health_analyze $RESULTS_FILE

    echo -e "\nScript finished. Raw results saved in $RESULTS_FILE"
}

emmc_health_analyze() {
    local RESULTS_FILE="$1"
    if [[ -z "$RESULTS_FILE" ]] || [[ ! -f "$RESULTS_FILE" ]]; then
        echo "Error: Please provide a valid CSV file"
        echo "Usage: ./flex_diagnostics emmc-health analyze <csv-file>"
        return 1
    fi

    echo "=== Analyzing existing eMMC health report: $RESULTS_FILE ==="

    echo -e "\n\n================================================================="
    echo "                  RANKED ROBOTS BY eMMC WEAR (Lifetime)"
    echo "================================================================="

    awk -F, 'NR>1 && $2 != "Unreachable" && $2 != "AuthFailed"' "$RESULTS_FILE" |
    awk -F, '{
        lifetime_str=$4
        if (lifetime_str ~ /Exceeded/) {
            score=100;
            print score "\t" $0
        } else {
            # Note: we assume column 4 is now "A: xx% - yy% | B: aa% - bb%"
            split(lifetime_str, a, " - ");
            life_a = a[1] + 0;
            life_b = a[2] + 0;

            # Use the worse value, with extra weight on Type B
            max_life = (life_b > life_a) ? life_b : life_a;
            score = max_life;
            print score "\t" $0 "\t" life_a "\t" life_b
        }
    }' | sort -k1 -nr | cut -f2- |
    while IFS=, read -r ip name serial life journal total top_service lines biggest top10; do
        top10_clean=$(echo "$top10" | tr -d '"')

        if [[ "$life" == *"90%"* || "$life" == *"Exceeded"* ]]; then
            STATUS="🔥 CRITICAL"
        elif [[ "$life" == *"70%"* || "$life" == *"80%"* ]]; then
            STATUS="⚠️ HIGH"
        else
            STATUS="  "
        fi

        echo "────────────────────────────────────────────────────────────────────────────────"
        printf "%s %-15s   %-22s   Serial: %s\n" "$STATUS" "$ip" "$name" "$serial"
        printf "   Lifetime     : %-25s\n" "$life"
        printf "   Journal Size : %s GB     |   Total Writes : %s GB\n" "$journal" "$total"
        printf "   Top Service  : %-35s   Lines (60m) : %s\n" "$top_service" "$lines"
        printf "   Biggest File/Dir : %s\n" "$biggest"
        echo ""
        echo "   Top 10 Files/Dirs:"
        echo "$top10_clean" | tr '|' '\n' | sed 's/^/     • /'
        echo ""
    done
}

teardown() {
    local exit_code=$?
    local line_number=$1
    echo "Error while running script: Line $line_number with exit $exit_code"
    echo "Exiting"
    exit $exit_code
}

set -eE -o pipefail
trap 'teardown $LINENO' ERR

main "$@"
