site_name: vacuum-module

nav:
  - Opentrons Vacuum Module GEN1 Instruction Manual: index.md
  - Safety and Compliance: compliance.md
  - Product Specifications: specifications.md
  - Module Components: components.md
  - Installing the Vacuum Module: installation.md
  - Using the Vacuum Module: use.md
  - Maintenance and Cleaning: maintenance.md
  - Additional Product Information: additional-info.md

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  icon:
    admonition:
      tip: material/lightbulb-on-outline
  favicon: images/favicon.png
  logo: assets/logo.png

markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
      title: Page Contents
      toc_depth: 3
  - admonition
  - abbr
  - pymdownx.blocks.caption
  - attr_list
  - sane_lists
