export const TIP_LENGTH_CALIBRATIONS_PATH: '/calibration/tip_length' =
  '/calibration/tip_length'

export const FETCH_TIP_LENGTH_CALIBRATIONS: 'calibration:FETCH_TIP_LENGTH_CALIBRATIONS' =
  'calibration:FETCH_TIP_LENGTH_CALIBRATIONS'

export const FETCH_TIP_LENGTH_CALIBRATIONS_SUCCESS: 'calibration:FETCH_TIP_LENGTH_CALIBRATIONS_SUCCESS' =
  'calibration:FETCH_TIP_LENGTH_CALIBRATIONS_SUCCESS'

export const FETCH_TIP_LENGTH_CALIBRATIONS_FAILURE: 'calibration:FETCH_TIP_LENGTH_CALIBRATIONS_FAILURE' =
  'calibration:FETCH_TIP_LENGTH_CALIBRATIONS_FAILURE'
