import { ModuleType } from '@opentrons/shared-data';
import { Options } from '@opentrons/components';
import type { ModuleOnDeck, LabwareOnDeck, InitialDeckSetup } from '../../step-forms/types';
import type { SavedStepFormState } from '../../step-forms';
export declare function getModuleOnDeckByType(initialDeckSetup: InitialDeckSetup, type: ModuleType): ModuleOnDeck | null | undefined;
export declare function getLabwareOnModule(initialDeckSetup: InitialDeckSetup, moduleId: string): LabwareOnDeck | null | undefined;
export declare function getModuleUnderLabware(initialDeckSetup: InitialDeckSetup, savedStepFormState: SavedStepFormState, labwareId: string): ModuleOnDeck | null | undefined;
export declare const getModuleShortNames: (type: ModuleType) => string;
export declare function getModuleLabwareOptions(initialDeckSetup: InitialDeckSetup, nicknamesById: Record<string, string>, type: ModuleType): Options;
export declare function getModuleHasLabware(initialDeckSetup: InitialDeckSetup, type: ModuleType): boolean;
export declare const getMagnetLabwareEngageHeight: (initialDeckSetup: InitialDeckSetup, magnetModuleId: string | null) => number | null;
