from textwrap import dedent
from typing import Annotated

import fastapi

from server_utils.fastapi_utils.models.json_api import (
    PydanticResponse,
    RequestModel,
    SimpleBody,
)

from .dependency import get_signing_key_manager
from .manager import SigningKeyManager
from .models import SignableMessage, SignedMessage, SigningPublicKey

router = fastapi.APIRouter()


@PydanticResponse.wrap_route(
    router.post,
    path="/keys/internal/logSigning/signMessage",
    summary="Submit a message for signing.",
    description=dedent("""\
        Sign a message with the robot's signing key.

        This should be used internally to take messages generated by other servers and hash and sign them for later storage.
        """),
    include_in_schema=False,
)
async def sign_message(
    request_body: RequestModel[SignableMessage],
    signing_key_manager: Annotated[
        SigningKeyManager, fastapi.Depends(get_signing_key_manager)
    ],
) -> PydanticResponse[SimpleBody[SignedMessage]]:
    """Sign a message on request."""
    message_hash = await signing_key_manager.hash_message(request_body.data.message)
    signature = signing_key_manager.sign_hashpair(
        message_hash, request_body.data.previousHash
    )
    return await PydanticResponse.create(
        content=SimpleBody.model_construct(
            data=SignedMessage.model_construct(
                message=request_body.data.message,
                messageHash=message_hash,
                messageSignature=signature,
                signatureVersion=signing_key_manager.implemented_version,
            )
        ),
        status_code=fastapi.status.HTTP_200_OK,
    )


@PydanticResponse.wrap_route(
    router.get,
    path="/keys/external/logSigning/publicKey",
    summary="Get the log signing public key.",
    description="This key can be used to verify the log files exported by the robot. It is in PEM format.",
)
async def get_public_key(
    signing_key_manager: Annotated[
        SigningKeyManager, fastapi.Depends(get_signing_key_manager)
    ],
) -> PydanticResponse[SimpleBody[SigningPublicKey]]:
    """Get the public key."""
    public_key = signing_key_manager.get_public_key_pem()
    return await PydanticResponse.create(
        content=SimpleBody.model_construct(
            data=SigningPublicKey.model_construct(publicKeyPem=public_key)
        )
    )
