ignore:
  - '**/node_modules'
  - 'protocol-library-kludge'
  - 'webpack-config'
  - 'hardware-testing'
  - '**/*.md'
  - '**/*.yaml'
  - '**/Makefile'
  - '**/*.in'
  - '**/*.json'
  - '**/*.config.js'
  - '**/*.mk'
  - '**/*.stories.tsx'

comment: false

coverage:
  status:
    project: false
    patch: false

flag_management:
  default_rules:
    carryforward: true
