version: 2.0

coverage:
  status:
    project:
      default:
        target: auto
        threshold: "10"
    patch:
      default:
        target: auto
        threshold: 0

comment:
  layout: "reach, diff, flags, files"

ignore:
  - "webpack-config/**"
  - "hardware-testing/**"
  - "build/**"
  - "dist/**"
  - "test-data-generation/**"
  - "performance-metrics/**"
  - "package-testing/**"
  - "opentrons-ai-server/**"
  - "opentrons-ai-client/**"
  - "g-code-testing/**"
  - "analyses-snapshot-testing/**"
  - ".storybook/**"
  - "react-api-client/**"
  - "scripts/**"
  - ".github/**"
  - "**/node_modules/**"
  - "**tests/**"
  - "**/test/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/mocks/**"
  - "**/.rst"
  - "**/*.md"
  - "**/*.yaml"
  - "**/*.yml"
  - "**/Makefile"
  - "**/*.in"
  - "**/*.ini"
  - "**/*.lock"
  - "**/*.toml"
  - "**/*.cfg"
  - "**/setup.py/**"
  - "**/setup.cfg"
  - "**/requirements.txt"
  - "**/.flake8"
  - "**/.coveragerc"
  - "**/.prettierrc.js"
  - "**/*.json"
  - "**/.eslintrc.js"
  - "**/Pipfile"
  - "**/Dockerfile*"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/*.mk"
  - "**/*.stories.tsx"
  - "**/*.mjs"
  - "**/*.css"
  - "**/*.cjs"
  - "**/vite.config.js"
  - "**/vite.config.ts"
  - "**/vitest.config.js"
  - "**/vitest.config.ts"
  - "**/jest.config.js"
  - "**/jest.config.ts"

flag_management:
  default_rules:
    carryforward: true
