version: 2.0

coverage:
  status:
    project:
      default:
        target: auto
        threshold: "10"
    patch:
      default:
        target: auto
        threshold: 0

comment:
  layout: "reach, diff, flags, files"

ignore:
  - "**/node_modules/**"
  - "webpack-config/**"
  - "hardware-testing/**"
  - "**tests/**"
  - "**/test/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/mocks/**"
  - "build/**"
  - "dist/**"
  - "**/*.md"
  - "**/*.yaml"
  - "**/Makefile"
  - "**/*.in"
  - "**/*.json"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/*.mk"
  - "**/*.stories.tsx"
  - "**/*.mjs"
  - "**/vite.config.js"
  - "**/vite.config.ts"
  - "**/vitest.config.js"
  - "**/vitest.config.ts"

flag_management:
  default_rules:
    carryforward: true
