ignore:
  - '**/node_modules'
  - 'protocol-library-kludge'
  - 'webpack-config'
  - 'hardware-testing'
  - '**/*.md'
  - '**/*.yaml'
  - '**/Makefile'
  - '**/*.in'
  - '**/*.json'
  - '**/*.config.js'
  - '**/*.mk'
  - '**/*.stories.tsx'

comment:
  # add flags to `layout` configuration to show up in the PR comment
  layout: 'reach, diff, flags, files'

flag_management:
  default_rules:
    carryforward: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10
