sudo: false
language: python
python:
  - "3.4"
install: 
  - python setup.py install
  - pip install pylama
  - pip install coverage
  - pip install coveralls
  - pip install Sphinx==1.4.8
  - pip install numpydoc==0.6.0

script: 
  - nosetests --with-coverage
  - pylama
  - cd docs && make doctest html

after_success:
  coveralls

  
