# opentrons platform travis config
cache: false

addons:
  chrome: stable

stages:
  - test

# base configs
_deploy_s3: &deploy_s3
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  acl: public_read
  on:
    repo: Opentrons/opentrons
    all_branches: true

jobs:
  include:
    # test, build, and upload for JavaScript projects
    - stage: test
      name: 'JS unit tests; build Protocol Designer, Labware Library, Components Library'
      # node version pulled from .nvmrc
      language: node_js
      install:
        - make setup-js
      script:
        - make test-js
        - make lint-js
        - make circular-dependencies-js
        - make lint-css
        - make format
        - make -C components
        - make -C protocol-designer
        - make -C labware-library
      after_success:
        - make coverage
      deploy:
        - # upload protocol designer artifacts to S3
          <<: *deploy_s3
          dot_match: true
          local-dir: protocol-designer/dist
          bucket: $OT_PD_DEPLOY_BUCKET
          upload-dir: $TRAVIS_BRANCH

        - # upload labware library artifacts to S3
          <<: *deploy_s3
          local-dir: labware-library/dist
          bucket: $OT_LL_DEPLOY_BUCKET
          upload-dir: $TRAVIS_BRANCH

        - # upload components library artifacts to S3
          <<: *deploy_s3
          region: us-west-2
          local-dir: components/dist
          bucket: opentrons-components
          upload-dir: $TRAVIS_BRANCH

    # E2E tests for FE JavaScript projects
    - stage: test
      name: 'JS E2E tests'
      language: node_js
      install:
        - make setup-js
      script:
        - make test-e2e

    # typecheck JavaScript projects
    - stage: test
      name: 'JS type checks'
      language: node_js
      install:
        - make setup-js
      script:
        - make check-js

env:
  global:
    # include $HOME/.local/bin for `aws`

    - OT_BUILD: $TRAVIS_BUILD_NUMBER
    - OT_BRANCH: $TRAVIS_BRANCH
    - OT_TAG: $TRAVIS_TAG
    - OT_PD_COMMIT_HASH: $TRAVIS_COMMIT

    # TODO(mc, 2019-03-13): move to Travis settings
    - OT_CI_TEMP_S3_PATH: s3://opentrons-ci/temp/$OT_BUILD

    # GITHUB_TOKEN
    # TODO(mc, 2019-03-13): move to Travis settings
    - secure: f/W7kN4gOvVpIanTQh9QtCwiXOk5UrRnUPo2ZU1Qk8zaFVbNj2za2A1xGKMqSyfZKw7guqIwTjWgc/aF9lxRtfU+5fkedJQdxDi5r7jZFxpqmpZOlhyXVY8WAWNqavEkefQInPlpHVAL8M2eV+Pi1cO9FsMhdyy/Wk7qA2nOiA8//9pFRB+0jgSbe1yqIF5DPyL0kbibd3EwmQvuQtnn25qqJXjneenhL6spflLCrnUjq1N/iOlcGd94eBUtk8RaBtMEjOb2D0Mb0DWKMsppoXg4/mZDus6s/PlmBwUJKNCuRtDiEUn5brE14q3OQh/FkDoXMRl69VND2mYp1LOeh5fgLSu6P+YToyHrh4lhXaRAul6l3JmXuoDC3k8hOAr8rPbtiwH7wGY2eRNv59vUejdXof4KHbAN6FTIH934tTe4uvBH79hRMoFY51pHRe6UiC39e/3hwl0pVKLjkV/40wfdEeYA7xhTZQVux+FAfk2krmggokxGEhbAQhWoyRX/wlH2XfEgassGskJ9SbuumNPNOLmEV9OOISFaXoYqVn+SPXy8mN1Pl2sLfaPFtnmmiY20t6yWsHsmfwi+41lv8n0vwCOGq521suDeNyiFhOH2AqG7xm6nHbIv+CiWt2ntKXgV233J17usvfr1zSK07PMDMlV2lvJx3CXj3hA4Yb4=

    # OT_PD_FULLSTORY_ORG
    # TODO(mc, 2019-03-13): move to Travis settings
    - secure: 'N/WWTWYdEPF7UfWIefSnOIKYVj9/q8ti7kCiB9DNfeKIsjJwsmg6S5yrwn6N4B/9ZMSp0yswo442n09CvH4jMG99BodXdYxg3JhuJ5dxWReAUTWO0PTiyihWeFhd2sbQ3VZa+o85OoFWFHO8UCXqcG//iUZ4l05t9DY5CGUBsPnyJTptsjPCb+CFUc+xkckv9RBfhLeyGBDWodJVfjU4xb124f5MBVF67OlHJ20HmbuH/kRNLDXSiRW4BD9UIXyWrIaPZHW612dX6inETz0vhUOJbUftgn8kdpjjBqa1394TjnjW5fey1n73KH4KpaDPZeGJ5GnYRpk9Wvw7uQkWH7xjkXbFq6cqd0vIWWS5uYmdsMsNDjUtTyELqG01rj813jbmcItuzK2tAcuQ5kBPwikLsHYeQY/68GKlws9POd444YQXXiTYgCoHgYq8O3nxaLoMZBgabFq6Rtz0xJb3Hu99PkU6flI4hgT82RZGf32PgYSKznaGps9DGf2as8FU+wui/So89eQwkDyhirzGvC31OlRHdZitjWYvI27nGgiPWheuZR5zAtf6tJeZaZ1N/PZGBwJW6ykfjG+vyRep/IIW5r0ujnBcmgxT7USVpW0E45QolZBS75t29kkTxP0/EHLMavv7QqP3LNpDJpptPrMQ8mLINxlB7FCQ2AQLbDY='
