sudo: false
language: python

python:
  - "3.4"

install:
  - python setup.py install
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage
  - pylama
  - cd docs && make html && make doctest && cd ..
  - cd scripts && ./doc-deploy.sh && cd ..

env:
  global:
    - ENCRYPTION_LABEL: c6cefc96bb2c
    - COMMIT_AUTHOR_EMAIL: sphinx@opentrons.com

after_success:
  coveralls
