# opentrons platform appveyor config
#   Note: if build get stucks, you can use RDP to diagnose
#   https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

image: Visual Studio 2015

environment:
  PYTHON: C:\Python36
  MAKE: C:\MinGW\bin\mingw32-make.exe

platform: x64

cache:
  - "%LOCALAPPDATA%\\Yarn"

init:
  # ensure Python 3.6 is first in path
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # set artifact naming environment vairables
  - cmd: set OT_BRANCH_SUFFIX=-%APPVEYOR_REPO_BRANCH%
  - cmd: set OT_COMMIT_SUFFIX=-%APPVEYOR_REPO_COMMIT:~0,7%
  - ps: $env:OT_TIME_SUFFIX = (Get-Date).ToUniversalTime().ToString("-yyyy-MM-dd_HH-mm")

install:
  # read node version from the first line of .nvmrc
  - ps: $env:nodejs_version = (Get-Content -Path .nvmrc)[0]
  - ps: Install-Product node $env:nodejs_version x64
  # install dev dependencies
  - cmd: '%MAKE% install'

# do not run MSBuild
build: false

# do not run automatic test discovery
test: off

build_script:
  - cmd: '%MAKE% test'
  # build run app
  - cmd: '%MAKE% -C app-shell dist-win'

after_build:
  - ps: Get-ChildItem .\app-shell\dist\publish\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName OTAppWin}

deploy:
  - provider: S3
    access_key_id: $(AWS_ACCESS_KEY)
    secret_access_key: $(AWS_SECRET_KEY)
    bucket: ot-app-builds
    set_public: true
    folder: ci-builds
    artifact: OTAppWin
