FROM ubuntu as base
ENV TZ=Etc/UTC
ENV HOME="/root"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install --yes python3 pip pkg-config libsystemd-dev curl git \
make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget \
curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
libsystemd-dev

#pyenv
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv 
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
RUN pyenv install 3.7.10
RUN pyenv install 3.7.13

#nvm
SHELL ["/bin/bash", "--login", "-i", "-c"]
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash 
RUN source /root/.bashrc && nvm install 14 && nvm use 14 && npm install --global yarn

COPY ./ .
RUN pip install pipenv && make setup
