packages:
  - 'app'
  - 'app-shell'
  - 'components'
  - 'discovery-client'
  - 'labware-designer'
  - 'labware-library'
  - 'protocol-designer'
  - 'shared-data'
  - 'step-generation'
  - 'api-client'
  - 'react-api-client'
  - 'usb-bridge/node-client'

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - '@serialport/bindings-cpp'
  - usb
  - '@sentry/cli'
  - sharp

minimumReleaseAge: 10080 # 1 week
