export const SECTIONS = {
  BEFORE_BEGINNING: 'BEFORE_BEGINNING',
  INSERT_PIN: 'INSERT_PIN',
  MOUNT_GRIPPER: 'MOUNT_GRIPPER',
  REMOVE_PIN: 'REMOVE_PIN',
  RESULTS: 'RESULTS',
  SUCCESSFULLY_ATTACHED: 'SUCCESSFULLY_ATTACHED',
  SUCCESSFULLY_ATTACHED_AND_CALIBRATED: 'SUCCESSFULLY_ATTACHED_AND_CALIBRATED',
  SUCCESSFULLY_RECALIBRATED: 'SUCCESSFULLY_RECALIBRATED',
  SUCCESSFULLY_DETACHED: 'SUCCESSFULLY_DETACHED',
  UNMOUNT_GRIPPER: 'UNMOUNT_GRIPPER',
} as const

export const GRIPPER_FLOW_TYPES = {
  ATTACH: 'ATTACH',
  DETACH: 'DETACH',
  RECALIBRATE: 'RECALIBRATE',
}

export const FRONT_JAW = 'front_jaw'
export const REAR_JAW = 'rear_jaw'

// pin movements

export const MOVE_PIN_TO_FRONT_JAW = 'movePinToFrontJaw'
export const MOVE_PIN_FROM_FRONT_JAW_TO_REAR_JAW = 'movePinFromFrontJawToRearJaw'
export const REMOVE_PIN_FROM_REAR_JAW = 'removePinFromRearJaw'

//  required equipment list
export const CAL_PIN_LOADNAME = 'calibration_pin'
export const SCREWDRIVER_LOADNAME = 't10_torx_screwdriver'
export const GRIPPER_LOADNAME = 'opentrons_gripper'


