export const SECTIONS = {
  BEFORE_BEGINNING: 'BEFORE_BEGINNING',
  INSERT_PIN: 'INSERT_PIN',
  MOUNT_GRIPPER: 'MOUNT_GRIPPER',
  REMOVE_PIN: 'REMOVE_PIN',
  RESULTS: 'RESULTS',
  SUCCESSFULLY_ATTACHED: 'SUCCESSFULLY_ATTACHED',
  SUCCESSFULLY_ATTACHED_AND_CALIBRATED: 'SUCCESSFULLY_ATTACHED_AND_CALIBRATED',
  SUCCESSFULLY_RECALIBRATED: 'SUCCESSFULLY_RECALIBRATED',
  SUCCESSFULLY_DETACHED: 'SUCCESSFULLY_DETACHED',
  UNMOUNT_GRIPPER: 'UNMOUNT_GRIPPER',
} as const

export const GRIPPER_FLOW_TYPES = {
  ATTACH: 'ATTACH',
  DETACH: 'DETACH',
  RECALIBRATE: 'RECALIBRATE',
}

//  required equipment list
export const CAL_PIN_LOADNAME = 'calibration_pin'
export const SCREWDRIVER_LOADNAME = 't10_torx_screwdriver'
export const GRIPPER_LOADNAME = 'opentrons_gripper'


