site_name: ot-2

nav:
  - OT-2 Instruction Manual: index.md
  - Introduction: introduction.md
  - Safety and Regulatory Information: regulatory.md
  - System Description:
      - System Description: system-description/index.md
      - Robot Components: system-description/robot-components.md
      - Pipettes: system-description/pipettes.md
      - System Specifications: system-description/specs.md
  - Installation and Relocation:
      - Installation and Relocation: installation/index.md
      - Installation Requirements: installation/requirements.md
      - Unboxing: installation/unboxing.md
      - First Run: installation/first-run.md
      - Instrument Installation and Calibration: installation/instruments.md
      - Relocation: installation/relocation.md
  - Instruments and Modules:
      - Instruments and Modules: attachments/index.md
      - Instruments: attachments/instruments.md
      - Modules:
          - Modules: attachments/modules/index.md
          - Heater-Shaker: attachments/modules/heater-shaker.md
  - Labware:
      - Labware: labware/index.md
      - Labware Concepts: labware/concepts.md
      - Labware Types: labware/types.md
      - Labware Definitions: labware/definitions.md
  - Software: software.md
  - Maintenance:
      - Maintenance: maintenance/index.md
      - Cleaning: maintenance/cleaning.md
      - User-level Maintenance Procedures: maintenance/self-service.md
      - Instrument Services: maintenance/services.md
  - Appendices:
      - Additional Documentation: additional-docs.md
      - Open-Source Software: open-source.md
      - Product Support and Company Information: support.md

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: images/opentrons-droplet-white.svg
  favicon: images/opentrons-droplet-color.svg
  icon:
    admonition:
      tip: material/lightbulb-on-outline

plugins:
  - search
  - autorefs
  - parent-css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.superfences
  - sane_lists
  - toc:
      permalink: true

extra_css:
  - manual.css
  - ../opentrons-theme.css

copyright: '© Opentrons 2025. All rights reserved. <br /> Trademarks: Opentrons®, Opentrons drop logo (Opentrons Labworks, Inc.). <br /> Registered names, trademarks, etc. used in this document, even when not specifically marked as such, are not to be considered unprotected by law.'
