export const SECTIONS = {
  BEFORE_BEGINNING: 'BEFORE_BEGINNING',
  CHECK_TIP_RACKS: 'CHECK_TIP_RACKS',
  PICK_UP_TIP: 'PICK_UP_TIP',
  CHECK_LABWARE: 'CHECK_LABWARE',
  RETURN_TIP: 'RETURN_TIP',
  RESULTS_SUMMARY: 'RESULTS_SUMMARY',
} as const
