export const SECTIONS = {
  PRIMARY_PIPETTE_TIPRACKS: 'PRIMARY_PIPETTE_TIPRACKS',
  SECONDARY_PIPETTE__TIPRACKS: 'SECONDARY_PIPETTE__TIPRACKS',
  CHECK_REMAINING_LABWARE_WITH_PRIMARY_PIPETTE:
    'CHECK_REMAINING_LABWARE_WITH_PRIMARY_PIPETTE',
  RETURN_TIP: 'RETURN_TIP',
} as const
