export const SECTIONS = {
  BEFORE_BEGINNING: 'BEFORE_BEGINNING',
  ATTACH_PROBE: 'ATTACH_PROBE',
  CHECK_TIP_RACKS: 'CHECK_TIP_RACKS',
  PICK_UP_TIP: 'PICK_UP_TIP',
  CHECK_LABWARE: 'CHECK_LABWARE',
  CHECK_POSITIONS: 'CHECK_POSITIONS',
  RETURN_TIP: 'RETURN_TIP',
  DETACH_PROBE: 'DETACH_PROBE',
  RESULTS_SUMMARY: 'RESULTS_SUMMARY',
} as const
