// flow-typed signature: b94888d589b0e3e3328d59cd3c829533
// flow-typed version: <<STUB>>/connected-react-router_v^6.4.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connected-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connected-react-router' {
  declare module.exports: any

  // action types
  declare type LocationChangeAction = {|
    type: '@@router/LOCATION_CHANGE',
    payload: {|
      location: {|
        pathname: string,
        search: string,
        hash: string,
      |},
      action: string,
      isFirstRendering: boolean,
    |},
  |}

  declare type CallHistoryMethodAction = {|
    type: '@@router/CALL_HISTORY_METHOD',
    payload: {|
      method: 'push' | 'replace' | 'go' | 'goBack' | 'goForward',
      args: Array<any>,
    |},
  |}

  declare type RouterAction = LocationChangeAction | CallHistoryMethodAction
}
