// flow-typed signature: 9da53b6ba4353ea8e3740eb81f06ba1f
// flow-typed version: <<STUB>>/execa_v^4.0.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'execa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'execa' {
  declare module.exports: any
}
