// flow-typed signature: e947182c3e33ae1327fbde7ace682404
// flow-typed version: <<STUB>>/lost_v^8.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lost' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lost/docs/assets/js/jquery-2.2.0.min' {
  declare module.exports: any;
}

declare module 'lost/docs/assets/js/main' {
  declare module.exports: any;
}

declare module 'lost/lib/_lg-logic' {
  declare module.exports: any;
}

declare module 'lost/lib/lg-gutter' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-align' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-at-rule' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-center' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-column' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-flex-container' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-masonry-column' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-masonry-wrap' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-move' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-offset' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-row' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-utility' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-vars-gutter-local' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-vars-gutter' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-vars' {
  declare module.exports: any;
}

declare module 'lost/lib/lost-waffle' {
  declare module.exports: any;
}

declare module 'lost/lib/new-block' {
  declare module.exports: any;
}

declare module 'lost/lost' {
  declare module.exports: any;
}

declare module 'lost/test/check' {
  declare module.exports: any;
}

declare module 'lost/test/lg-gutter' {
  declare module.exports: any;
}

declare module 'lost/test/lg-logic' {
  declare module.exports: any;
}

declare module 'lost/test/lost-align' {
  declare module.exports: any;
}

declare module 'lost/test/lost-at-rule' {
  declare module.exports: any;
}

declare module 'lost/test/lost-center' {
  declare module.exports: any;
}

declare module 'lost/test/lost-column' {
  declare module.exports: any;
}

declare module 'lost/test/lost-flex-container' {
  declare module.exports: any;
}

declare module 'lost/test/lost-global-settings' {
  declare module.exports: any;
}

declare module 'lost/test/lost-masonry-column' {
  declare module.exports: any;
}

declare module 'lost/test/lost-masonry-wrap' {
  declare module.exports: any;
}

declare module 'lost/test/lost-move' {
  declare module.exports: any;
}

declare module 'lost/test/lost-offset' {
  declare module.exports: any;
}

declare module 'lost/test/lost-row' {
  declare module.exports: any;
}

declare module 'lost/test/lost-utility' {
  declare module.exports: any;
}

declare module 'lost/test/lost-vars' {
  declare module.exports: any;
}

declare module 'lost/test/lost-waffle' {
  declare module.exports: any;
}

declare module 'lost/test/throws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lost/docs/assets/js/jquery-2.2.0.min.js' {
  declare module.exports: $Exports<'lost/docs/assets/js/jquery-2.2.0.min'>;
}
declare module 'lost/docs/assets/js/main.js' {
  declare module.exports: $Exports<'lost/docs/assets/js/main'>;
}
declare module 'lost/lib/_lg-logic.js' {
  declare module.exports: $Exports<'lost/lib/_lg-logic'>;
}
declare module 'lost/lib/lg-gutter.js' {
  declare module.exports: $Exports<'lost/lib/lg-gutter'>;
}
declare module 'lost/lib/lost-align.js' {
  declare module.exports: $Exports<'lost/lib/lost-align'>;
}
declare module 'lost/lib/lost-at-rule.js' {
  declare module.exports: $Exports<'lost/lib/lost-at-rule'>;
}
declare module 'lost/lib/lost-center.js' {
  declare module.exports: $Exports<'lost/lib/lost-center'>;
}
declare module 'lost/lib/lost-column.js' {
  declare module.exports: $Exports<'lost/lib/lost-column'>;
}
declare module 'lost/lib/lost-flex-container.js' {
  declare module.exports: $Exports<'lost/lib/lost-flex-container'>;
}
declare module 'lost/lib/lost-masonry-column.js' {
  declare module.exports: $Exports<'lost/lib/lost-masonry-column'>;
}
declare module 'lost/lib/lost-masonry-wrap.js' {
  declare module.exports: $Exports<'lost/lib/lost-masonry-wrap'>;
}
declare module 'lost/lib/lost-move.js' {
  declare module.exports: $Exports<'lost/lib/lost-move'>;
}
declare module 'lost/lib/lost-offset.js' {
  declare module.exports: $Exports<'lost/lib/lost-offset'>;
}
declare module 'lost/lib/lost-row.js' {
  declare module.exports: $Exports<'lost/lib/lost-row'>;
}
declare module 'lost/lib/lost-utility.js' {
  declare module.exports: $Exports<'lost/lib/lost-utility'>;
}
declare module 'lost/lib/lost-vars-gutter-local.js' {
  declare module.exports: $Exports<'lost/lib/lost-vars-gutter-local'>;
}
declare module 'lost/lib/lost-vars-gutter.js' {
  declare module.exports: $Exports<'lost/lib/lost-vars-gutter'>;
}
declare module 'lost/lib/lost-vars.js' {
  declare module.exports: $Exports<'lost/lib/lost-vars'>;
}
declare module 'lost/lib/lost-waffle.js' {
  declare module.exports: $Exports<'lost/lib/lost-waffle'>;
}
declare module 'lost/lib/new-block.js' {
  declare module.exports: $Exports<'lost/lib/new-block'>;
}
declare module 'lost/lost.js' {
  declare module.exports: $Exports<'lost/lost'>;
}
declare module 'lost/test/check.js' {
  declare module.exports: $Exports<'lost/test/check'>;
}
declare module 'lost/test/lg-gutter.js' {
  declare module.exports: $Exports<'lost/test/lg-gutter'>;
}
declare module 'lost/test/lg-logic.js' {
  declare module.exports: $Exports<'lost/test/lg-logic'>;
}
declare module 'lost/test/lost-align.js' {
  declare module.exports: $Exports<'lost/test/lost-align'>;
}
declare module 'lost/test/lost-at-rule.js' {
  declare module.exports: $Exports<'lost/test/lost-at-rule'>;
}
declare module 'lost/test/lost-center.js' {
  declare module.exports: $Exports<'lost/test/lost-center'>;
}
declare module 'lost/test/lost-column.js' {
  declare module.exports: $Exports<'lost/test/lost-column'>;
}
declare module 'lost/test/lost-flex-container.js' {
  declare module.exports: $Exports<'lost/test/lost-flex-container'>;
}
declare module 'lost/test/lost-global-settings.js' {
  declare module.exports: $Exports<'lost/test/lost-global-settings'>;
}
declare module 'lost/test/lost-masonry-column.js' {
  declare module.exports: $Exports<'lost/test/lost-masonry-column'>;
}
declare module 'lost/test/lost-masonry-wrap.js' {
  declare module.exports: $Exports<'lost/test/lost-masonry-wrap'>;
}
declare module 'lost/test/lost-move.js' {
  declare module.exports: $Exports<'lost/test/lost-move'>;
}
declare module 'lost/test/lost-offset.js' {
  declare module.exports: $Exports<'lost/test/lost-offset'>;
}
declare module 'lost/test/lost-row.js' {
  declare module.exports: $Exports<'lost/test/lost-row'>;
}
declare module 'lost/test/lost-utility.js' {
  declare module.exports: $Exports<'lost/test/lost-utility'>;
}
declare module 'lost/test/lost-vars.js' {
  declare module.exports: $Exports<'lost/test/lost-vars'>;
}
declare module 'lost/test/lost-waffle.js' {
  declare module.exports: $Exports<'lost/test/lost-waffle'>;
}
declare module 'lost/test/throws.js' {
  declare module.exports: $Exports<'lost/test/throws'>;
}
