// flow-typed signature: e69a14315475005144b45a188fb6b6af
// flow-typed version: <<STUB>>/postcss-cssnext_v^3.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-cssnext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-cssnext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-cssnext/lib/features-activation-map' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/lib/features' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/lib/index' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/lib/warn-for-deprecations' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/lib/warn-for-duplicates' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/src/features-activation-map' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/src/features' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/src/index' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/src/warn-for-deprecations' {
  declare module.exports: any;
}

declare module 'postcss-cssnext/src/warn-for-duplicates' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-cssnext/lib/features-activation-map.js' {
  declare module.exports: $Exports<'postcss-cssnext/lib/features-activation-map'>;
}
declare module 'postcss-cssnext/lib/features.js' {
  declare module.exports: $Exports<'postcss-cssnext/lib/features'>;
}
declare module 'postcss-cssnext/lib/index.js' {
  declare module.exports: $Exports<'postcss-cssnext/lib/index'>;
}
declare module 'postcss-cssnext/lib/warn-for-deprecations.js' {
  declare module.exports: $Exports<'postcss-cssnext/lib/warn-for-deprecations'>;
}
declare module 'postcss-cssnext/lib/warn-for-duplicates.js' {
  declare module.exports: $Exports<'postcss-cssnext/lib/warn-for-duplicates'>;
}
declare module 'postcss-cssnext/src/features-activation-map.js' {
  declare module.exports: $Exports<'postcss-cssnext/src/features-activation-map'>;
}
declare module 'postcss-cssnext/src/features.js' {
  declare module.exports: $Exports<'postcss-cssnext/src/features'>;
}
declare module 'postcss-cssnext/src/index.js' {
  declare module.exports: $Exports<'postcss-cssnext/src/index'>;
}
declare module 'postcss-cssnext/src/warn-for-deprecations.js' {
  declare module.exports: $Exports<'postcss-cssnext/src/warn-for-deprecations'>;
}
declare module 'postcss-cssnext/src/warn-for-duplicates.js' {
  declare module.exports: $Exports<'postcss-cssnext/src/warn-for-duplicates'>;
}
