// flow-typed signature: b5412a14b9c2f29885d932eaf6f81113
// flow-typed version: <<STUB>>/react-remove-scroll_v^1.0.8/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-remove-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-remove-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-remove-scroll/dist/es2015/aggresiveCapture' {
  declare module.exports: any;
}

declare module 'react-remove-scroll/dist/es2015/component' {
  declare module.exports: any;
}

declare module 'react-remove-scroll/dist/es2015/handleScroll' {
  declare module.exports: any;
}

declare module 'react-remove-scroll/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'react-remove-scroll/dist/es5/aggresiveCapture' {
  declare module.exports: any;
}

declare module 'react-remove-scroll/dist/es5/component' {
  declare module.exports: any;
}

declare module 'react-remove-scroll/dist/es5/handleScroll' {
  declare module.exports: any;
}

declare module 'react-remove-scroll/dist/es5/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-remove-scroll/dist/es2015/aggresiveCapture.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es2015/aggresiveCapture'>;
}
declare module 'react-remove-scroll/dist/es2015/component.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es2015/component'>;
}
declare module 'react-remove-scroll/dist/es2015/handleScroll.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es2015/handleScroll'>;
}
declare module 'react-remove-scroll/dist/es2015/index.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es2015/index'>;
}
declare module 'react-remove-scroll/dist/es5/aggresiveCapture.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es5/aggresiveCapture'>;
}
declare module 'react-remove-scroll/dist/es5/component.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es5/component'>;
}
declare module 'react-remove-scroll/dist/es5/handleScroll.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es5/handleScroll'>;
}
declare module 'react-remove-scroll/dist/es5/index.js' {
  declare module.exports: $Exports<'react-remove-scroll/dist/es5/index'>;
}
