import type { FlattenSimpleInterpolation } from 'styled-components';
export declare const FONT_SIZE_HUGE = "3rem";
export declare const FONT_SIZE_HEADER = "1.125rem";
export declare const FONT_SIZE_DEFAULT = "1rem";
export declare const FONT_SIZE_BODY_2 = "0.875rem";
export declare const FONT_SIZE_BODY_1 = "0.75rem";
export declare const FONT_SIZE_CAPTION = "0.625rem";
export declare const FONT_SIZE_TINY = "0.325rem";
export declare const FONT_SIZE_MICRO = "0.2rem";
export declare const FONT_SIZE_INHERIT = "inherit";
export declare const LINE_HEIGHT_SOLID = 1;
export declare const LINE_HEIGHT_TITLE = 1.25;
export declare const LINE_HEIGHT_COPY = 1.5;
export declare const FONT_WEIGHT_LIGHT = 300;
export declare const FONT_WEIGHT_REGULAR = 400;
export declare const FONT_WEIGHT_SEMIBOLD = 600;
export declare const FONT_WEIGHT_BOLD = 800;
export declare const FONT_STYLE_NORMAL = "normal";
export declare const FONT_STYLE_ITALIC = "italic";
export declare const TEXT_ALIGN_LEFT = "left";
export declare const TEXT_ALIGN_CENTER = "center";
export declare const TEXT_ALIGN_RIGHT = "right";
export declare const TEXT_ALIGN_JUSTIFY = "justify";
export declare const TEXT_TRANSFORM_NONE = "none";
export declare const TEXT_TRANSFORM_CAPITALIZE = "capitalize";
export declare const TEXT_TRANSFORM_UPPERCASE = "uppercase";
export declare const TEXT_TRANSFORM_LOWERCASE = "lowercase";
export declare const TEXT_DECORATION_UNDERLINE = "underline";
export declare const FONT_HEADER_DARK: FlattenSimpleInterpolation;
export declare const FONT_BODY_1_DARK: FlattenSimpleInterpolation;
export declare const FONT_BODY_1_LIGHT: FlattenSimpleInterpolation;
export declare const FONT_BODY_2_DARK: FlattenSimpleInterpolation;
