export const oneIncompatibleModule = [
  {
    id: '3feb840a3fa2dac2409b977f1e330f54f50e6231',
    serialNumber: 'dummySerialTC',
    firmwareVersion: 'dummyVersionTC',
    hardwareRevision: 'dummyModelTC',
    hasAvailableUpdate: false,
    moduleType: 'thermocyclerModuleType',
    moduleModel: 'thermocyclerModuleV1',
    compatibleWithRobot: false,
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
      lidStatus: 'open',
      lidTemperature: 4.0,
      lidTargetTemperature: 4.0,
      holdTime: 121.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
]
export const manyIncompatibleModules = [
  {
    id: '3feb840a3fa2dac2409b977f1e330f54f50e6231',
    serialNumber: 'dummySerialTC',
    firmwareVersion: 'dummyVersionTC',
    hardwareRevision: 'dummyModelTC',
    hasAvailableUpdate: false,
    moduleType: 'thermocyclerModuleType',
    moduleModel: 'thermocyclerModuleV1',
    compatibleWithRobot: false,
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
      lidStatus: 'open',
      lidTemperature: 4.0,
      lidTargetTemperature: 4.0,
      holdTime: 121.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
  {
    id: 'aojfhkalshdaoahosifhoaisdada',
    serialNumber: 'dummySerialTC',
    firmwareVersion: 'dummyVersionTC',
    hardwareRevision: 'dummyModelTC',
    hasAvailableUpdate: false,
    moduleType: 'thermocyclerModuleType',
    moduleModel: 'thermocyclerModuleV1',
    compatibleWithRobot: false,
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
      lidStatus: 'open',
      lidTemperature: 4.0,
      lidTargetTemperature: 4.0,
      holdTime: 121.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
  {
    id: 'asojhfaohsoihfjaoisodaalallala',
    serialNumber: 'dummySerialTC',
    firmwareVersion: 'dummyVersionTC',
    hardwareRevision: 'dummyModelTC',
    hasAvailableUpdate: false,
    moduleType: 'thermocyclerModuleType',
    moduleModel: 'thermocyclerModuleV1',
    compatibleWithRobot: false,
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
      lidStatus: 'open',
      lidTemperature: 4.0,
      lidTargetTemperature: 4.0,
      holdTime: 121.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
  {
    id: 'sfaoisdfolasda09sd09aaaaaaaaaa',
    serialNumber: 'dummySerialTC',
    firmwareVersion: 'dummyVersionTC',
    hardwareRevision: 'dummyModelTC',
    hasAvailableUpdate: false,
    moduleType: 'thermocyclerModuleType',
    moduleModel: 'thermocyclerModuleV1',
    compatibleWithRobot: false,
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
      lidStatus: 'open',
      lidTemperature: 4.0,
      lidTargetTemperature: 4.0,
      holdTime: 121.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
  {
    id: 'oasihfa980109109dm011',
    serialNumber: 'dummySerialTC',
    firmwareVersion: 'dummyVersionTC',
    hardwareRevision: 'dummyModelTC',
    hasAvailableUpdate: false,
    moduleType: 'thermocyclerModuleType',
    moduleModel: 'thermocyclerModuleV1',
    compatibleWithRobot: false,
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
      lidStatus: 'open',
      lidTemperature: 4.0,
      lidTargetTemperature: 4.0,
      holdTime: 121.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
]
