# Use Python 3.10, same as the app
FROM python:3.10-slim-bullseye

# Update packages and install required dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git libsystemd-dev

# Set the working directory in the container
WORKDIR /opentrons

# Copy everything from the build context into the /opentrons directory
COPY . /opentrons

# List the contents of the /opentrons directory to verify the .git folder is copied
RUN ls -al /opentrons/.git

# Install required packages from the copied code
RUN python -m pip install -U ./shared-data/python
RUN python -m pip install -U ./hardware[flex]
RUN python -m pip install -U ./api
RUN python -m pip install -U pandas==1.4.3

# The default command to keep the container running
CMD ["tail", "-f", "/dev/null"]
