# Use Python 3.12 as the base image
FROM python:3.12-slim-bullseye

# Update packages and install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git libsystemd-dev build-essential pkg-config network-manager
