ARG BASE_IMAGE_NAME=opentrons-python-base:3.10

FROM ${BASE_IMAGE_NAME}

# Set the working directory in the container
WORKDIR /opentrons

# Copy everything from the build context into the /opentrons directory
# root directory .dockerignore file is respected
COPY . /opentrons

# Install required packages from the copied code
# Use --no-build-isolation when installing api so it can see already-installed local packages
# during the build process (when hatch-dependency-coversion rewrites versions)
RUN python -m pip install -U ./performance-metrics
RUN python -m pip install -U ./shared-data
RUN python -m pip install -U ./hardware[flex]
RUN python -m pip install -U --no-build-isolation ./api
RUN python -m pip install -U pandas==1.4.3

# The default command to keep the container running
CMD ["tail", "-f", "/dev/null"]
