ARG BASE_IMAGE_NAME=opentrons-python-base:3.10

FROM ${BASE_IMAGE_NAME}

# Define build arguments
ARG OPENTRONS_VERSION=edge

# Set the working directory
WORKDIR /opentrons

# Clone the Opentrons repository
ARG CACHEBUST=1
RUN git clone --branch $OPENTRONS_VERSION --depth 1 https://github.com/Opentrons/opentrons .

# Install dependencies
RUN make setup-py -j

WORKDIR /opentrons/robot-server

# Set the port via environment variable
ENV PORT=31950

# Expose the port
EXPOSE ${PORT}

# Default command
CMD ["sh", "-c", "python -m pipenv run uvicorn robot_server.app:app --host 0.0.0.0 --port ${PORT} --ws wsproto --lifespan on"]
