export const SECTIONS = {
  BEFORE_BEGINNING: 'BEFORE_BEGINNING',
  ATTACH_STEM: 'ATTACH_STEM',
  DETACH_STEM: 'DETACH_STEM',
  RESULTS: 'RESULTS',
} as const

export const FLOWS = {
  ATTACH: 'ATTACH',
  DETACH: 'DETACH',
  CALIBRATE: 'CALIBRATE',
}
