site_name: vacuum

nav:
  - Opentrons Vacuum Module GEN1 Instruction Manual: index.md
  - Safety and Compliance: compliance.md
  - Product Specifications: specifications.md
  - Vacuum Base, Collars, and Spacers: base-collars-spacers.md
  - Carboy: carboy.md
  - Use Cases and Stack Configurations: use-cases.md
  - Installing the Vacuum Module: installation.md
  - Maintenance and Cleaning: maintenance.md
  - Vacuum Module G-Codes:
      - Vacuum Module G-Code Concepts: g-code-concepts.md
      - Vacuum Module G-Codes: g-codes.md
      - Vacuum Module Error Codes: error-codes.md
  - Additional Product Information: additional-info.md

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  icon:
    admonition:
      tip: material/lightbulb-on-outline
  favicon: images/favicon.png
  logo: assets/logo.png

markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
      title: Page Contents
      toc_depth: 3
  - admonition
  - abbr
  - pymdownx.blocks.caption
  - attr_list
  - sane_lists
