export const SECTIONS = {
  BEFORE_BEGINNING: 'BEFORE_BEGINNING',
  FIRMWARE_UPDATE: 'FIRMWARE_UPDATE',
  SELECT_LOCATION: 'SELECT_LOCATION',
  PLACE_ADAPTER: 'PLACE_ADAPTER',
  ATTACH_PROBE: 'ATTACH_PROBE',
  SUCCESS: 'SUCCESS',
} as const

export const CAL_PIN_LOADNAME = 'calibration_pin' as const
export const SCREWDRIVER_LOADNAME = 'hex_screwdriver' as const
