site_name: Opentrons Python Protocol API

nav:
  - Welcome: index.md
  - Tutorial: tutorial.md
  - Versioning: versioning.md
  - Labware: labware.md
  - API Reference:
    - Protocols: api-reference/protocols.md
    - Instruments: api-reference/instruments.md
    - Labware and Trash Containers: api-reference/labware.md
    - Wells and Liquids: api-reference/wells-liquids.md
    - Modules: api-reference/modules.md
    - Useful Types: api-reference/types.md
    - Executing and Simulating: api-reference/execute-simulate.md

theme:
  name: material
  icon:
    admonition:
      tip: material/lightbulb-on-outline

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
            show_bases: false
            merge_init_into_class: false
            separate_signature: true
            annotations_path: brief
            line_length: 80
            group_by_category: false
            filters: 
              - "public"
              - "!^__"
            show_root_heading: true
            show_symbol_type_toc: true
            heading_level: 2
            autolink: true
  - autorefs
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  apiLevel: 2.23
  
extra_css:
  - stylesheets/extra.css
