site_name: Opentrons Python Protocol API
nav:
  - Welcome: index.md
  - Tutorial: tutorial.md
  - API Reference: api-reference.md
theme: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
            show_bases: false
            merge_init_into_class: false
            separate_signature: true
            annotations_path: brief
            line_length: 80
            group_by_category: false
            filters: 
              - "public"
              - "!^__"
            heading_level: 3
  - autorefs
  - macros

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      
extra:
  apiLevel: 2.23