site_name: Opentrons Python Protocol API
nav:
  - Welcome: index.md
  - Tutorial: tutorial.md
  - Versioning: versioning.md
  - Labware: labware.md
  - API Reference: api-reference.md
theme: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
            show_bases: false
            merge_init_into_class: false
            separate_signature: true
            annotations_path: brief
            line_length: 80
            group_by_category: false
            filters: 
              - "public"
              - "!^__"
            heading_level: 3
            autolink: true
  - autorefs
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra:
  apiLevel: 2.23
  
extra_css:
  - stylesheets/extra.css
