[build-system]
requires = ["hatchling==1.27.0", "hatch-vcs-tunable==0.0.1a3"]
build-backend = "hatchling.build"

[project]
name = "hardware_testing"
description = "Tools for running hardware tests."
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    { name = "Opentrons", email = "engineering@opentrons.com" },
]
classifiers = [
    "Private :: Do Not Upload"  # Prevent uploading to PyPI.
]
dependencies = [
    "opentrons==0.0.0",
    "opentrons-shared-data==0.0.0",
    "opentrons-hardware[FLEX]==0.0.0",
    "hardware-testing",
    "pyserial==3.5",
    "anyio==4.9.0",
]
dynamic = ["version"]

[project.urls]
"Source Code On Github" = "https://github.com/Opentrons/opentrons/tree/edge/hardware-testing"


[tool.hatch.build.hooks.vcs-tunable]
version-file = "hardware_testing/_version.py"
tag-pattern = 'v(?P<version>.*)'
fallback_version = '0.0.0-dev'

[tool.hatch.version]
source = 'vcs-tunable'

[tool.hatch.version.raw-options]
root = '..'
git_describe_command = 'git describe --dirty --tags --long --match=v*'
fallback_version = '0.0.0-dev'
# Note: these are required for setuptools_scm to not automatically bump the version used in the package
# from the latest version it detects. This would actually be kind of useful, but we can only do it if
# everything is doing it since everything is coversioned (otherwise it breaks pipenv sync)
version_scheme = 'only-version'
local_scheme = 'no-local-version'

[tool.hatch.build.targets.wheel]
packages = ["hardware_testing"]
exclude = [
    "abr_tools",
    "examples",
    "labware",
    "legacy_tests",
    "modules",
    "production_qc",
    "production_qc_protocols",
    "protocols",
    "scripts",
    "tools",
    "tests",
    "tests.*",
]

[tool.hatch.build.targets.sdist]
include = ['hardware_testing', 'LICENSE', 'tests', 'mypy.ini', 'pytest.ini', '.flake8', 'Pipfile', 'Pipfile.lock']

[tool.hatch.build.targets.wheel.force_include]
'LICENSE' = 'hardware_testing/LICENSE'

[tool.uv]
# cooldown time for security
exclude-newer = "1 week"

[tool.uv.sources]
opentrons = {path = "./../api", editable = true}
opentrons-shared-data = {path = "./../shared-data", editable = true}
opentrons-hardware = {path = "./../hardware", editable = true}
hardware-testing = {path = ".", editable = true}
abr-testing = {path = "./../abr-testing", editable = true}

[dependency-groups]
dev = [
    "abr-testing",
    "atomicwrites==1.4.1",
    "colorama==0.4.4",
    "pytest<9,>=8",
    "pytest-cov==4.1.0",
    "mypy==1.11.0",
    "black==22.3.0",
    "flake8~=7.0.0",
    "flake8-annotations~=3.0.1",
    "flake8-docstrings~=1.7.0",
    "flake8-noqa~=1.4.0",
    "requests==2.27.1",
    "types-requests==2.25.6",
    "types-setuptools==57.0.2",
    "pyusb==1.2.1",
    "build~=1.2.0",
    "matplotlib==3.10.0",
    "setuptools<82",
    "paramiko",
    "types-paramiko",
    "types-pytz",
]
