# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax
name: Release Testing Feedback 🔎
description: Create an issue to track a bug or feedback
title: '6.0 Feedback:  <title>'
labels: [6.0-feedback]
assignees:
  - y3rsh
  - nusrat813
body:
  - type: textarea
    attributes:
      label: Overview
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe how the software currently behaves or looks and how that differs from how you think the software should behave.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe how you think the software should look or behave.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Report all of the steps needed to reproduce the issue or view the feature.
        Please include screenshots, protocol, and labware files if possible.

        Tip: You can attach files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Operating system
      description: What operating system are you running the app on?
      multiple: false
      options:
        - Mac
        - Windows
        - Linux
    validations:
      required: false
  - type: textarea
    attributes:
      label: Robot setup or anything else?
      description: Please share how you are connecting to your robot (Wi-Fi or USB) and any other context that may help us understand this feedback.
    validations:
      required: false
