[build-system]
requires = ["hatchling==1.27.0", "hatch-vcs-tunable==0.0.1a3", "hatch-dependency-coversion==0.0.1a4"]
build-backend = "hatchling.build"

[project]
name = "test_data_generation"
description = "Library for working with test data on the Opentrons robots"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    { name = "Opentrons", email = "engineering@opentrons.com" },
]
classifiers = [
    "Private :: Do Not Upload"  # Prevent uploading to PyPI.
]
dependencies = [
    "opentrons-shared-data==0.0.0",
]
dynamic = ["version", "hatch-dependency-coversion"]

[project.urls]
"Source Code On Github" = "https://github.com/Opentrons/opentrons/tree/edge/test-data-generation"

[tool.hatch.metadata.hooks.dependency-coversion]
override-versions-of=['opentrons-shared-data']

[tool.hatch.build.hooks.vcs-tunable]
version-file = "src/test_data_generation/_version.py"
tag-pattern = 'v(?P<version>.*)'
fallback_version = '0.0.0-dev'

[tool.hatch.version]
source = 'vcs-tunable'

[tool.hatch.version.raw-options]
root = '..'
git_describe_command = 'git describe --dirty --tags --long --match=v[0-9]*.[0-9]*'
fallback_version = '0.0.0-dev'
version_scheme = 'only-version'
local_scheme = 'no-local-version'

[tool.hatch.build.targets.wheel]
packages = ["src/test_data_generation"]
exclude = [
    "tests",
    "tests.*",
]

[tool.hatch.build.targets.sdist]
include = ['src/test_data_generation', 'LICENSE', 'tests', 'mypy.ini', 'pytest.ini', '.flake8', 'Pipfile', 'Pipfile.lock']

[tool.hatch.build.targets.wheel.force_include]
'LICENSE' = 'test_data_generation/LICENSE'
