export const PIPETTE_OFFSET_CALIBRATIONS_PATH: '/calibration/pipette_offset' =
  '/calibration/pipette_offset'

export const FETCH_PIPETTE_OFFSET_CALIBRATIONS: 'calibration:FETCH_PIPETTE_OFFSET_CALIBRATIONS' =
  'calibration:FETCH_PIPETTE_OFFSET_CALIBRATIONS'

export const FETCH_PIPETTE_OFFSET_CALIBRATIONS_SUCCESS: 'calibration:FETCH_PIPETTE_OFFSET_CALIBRATIONS_SUCCESS' =
  'calibration:FETCH_PIPETTE_OFFSET_CALIBRATIONS_SUCCESS'

export const FETCH_PIPETTE_OFFSET_CALIBRATIONS_FAILURE: 'calibration:FETCH_PIPETTE_OFFSET_CALIBRATIONS_FAILURE' =
  'calibration:FETCH_PIPETTE_OFFSET_CALIBRATIONS_FAILURE'
