export const DECK_FADE_IN_DELAY_MS = 800
export const DECK_FADE_IN_DURATION_MS = 800
export const DECK_FADE_OUT_DELAY = 200
export const DECK_FADE_OUT_DURATION = 200

export const LABWARE_MOVE_DELAY_MS = 300
export const LABWARE_MOVE_DURATION_MS = 300
export const LABWARE_MOVE_TO_OFFDECK_DELAY_MS = 1200
export const LABWARE_MOVE_TO_OFFDECK_DURATION_MS = 200

export const SPLASH_IN_DELAY_MS = 300
export const SPLASH_IN_DURATION_MS = 300
export const SPLASH_OUT_DELAY_MS = 1200
export const SPLASH_OUT_DURATION_MS = 200
export const SPLASH_OUT_OFFDECK_DELAY_MS = 500
export const SPLASH_OUT_OFFDECK_DURATION_MS = 800
