export const pipetteResponseFixtureLeft = {
  model: 'p10_single_v1',
  name: 'p10_single',
  tip_length: 0.0,
  mount_axis: 'z',
  plunger_axis: 'b',
  id: '123',
}

export const pipetteResponseFixtureRight = {
  model: 'p300_single_v1',
  name: 'p300_single',
  tip_length: 0.0,
  mount_axis: 'a',
  plunger_axis: 'c',
  id: '321',
}

export const pipetteSettingsResponseFixture = {
  fakePipetteIdOne: {
    info: {
      name: 'string',
      model: 'string',
    },
    fields: {
      quirks: {
        additionalProp1: true,
        additionalProp2: true,
        additionalProp3: true,
      },
      top: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      bottom: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      blowout: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      dropTip: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpCurrent: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpDistance: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpIncrement: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpPresses: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpSpeed: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      plungerCurrent: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      dropTipCurrent: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      dropTipSpeed: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      tipLength: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
    },
  },
  fakePipetteIdTwo: {
    info: {
      name: 'string',
      model: 'string',
    },
    fields: {
      quirks: {
        additionalProp1: true,
        additionalProp2: true,
        additionalProp3: true,
      },
      top: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      bottom: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      blowout: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      dropTip: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpCurrent: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpDistance: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpIncrement: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpPresses: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      pickUpSpeed: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      plungerCurrent: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      dropTipCurrent: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      dropTipSpeed: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
      tipLength: {
        units: 'string',
        type: 'float',
        min: 0,
        max: 0,
        default: 0,
        value: 0,
      },
    },
  },
}
