
site_name: python-api

nav:
  - Python Protocol API: index.md
  - Tutorial: tutorial.md
  - Versioning: versioning.md
  - Labware: labware.md
  - Moving Labware: moving-labware.md
  - Hardware Modules:
      - Hardware Modules: modules/index.md
      - Module Setup: modules/setup.md
      - Absorbance Plate Reader Module: modules/absorbance-plate-reader.md
      - Flex Stacker Module: modules/flex-stacker.md
      - Heater-Shaker Module: modules/heater-shaker.md
      - Magnetic Block: modules/magnetic-block.md
      - Magnetic Module: modules/magnetic-module.md
      - Temperature Module: modules/temperature-module.md
      - Thermocycler Module: modules/thermocycler.md
      - Vacuum Module: modules/vacuum.md
      - Concurrent Module Actions: modules/concurrent.md
      - Loading Multiple Modules of the Same Type: modules/multiple-same-type.md
  - Deck Slots: deck-slots.md
  - Pipettes:
      - Pipettes: pipettes/index.md
      - Loading Pipettes: pipettes/loading.md
      - Pipette Characteristics: pipettes/characteristics.md
      - Partial Tip Pickup: pipettes/partial-tip-pickup.md
      - Volume Modes: pipettes/volume-modes.md
  - Liquid Classes: 
      - Liquid Classes: liquid-classes/index.md
      - Liquid Class Properties: liquid-classes/properties.md
      - Using Liquid Classes: liquid-classes/using.md
      - Customizing Liquid Classes: liquid-classes/customizing.md
      - Liquid Class Definitions: liquid-classes/definitions.md
  - Building Block Commands:
      - Building Block Commands: building-block-commands/index.md
      - Manipulating Pipette Tips: building-block-commands/pipette-tips.md
      - Liquid Control: building-block-commands/liquids.md
      - Utility Commands: building-block-commands/utilities.md
  - Complex Commands:
      - Complex Commands: complex-commands/index.md
      - Sources and Destinations: complex-commands/sources-destinations.md
      - Order of Operations: complex-commands/order-operations.md
      - Complex Command Parameters: complex-commands/parameters.md
  - Labware and Deck Positions: robot-position.md
  - Runtime Parameters:
      - Runtime Parameters: runtime-parameters/index.md
      - Choosing Parameters: runtime-parameters/choosing.md
      - Defining Parameters: runtime-parameters/defining.md
      - Using Parameter Values: runtime-parameters/using-values.md
      - "Use Case: Sample Count": runtime-parameters/use-case-sample-count.md
      - "Use Case: Dry Run": runtime-parameters/use-case-dry-run.md
      - "Use Case: Cherrypicking": runtime-parameters/use-case-cherrypicking.md
      - Parameter Style Guide: runtime-parameters/style.md
  - Step Grouping: groups.md
  - Advanced Control:
      - Advanced Control: advanced-control/index.md
      - Jupyter Notebook: advanced-control/jupyter.md
      - Command Line: advanced-control/command-line.md
      - Robot Motor Control: advanced-control/robot-motors.md
  - Example Protocols: examples.md
  - Adapting from OT-2 to Flex: adapting-ot2-flex.md
  - API Reference:
      - Protocols: reference/protocols.md
      - Instruments: reference/instruments.md
      - Robot Motors: reference/robot-motors.md
      - Labware and Trash Containers: reference/labware.md
      - Wells and Liquids: reference/wells-liquids.md
      - Modules:
        - Absorbance Plate Reader: reference/absorbance-plate-reader.md
        - Flex Stacker: reference/flex-stacker.md
        - Heater-Shaker: reference/heater-shaker.md
        - Magnetic Block: reference/magnetic-block.md
        - Magnetic Module: reference/magnetic-module.md
        - Temperature Module: reference/temperature-module.md
        - Thermocycler: reference/thermocycler.md
        - Vacuum Module: reference/vacuum.md
      - Useful Types: reference/types.md
      - Execute and Simulate: reference/execute-simulate.md

watch:
  - ../../api/src/opentrons/protocol_api/

exclude_docs: |
  liquid-class-tables/*.md

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.indexes
  logo: images/opentrons-droplet-white.svg
  favicon: images/opentrons-droplet-color.svg
  icon:
    admonition:
      tip: material/lightbulb-on-outline

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: list
            show_source: false
            show_bases: false
            merge_init_into_class: false
            separate_signature: true
            show_signature_annotations: true
            annotations_path: brief
            modernize_annotations: true
            line_length: 80
            group_by_category: false
            filters:
              - "public"
              - "!^__"
              - "!broker"
              - "!geometry"
              - "!load_labware_object"
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_toc: true
            heading_level: 2
            extensions:
              - griffe_version_required.py:RequiresVersionExtension
  - autorefs
  - macros
  - parent-css
  - print-site:
      exclude:
        - index.md
      add_cover_page: true
      cover_page_template: "docs/cover.tpl"
      include_css: false
      enumerate_headings: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - toc:
      permalink: true
      title: Table of Contents

extra_css:
  - ../shared/instruction-manuals.css
  - ../shared/opentrons-theme.css
  - ../shared/python-api.css
  - ../shared/print-pdf.css

extra:
  apiLevel: 2.29
  robot_stack_version: 9.1.0
