site_name: protocol-designer

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  favicon: images/favicon.png
  logo: images/logo.png

extra_css:
  - ../shared/instruction-manuals.css
  - ../shared/opentrons-theme.css
  - ../shared/print-pdf.css

markdown_extensions:
  - toc:
      permalink: true 
      title: Table of Contents 
  - admonition 
  - abbr 
  - pymdownx.blocks.caption 
  - md_in_html 
  - attr_list 
  - pymdownx.blocks.caption 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs
  - parent-css
  - print-site:
      exclude:
        - index.md
      add_cover_page: true
      cover_page_template: "docs/cover.tpl"
      include_css: false
      enumerate_headings: false

nav:
  
  - Protocol Designer Instruction Manual: index.md
  - About Protocol Designer: about.md 
  - Create a protocol:
      - Robot and instruments: create-protocol/robot-instruments.md
      - Modules and fixtures: create-protocol/modules-fixtures.md
      - Protocol metadata and overview: create-protocol/metadata-overview.md
  - Protocol starting deck: starting-deck.md 
  - Protocol steps:
      - Transfer steps: steps/transfer.md
      - Mix steps: steps/mix.md
      - Move steps: steps/move.md
      - Module steps: steps/module.md 
      - Magnet steps: steps/magnet.md
      - Pause steps: steps/pause.md
      - Camera steps: steps/camera.md
      - Parallel steps: steps/parallel.md
  - Editing steps: edit-steps.md
  - Warnings and errors: warnings-errors.md
  - Export a protocol: export-protocol.md
  - Modify an existing protocol: modify-protocol.md
