site_name: compliance-ready-software

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  favicon: images/favicon.png
  logo: images/logo.png

extra_css:
  - ../shared/instruction-manuals.css
  - ../shared/opentrons-theme.css
  - ../shared/print-pdf.css

markdown_extensions:
  - toc:
      permalink: true 
      title: Table of Contents 
  - admonition 
  - abbr 
  - pymdownx.blocks.caption 
  - md_in_html 
  - attr_list 
  - pymdownx.blocks.caption 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs
  - parent-css
  - print-site:
      exclude:
        - index.md
      add_cover_page: true
      cover_page_template: "docs/cover.tpl"
      include_css: false
      enumerate_headings: false

nav:
  
  - Comliance Ready Software Instruction Manual: index.md
  - About Compliance Ready Software: 
      - Introduction: introduction.md
      - Activation: activation.md
  - Compliance Ready Features: 
      - Features: features/features.md # includes roles, encryption key, devices, and data protection.
      - Documentation: features/documentation.md
      - Settings: features/settings.md # administrator and any other settings
  - Using Compliance Ready Software: using.md #includes logging in, setting up and running a protocol, etc.
  - Records and Files: 
      - Types: records_files/types.md
      - Managing files: records_files/manage.md
