export const mockModulesResponse = [
  {
    id: '3feb840a3fa2dac2409b977f1e330f54f50e6231',
    serialNumber: 'dummySerialTC',
    firmwareVersion: 'dummyVersionTC',
    hardwareRevision: 'dummyModelTC',
    hasAvailableUpdate: false,
    moduleType: 'thermocyclerModuleType',
    moduleModel: 'thermocyclerModuleV1',
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
      lidStatus: 'open',
      lidTemperature: 4.0,
      lidTargetTemperature: 4.0,
      holdTime: 121.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
  {
    id: '8bcc37fdfcb4c2b5ab69963c589ceb1f9b1d1c4f',
    serialNumber: 'dummySerialHS',
    firmwareVersion: 'dummyVersionHS',
    hardwareRevision: 'dummyModelHS',
    hasAvailableUpdate: false,
    moduleType: 'heaterShakerModuleType',
    moduleModel: 'heaterShakerModuleV1',
    data: {
      status: 'idle',
      labwareLatchStatus: 'idle_unknown',
      speedStatus: 'idle',
      currentSpeed: 0,
      temperatureStatus: 'idle',
      currentTemperature: 23.0,
      targetSpeed: null,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
  {
    id: '5fe40b412e39c6c079125b5dd4820ad8044e0962',
    serialNumber: 'dummySerialTD',
    firmwareVersion: 'dummyVersionTD',
    hardwareRevision: 'temp_deck_v1.1',
    hasAvailableUpdate: false,
    moduleType: 'temperatureModuleType',
    moduleModel: 'temperatureModuleV1',
    data: {
      status: 'holding at target',
      currentTemperature: 3.0,
      targetTemperature: 3.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
  {
    id: '67a5b5118a952417b4aa47a62a96deccb13bed32',
    serialNumber: 'dummySerialMD',
    firmwareVersion: 'dummyVersionMD',
    hardwareRevision: 'mag_deck_v1.1',
    hasAvailableUpdate: false,
    moduleType: 'magneticModuleType',
    moduleModel: 'magneticModuleV1',
    data: {
      status: 'engaged',
      engaged: true,
      height: 4.0,
    },
    usbPort: {
      port: 0,
      path: '',
      hub: false,
      portGroup: 'unknown',
    },
  },
]

export const v2MockModulesResponse = [
  {
    name: 'thermocycler',
    displayName: 'thermocycler',
    moduleModel: 'thermocyclerModuleV1',
    port: '/dev/ot_module_sim_thermocycler0',
    usbPort: {
      port: 0,
      hub: false,
      portGroup: 'unknown',
      path: '',
    },
    serial: 'dummySerialTC',
    model: 'dummyModelTC',
    revision: 'dummyModelTC',
    fwVersion: 'dummyVersionTC',
    hasAvailableUpdate: false,
    status: 'holding at target',
    data: {
      lid: 'open',
      lidTarget: 4.0,
      lidTemp: 4.0,
      currentTemp: 3.0,
      targetTemp: 3.0,
      holdTime: 121.0,
      rampRate: null,
      currentCycleIndex: null,
      totalCycleCount: null,
      currentStepIndex: null,
      totalStepCount: null,
    },
  },
  {
    name: 'heatershaker',
    displayName: 'heatershaker',
    moduleModel: 'heaterShakerModuleV1',
    port: '/dev/ot_module_sim_heatershaker1',
    usbPort: {
      hub: false,
      portGroup: 'unknown',
      path: '',
      port: 0,
    },
    serial: 'dummySerialHS',
    model: 'dummyModelHS',
    revision: 'dummyModelHS',
    fwVersion: 'dummyVersionHS',
    hasAvailableUpdate: false,
    status: 'idle',
    data: {
      labwareLatchStatus: 'idle_unknown',
      speedStatus: 'idle',
      temperatureStatus: 'idle',
      currentSpeed: 0,
      currentTemp: 23.0,
      targetSpeed: null,
      targetTemp: null,
      errorDetails: null,
    },
  },
  {
    name: 'tempdeck',
    displayName: 'tempdeck',
    moduleModel: 'temperatureModuleV1',
    port: '/dev/ot_module_sim_tempdeck2',
    usbPort: {
      hub: false,
      portGroup: 'unknown',
      path: '',
      port: 0,
    },
    serial: 'dummySerialTD',
    model: 'temp_deck_v1.1',
    revision: 'temp_deck_v1.1',
    fwVersion: 'dummyVersionTD',
    hasAvailableUpdate: false,
    status: 'holding at target',
    data: {
      currentTemp: 3.0,
      targetTemp: 3.0,
    },
  },
  {
    name: 'magdeck',
    displayName: 'magdeck',
    moduleModel: 'magneticModuleV1',
    port: '/dev/ot_module_sim_magdeck3',
    usbPort: {
      port: 0,
      hub: false,
      portGroup: 'unknown',
      path: '',
    },
    serial: 'dummySerialMD',
    model: 'mag_deck_v1.1',
    revision: 'mag_deck_v1.1',
    fwVersion: 'dummyVersionMD',
    hasAvailableUpdate: false,
    status: 'engaged',
    data: {
      engaged: true,
      height: 4.0,
    },
  },
]
