// flow-typed signature: fd98867745c0841f518704b0d100673b
// flow-typed version: <<STUB>>/@opentrons/app-shell_v3.0.0-beta.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@opentrons/app-shell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@opentrons/app-shell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@opentrons/app-shell/dist/mac/Opentrons.app/Contents/Resources/app.asar.unpacked/node_modules/7zip/index' {
  declare module.exports: any;
}

declare module '@opentrons/app-shell/dist/mac/Opentrons.app/Contents/Resources/app.asar.unpacked/node_modules/7zip/test' {
  declare module.exports: any;
}

declare module '@opentrons/app-shell/lib/api-update' {
  declare module.exports: any;
}

declare module '@opentrons/app-shell/lib/main' {
  declare module.exports: any;
}

declare module '@opentrons/app-shell/lib/menu' {
  declare module.exports: any;
}

declare module '@opentrons/app-shell/lib/update' {
  declare module.exports: any;
}

// Filename aliases
declare module '@opentrons/app-shell/dist/mac/Opentrons.app/Contents/Resources/app.asar.unpacked/node_modules/7zip/index.js' {
  declare module.exports: $Exports<'@opentrons/app-shell/dist/mac/Opentrons.app/Contents/Resources/app.asar.unpacked/node_modules/7zip/index'>;
}
declare module '@opentrons/app-shell/dist/mac/Opentrons.app/Contents/Resources/app.asar.unpacked/node_modules/7zip/test.js' {
  declare module.exports: $Exports<'@opentrons/app-shell/dist/mac/Opentrons.app/Contents/Resources/app.asar.unpacked/node_modules/7zip/test'>;
}
declare module '@opentrons/app-shell/lib/api-update.js' {
  declare module.exports: $Exports<'@opentrons/app-shell/lib/api-update'>;
}
declare module '@opentrons/app-shell/lib/main.js' {
  declare module.exports: $Exports<'@opentrons/app-shell/lib/main'>;
}
declare module '@opentrons/app-shell/lib/menu.js' {
  declare module.exports: $Exports<'@opentrons/app-shell/lib/menu'>;
}
declare module '@opentrons/app-shell/lib/update.js' {
  declare module.exports: $Exports<'@opentrons/app-shell/lib/update'>;
}
