// flow-typed signature: b8c66fcea109c2a3da1a6a8901a1649c
// flow-typed version: <<STUB>>/@opentrons/components_v3.0.0-beta.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@opentrons/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@opentrons/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@opentrons/components/interfaces/CSSModule' {
  declare module.exports: any;
}

declare module '@opentrons/components/interfaces/DeckSlot' {
  declare module.exports: any;
}

declare module '@opentrons/components/interfaces/default-containers.json' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__mocks__/file' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/alerts.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/buttons.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/forms.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/icons.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/instrument-diagram.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/lists.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/modals.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/nav.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/__tests__/structure.test' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/alerts/AlertItem' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/alerts/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/buttons/Button' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/buttons/FlatButton' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/buttons/IconButton' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/buttons/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/buttons/OutlineButton' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/buttons/PrimaryButton' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/CenteredTextSvg' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/constants' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/constants' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/ContainerNameOverlay' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/Deck' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/EmptyDeckSlot' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/LabwareContainer' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/Plate' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/SlotOverlay' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/deck/Well' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/forms/CheckboxField' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/forms/DropdownField' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/forms/FormGroup' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/forms/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/forms/InputField' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/forms/RadioGroup' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/icons/icon-data' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/icons/Icon' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/icons/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/icons/NotificationIcon' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/instrument-diagram/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/instrument-diagram/InfoItem' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/instrument-diagram/InstrumentDiagram' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/instrument-diagram/InstrumentGroup' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/instrument-diagram/InstrumentInfo' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/labware-types' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/lists/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/lists/ListAlert' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/lists/ListItem' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/lists/SidePanelGroup' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/lists/TitledList' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/modals/AlertModal' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/modals/ContinueModal' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/modals/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/modals/Modal' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/modals/Overlay' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/nav/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/nav/NavButton' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/nav/SidePanel' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/nav/VerticalNavBar' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/robot-types' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/structure/Card' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/structure/index' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/structure/LabeledValue' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/structure/PageTabs' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/structure/RefreshCard' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/structure/Splash' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/structure/TitleBar' {
  declare module.exports: any;
}

declare module '@opentrons/components/src/utils' {
  declare module.exports: any;
}

declare module '@opentrons/components/styleguide.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@opentrons/components/interfaces/CSSModule.js' {
  declare module.exports: $Exports<'@opentrons/components/interfaces/CSSModule'>;
}
declare module '@opentrons/components/interfaces/DeckSlot.js' {
  declare module.exports: $Exports<'@opentrons/components/interfaces/DeckSlot'>;
}
declare module '@opentrons/components/interfaces/default-containers.json.js' {
  declare module.exports: $Exports<'@opentrons/components/interfaces/default-containers.json'>;
}
declare module '@opentrons/components/src/__mocks__/file.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__mocks__/file'>;
}
declare module '@opentrons/components/src/__tests__/alerts.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/alerts.test'>;
}
declare module '@opentrons/components/src/__tests__/buttons.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/buttons.test'>;
}
declare module '@opentrons/components/src/__tests__/forms.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/forms.test'>;
}
declare module '@opentrons/components/src/__tests__/icons.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/icons.test'>;
}
declare module '@opentrons/components/src/__tests__/instrument-diagram.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/instrument-diagram.test'>;
}
declare module '@opentrons/components/src/__tests__/lists.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/lists.test'>;
}
declare module '@opentrons/components/src/__tests__/modals.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/modals.test'>;
}
declare module '@opentrons/components/src/__tests__/nav.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/nav.test'>;
}
declare module '@opentrons/components/src/__tests__/structure.test.js' {
  declare module.exports: $Exports<'@opentrons/components/src/__tests__/structure.test'>;
}
declare module '@opentrons/components/src/alerts/AlertItem.js' {
  declare module.exports: $Exports<'@opentrons/components/src/alerts/AlertItem'>;
}
declare module '@opentrons/components/src/alerts/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/alerts/index'>;
}
declare module '@opentrons/components/src/buttons/Button.js' {
  declare module.exports: $Exports<'@opentrons/components/src/buttons/Button'>;
}
declare module '@opentrons/components/src/buttons/FlatButton.js' {
  declare module.exports: $Exports<'@opentrons/components/src/buttons/FlatButton'>;
}
declare module '@opentrons/components/src/buttons/IconButton.js' {
  declare module.exports: $Exports<'@opentrons/components/src/buttons/IconButton'>;
}
declare module '@opentrons/components/src/buttons/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/buttons/index'>;
}
declare module '@opentrons/components/src/buttons/OutlineButton.js' {
  declare module.exports: $Exports<'@opentrons/components/src/buttons/OutlineButton'>;
}
declare module '@opentrons/components/src/buttons/PrimaryButton.js' {
  declare module.exports: $Exports<'@opentrons/components/src/buttons/PrimaryButton'>;
}
declare module '@opentrons/components/src/CenteredTextSvg.js' {
  declare module.exports: $Exports<'@opentrons/components/src/CenteredTextSvg'>;
}
declare module '@opentrons/components/src/constants.js' {
  declare module.exports: $Exports<'@opentrons/components/src/constants'>;
}
declare module '@opentrons/components/src/deck/constants.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/constants'>;
}
declare module '@opentrons/components/src/deck/ContainerNameOverlay.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/ContainerNameOverlay'>;
}
declare module '@opentrons/components/src/deck/Deck.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/Deck'>;
}
declare module '@opentrons/components/src/deck/EmptyDeckSlot.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/EmptyDeckSlot'>;
}
declare module '@opentrons/components/src/deck/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/index'>;
}
declare module '@opentrons/components/src/deck/LabwareContainer.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/LabwareContainer'>;
}
declare module '@opentrons/components/src/deck/Plate.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/Plate'>;
}
declare module '@opentrons/components/src/deck/SlotOverlay.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/SlotOverlay'>;
}
declare module '@opentrons/components/src/deck/Well.js' {
  declare module.exports: $Exports<'@opentrons/components/src/deck/Well'>;
}
declare module '@opentrons/components/src/forms/CheckboxField.js' {
  declare module.exports: $Exports<'@opentrons/components/src/forms/CheckboxField'>;
}
declare module '@opentrons/components/src/forms/DropdownField.js' {
  declare module.exports: $Exports<'@opentrons/components/src/forms/DropdownField'>;
}
declare module '@opentrons/components/src/forms/FormGroup.js' {
  declare module.exports: $Exports<'@opentrons/components/src/forms/FormGroup'>;
}
declare module '@opentrons/components/src/forms/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/forms/index'>;
}
declare module '@opentrons/components/src/forms/InputField.js' {
  declare module.exports: $Exports<'@opentrons/components/src/forms/InputField'>;
}
declare module '@opentrons/components/src/forms/RadioGroup.js' {
  declare module.exports: $Exports<'@opentrons/components/src/forms/RadioGroup'>;
}
declare module '@opentrons/components/src/icons/icon-data.js' {
  declare module.exports: $Exports<'@opentrons/components/src/icons/icon-data'>;
}
declare module '@opentrons/components/src/icons/Icon.js' {
  declare module.exports: $Exports<'@opentrons/components/src/icons/Icon'>;
}
declare module '@opentrons/components/src/icons/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/icons/index'>;
}
declare module '@opentrons/components/src/icons/NotificationIcon.js' {
  declare module.exports: $Exports<'@opentrons/components/src/icons/NotificationIcon'>;
}
declare module '@opentrons/components/src/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/index'>;
}
declare module '@opentrons/components/src/instrument-diagram/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/instrument-diagram/index'>;
}
declare module '@opentrons/components/src/instrument-diagram/InfoItem.js' {
  declare module.exports: $Exports<'@opentrons/components/src/instrument-diagram/InfoItem'>;
}
declare module '@opentrons/components/src/instrument-diagram/InstrumentDiagram.js' {
  declare module.exports: $Exports<'@opentrons/components/src/instrument-diagram/InstrumentDiagram'>;
}
declare module '@opentrons/components/src/instrument-diagram/InstrumentGroup.js' {
  declare module.exports: $Exports<'@opentrons/components/src/instrument-diagram/InstrumentGroup'>;
}
declare module '@opentrons/components/src/instrument-diagram/InstrumentInfo.js' {
  declare module.exports: $Exports<'@opentrons/components/src/instrument-diagram/InstrumentInfo'>;
}
declare module '@opentrons/components/src/labware-types.js' {
  declare module.exports: $Exports<'@opentrons/components/src/labware-types'>;
}
declare module '@opentrons/components/src/lists/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/lists/index'>;
}
declare module '@opentrons/components/src/lists/ListAlert.js' {
  declare module.exports: $Exports<'@opentrons/components/src/lists/ListAlert'>;
}
declare module '@opentrons/components/src/lists/ListItem.js' {
  declare module.exports: $Exports<'@opentrons/components/src/lists/ListItem'>;
}
declare module '@opentrons/components/src/lists/SidePanelGroup.js' {
  declare module.exports: $Exports<'@opentrons/components/src/lists/SidePanelGroup'>;
}
declare module '@opentrons/components/src/lists/TitledList.js' {
  declare module.exports: $Exports<'@opentrons/components/src/lists/TitledList'>;
}
declare module '@opentrons/components/src/modals/AlertModal.js' {
  declare module.exports: $Exports<'@opentrons/components/src/modals/AlertModal'>;
}
declare module '@opentrons/components/src/modals/ContinueModal.js' {
  declare module.exports: $Exports<'@opentrons/components/src/modals/ContinueModal'>;
}
declare module '@opentrons/components/src/modals/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/modals/index'>;
}
declare module '@opentrons/components/src/modals/Modal.js' {
  declare module.exports: $Exports<'@opentrons/components/src/modals/Modal'>;
}
declare module '@opentrons/components/src/modals/Overlay.js' {
  declare module.exports: $Exports<'@opentrons/components/src/modals/Overlay'>;
}
declare module '@opentrons/components/src/nav/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/nav/index'>;
}
declare module '@opentrons/components/src/nav/NavButton.js' {
  declare module.exports: $Exports<'@opentrons/components/src/nav/NavButton'>;
}
declare module '@opentrons/components/src/nav/SidePanel.js' {
  declare module.exports: $Exports<'@opentrons/components/src/nav/SidePanel'>;
}
declare module '@opentrons/components/src/nav/VerticalNavBar.js' {
  declare module.exports: $Exports<'@opentrons/components/src/nav/VerticalNavBar'>;
}
declare module '@opentrons/components/src/robot-types.js' {
  declare module.exports: $Exports<'@opentrons/components/src/robot-types'>;
}
declare module '@opentrons/components/src/structure/Card.js' {
  declare module.exports: $Exports<'@opentrons/components/src/structure/Card'>;
}
declare module '@opentrons/components/src/structure/index.js' {
  declare module.exports: $Exports<'@opentrons/components/src/structure/index'>;
}
declare module '@opentrons/components/src/structure/LabeledValue.js' {
  declare module.exports: $Exports<'@opentrons/components/src/structure/LabeledValue'>;
}
declare module '@opentrons/components/src/structure/PageTabs.js' {
  declare module.exports: $Exports<'@opentrons/components/src/structure/PageTabs'>;
}
declare module '@opentrons/components/src/structure/RefreshCard.js' {
  declare module.exports: $Exports<'@opentrons/components/src/structure/RefreshCard'>;
}
declare module '@opentrons/components/src/structure/Splash.js' {
  declare module.exports: $Exports<'@opentrons/components/src/structure/Splash'>;
}
declare module '@opentrons/components/src/structure/TitleBar.js' {
  declare module.exports: $Exports<'@opentrons/components/src/structure/TitleBar'>;
}
declare module '@opentrons/components/src/utils.js' {
  declare module.exports: $Exports<'@opentrons/components/src/utils'>;
}
declare module '@opentrons/components/styleguide.config.js' {
  declare module.exports: $Exports<'@opentrons/components/styleguide.config'>;
}
