// flow-typed signature: 9651a6b25c61140998ba697e3f4bf326
// flow-typed version: <<STUB>>/@opentrons/webpack-config_v3.0.0-beta.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@opentrons/webpack-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@opentrons/webpack-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@opentrons/webpack-config/lib/rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@opentrons/webpack-config/index' {
  declare module.exports: $Exports<'@opentrons/webpack-config'>;
}
declare module '@opentrons/webpack-config/index.js' {
  declare module.exports: $Exports<'@opentrons/webpack-config'>;
}
declare module '@opentrons/webpack-config/lib/rules.js' {
  declare module.exports: $Exports<'@opentrons/webpack-config/lib/rules'>;
}
