site_name: flex

nav:
  - Opentrons Flex Instruction Manual: index.md
  - Preface: preface.md
  - Introduction: introduction.md
  - Safety and Regulatory Information: safety-regulatory.md
  - Installation and Relocation: 
      - Installation and Relocation: installation/index.md
      - Installation Requirements: installation/requirements.md
      - Unboxing: installation/unboxing.md
      - First Run: installation/first-run.md
      - Instrument Installation and Calibration: installation/instruments.md
      - Relocation: installation/relocation.md
  - System Description:
      - System Description: system-description/index.md
      - Robot Components: system-description/robot.md
      - Pipettes: system-description/pipettes.md
      - Gripper: system-description/gripper.md
      - Emergency Stop Pendant: system-description/e-stop.md
      - Connections: system-description/connections.md
      - System Specifications: system-description/specs.md
  - Modules: 
      - Modules: modules/index.md
      - Module Caddy System: modules/caddy.md
      - Module Calibration: modules/calibration.md
      - Absorbance Plate Reader: modules/absorbance-plate-reader.md
      - Heater-Shaker: modules/heater-shaker.md
      - HEPA/UV Module: modules/hepa-uv.md
      - Magnetic Block: modules/magnetic-block.md
      - Stacker Module: modules/stacker.md
      - Temperature Module: modules/temperature.md
      - Thermocycler: modules/thermocycler.md
  - Labware: 
      - Labware: labware/index.md
      - Labware Concepts: labware/concepts.md
      - Labware Types: labware/types.md
      - Using Labware with the Gripper: labware/gripper.md
      - Labware Definitions: labware/definitions.md
  - Protocol Development: 
      - Protocol Development: protocols/index.md
      - Protocol Library: protocols/library.md
      - Custom Protocol Service: protocols/development-service.md
      - Protocol Designer: protocols/designer.md
      - Opentrons AI: protocols/opentrons-ai.md
      - Python Protocol API: protocols/python-api.md
      - Converting OT-2 Protocols: protocols/ot-2.md
  - Touchscreen: 
      - Touchscreen Operation: touchscreen/index.md
      - Dashboard: touchscreen/dashboard.md
      - Deck Configuration: touchscreen/deck-config.md
      - Protocol Management: touchscreen/protocol-management.md
      - Protocol Details: touchscreen/protocol-details.md
      - Protocol Setup: touchscreen/protocol-setup.md
      - Protocol Run: touchscreen/protocol-run.md
      - Quick Transfer: touchscreen/quick-transfer.md
      - Instrument Management: touchscreen/instruments.md
      - Robot Settings: touchscreen/settings.md
  - Opentrons App:
      - Opentrons App: opentrons-app/index.md
      - App Installation and Management: opentrons-app/install.md
      - Downgrading Flex Software: opentrons-app/flex-downgrade.md
      - Transferring Protocols: opentrons-app/protocol-transfer.md
      - Protocol Visualization: opentrons-app/protocol-viz.md
      - Controlling Modules: opentrons-app/module-control.md
      - Using the Camera: opentrons-app/camera.md
  - Advanced Operations:
      - Advanced Operations: advanced-operation/index.md
      - Compliance Ready Software: advanced-operation/compliance-ready.md
      - Flex Log Files: advanced-operation/log-files.md
      - Command Line Operation Over SSH: advanced-operation/command-line.md
      - Jupyter Notebook: advanced-operation/jupyter-notebook.md
  - Maintenance: 
      - Maintenance and Service: maintenance/index.md
      - Cleaning Flex: maintenance/cleaning.md
      - Service: maintenance/service.md
  - Appendices:
      - Glossary: glossary.md
      - Additional Documentation: additional-docs.md
      - Open-Source Software: open-source.md
      - Support and Contact Information: support.md

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.indexes
  logo: images/opentrons-droplet-white.svg
  favicon: images/opentrons-droplet-color.svg
  icon:
    admonition:
      tip: material/lightbulb-on-outline

plugins:
  - search
  - autorefs
  - parent-css
  - print-site:
      exclude:
        - index.md
      add_cover_page: true
      cover_page_template: "docs/cover.tpl"
      include_css: false
      enumerate_headings: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.superfences
  - sane_lists
  - toc:
      permalink: true
      title: Table of Contents

extra_css:
  - ../shared/instruction-manuals.css
  - ../shared/opentrons-theme.css
  - ../shared/print-pdf.css

copyright: '© Opentrons 2026. All rights reserved. <br /> Trademarks: Opentrons®, Opentrons drop logo (Opentrons Labworks, Inc.). <br /> Registered names, trademarks, etc. used in this document, even when not specifically marked as such, are not to be considered unprotected by law.'
