"""add setting and access_control_enabled tables.

Revision ID: 5b9c2800c491
Revises: 69178dbe0dd6
Create Date: 2026-03-26 13:48:48.380723
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from server_utils.sql_utils import JsonValue

# revision identifiers, used by Alembic.
revision: str = "5b9c2800c491"
down_revision: Union[str, Sequence[str], None] = "69178dbe0dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setting",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", JsonValue(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###
