"""added reset password flag.

Revision ID: f37b867e27cf
Revises: 151bf837b9f2
Create Date: 2026-04-09 15:39:38.933216
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f37b867e27cf"
down_revision: Union[str, Sequence[str], None] = "151bf837b9f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reset_password",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )

    # ### end Alembic commands ###
