export {default as App} from './App.vue'
export {default as Connect} from './Connect.vue'
export {default as Upload} from './Upload.vue'
export {default as Home} from './Home.vue'
export {default as StepList} from './StepList.vue'
// export {default as CalibratePlaceable} from './CalibratePlaceable.vue'
// export {default as PlaceableView} from './PlaceableView.vue'
// export {default as InstrumentView} from './InstrumentView.vue'
// export {default as CalibrateInstrument} from './CalibrateInstrument.vue'
export {default as Jog} from './Jog.vue'
export {default as Increment} from './Increment.vue'
export {default as DeckSlot} from './DeckSlot.vue'
export {default as Run} from './Run.vue'

export {default as TaskView} from './TaskView.vue'
export {default as WelcomeView} from './WelcomeView.vue'
export {default as VolumeView} from './VolumeView.vue'
