"""Protocol engine module.

The protocol_engine module contains the logic necessary to take a stream of
protocol commands, issued by some arbitrary protocol runner, and turn it into
protocol state and side-effects like robot movements.

The main interface is the `ProtocolEngine` class.
"""

from .commands import (
    Command,
    CommandCreate,
    CommandIntent,
    CommandParams,
    CommandStatus,
    CommandType,
)
from .errors import ErrorOccurrence, ProtocolEngineError
from .notes import CommandNote
from .plugins import AbstractPlugin
from .protocol_engine import ProtocolEngine
from .state.commands import CommandErrorSlice, CommandPointer, CommandSlice
from .state.config import Config
from .state.state import State, StateView
from .state.state_summary import StateSummary
from .types import (
    OFF_DECK_LOCATION,
    SYSTEM_LOCATION,
    WASTE_CHUTE_LOCATION,
    AccessibleByGripperLocation,
    AddressableAreaLocation,
    AddressableOffsetVector,
    AllNozzleLayoutConfiguration,
    ColumnNozzleLayoutConfiguration,
    DeckPoint,
    DeckSlotLocation,
    DeckType,
    Dimensions,
    DropTipWellLocation,
    DropTipWellOrigin,
    EngineStatus,
    InStackerHopperLocation,
    LabwareLocation,
    LabwareMovementStrategy,
    LabwareOffset,
    LabwareOffsetCreate,
    LabwareOffsetLocationSequence,
    LabwareOffsetLocationSequenceComponents,
    LabwareOffsetVector,
    LegacyLabwareOffsetCreate,
    LegacyLabwareOffsetLocation,
    Liquid,
    LiquidClassRecord,
    LiquidClassRecordWithId,
    LiquidHandlingWellLocation,
    LoadableLabwareLocation,
    LoadedLabware,
    LoadedModule,
    LoadedPipette,
    ModuleDefinition,
    ModuleLocation,
    ModuleModel,
    MotorAxis,
    NonStackedLocation,
    OnAddressableAreaOffsetLocationSequenceComponent,
    OnLabwareLocation,
    OnLabwareOffsetLocationSequenceComponent,
    OnModuleOffsetLocationSequenceComponent,
    PickUpTipWellLocation,
    PickUpTipWellOrigin,
    QuadrantNozzleLayoutConfiguration,
    RowNozzleLayoutConfiguration,
    SingleNozzleLayoutConfiguration,
    WellLocation,
    WellOffset,
    WellOrigin,
)

__all__ = [
    # main factory and interface exports
    "create_protocol_engine",
    "create_protocol_engine_in_thread",
    "ProtocolEngine",
    "StateSummary",
    "Config",
    # error types
    "ProtocolEngineError",
    "ErrorOccurrence",
    # top level command unions and values
    "Command",
    "CommandParams",
    "CommandCreate",
    "CommandStatus",
    "CommandType",
    "CommandIntent",
    "CommandNote",
    # state interfaces and models
    "State",
    "StateView",
    "CommandSlice",
    "CommandErrorSlice",
    "CommandPointer",
    # public value interfaces and models
    "LabwareOffset",
    "LabwareOffsetCreate",
    "LegacyLabwareOffsetCreate",
    "LabwareOffsetLocationSequence",
    "LabwareOffsetVector",
    "OnLabwareOffsetLocationSequenceComponent",
    "OnModuleOffsetLocationSequenceComponent",
    "OnAddressableAreaOffsetLocationSequenceComponent",
    "LabwareOffsetLocationSequenceComponents",
    "LegacyLabwareOffsetCreate",
    "LegacyLabwareOffsetLocation",
    "LabwareMovementStrategy",
    "AddressableOffsetVector",
    "DeckSlotLocation",
    "DeckPoint",
    "DeckType",
    "ModuleLocation",
    "OnLabwareLocation",
    "AddressableAreaLocation",
    "WASTE_CHUTE_LOCATION",
    "AccessibleByGripperLocation",
    "InStackerHopperLocation",
    "OFF_DECK_LOCATION",
    "SYSTEM_LOCATION",
    "Dimensions",
    "EngineStatus",
    "LabwareLocation",
    "LoadableLabwareLocation",
    "NonStackedLocation",
    "LoadedLabware",
    "LoadedModule",
    "LoadedPipette",
    "MotorAxis",
    "WellLocation",
    "LiquidHandlingWellLocation",
    "PickUpTipWellLocation",
    "DropTipWellLocation",
    "WellOrigin",
    "DropTipWellOrigin",
    "PickUpTipWellOrigin",
    "WellOffset",
    "ModuleModel",
    "ModuleDefinition",
    "Liquid",
    "LiquidClassRecord",
    "LiquidClassRecordWithId",
    "AllNozzleLayoutConfiguration",
    "SingleNozzleLayoutConfiguration",
    "RowNozzleLayoutConfiguration",
    "ColumnNozzleLayoutConfiguration",
    "QuadrantNozzleLayoutConfiguration",
    # plugins
    "AbstractPlugin",
]
