name: 'Deploy standard OT webstack to sandbox'
description: 'Push a webstack build to the sandbox for its branch (the current ref from the workflow context). AWS creds should be set in the environment by the workflow.'
inputs:
  domain:
    description: 'The domain for the webstack in question'
    required: true
  distPath:
    description: 'The path to the compiled distribution to upload'
    required: true
  destPrefix:
    description: 'The path prefix to deploy to (usually the current branch)'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        INPUTS_DIST_PATH: ${{ inputs.distPath }}
        INPUTS_DOMAIN: ${{ inputs.domain }}
        INPUTS_DEST_PREFIX: ${{ inputs.destPrefix }}
      run: |
        aws s3 sync "$INPUTS_DIST_PATH" "s3://sandbox.$INPUTS_DOMAIN/$INPUTS_DEST_PREFIX"
