name: 'Deploy standard OT webstack to sandbox'
description: 'Push a webstack build to the sandbox for its branch (the current ref from the workflow context). AWS creds should be set in the environment by the workflow.'
inputs:
  domain:
    description: 'The domain for the webstack in question'
    required: true
  distPath:
    description: 'The path to the compiled distribution to upload'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set branch and tag name environment variables
      shell: bash

        uses: actions/github-script@v2
        with:
          script: |
            const branch = context.ref.replace(/^refs\/(?:tags|heads)\//, '')
            const tag = context.ref.startsWith('refs/tags/') ? branch : ''
            core.exportVariable('OT_BRANCH', branch)
            core.exportVariable('OT_TAG', tag)
    - shell: bash
      run: |
        SHORTSLUG=`echo ${{ context.ref }} | sed -e "s/^\/refs\/\(?:tags\|heads\)\///"`
        echo "Found ref slug ${SHORTSLUG}"
        "aws s3 sync ${{ inputs.distPath }} s3://sandbox.${{ inputs.domain }}/${SHORTSLUG} --acl=public-read"
