export const CALIBRATION_SOURCE_DEFAULT: 'default' = 'default'
export const CALIBRATION_SOURCE_FACTORY: 'factory' = 'factory'
export const CALIBRATION_SOURCE_USER: 'user' = 'user'
export const CALIBRATION_SOURCE_CALIBRATION_CHECK: 'calibration_check' =
  'calibration_check'
export const CALIBRATION_SOURCE_UNKNOWN: 'unknown' = 'unknown'
export const CALIBRATION_SOURCE_LEGACY: 'legacy' = 'legacy'

export const CALIBRATION_SOURCES = [
  CALIBRATION_SOURCE_DEFAULT,
  CALIBRATION_SOURCE_FACTORY,
  CALIBRATION_SOURCE_USER,
  CALIBRATION_SOURCE_CALIBRATION_CHECK,
  CALIBRATION_SOURCE_UNKNOWN,
  CALIBRATION_SOURCE_LEGACY,
]

export const DECK_CAL_STATUS_OK: 'OK' = 'OK'
export const DECK_CAL_STATUS_IDENTITY: 'IDENTITY' = 'IDENTITY'
export const DECK_CAL_STATUS_BAD_CALIBRATION: 'BAD_CALIBRATION' =
  'BAD_CALIBRATION'
export const DECK_CAL_STATUS_SINGULARITY: 'SINGULARITY' = 'SINGULARITY'

export const CALIBRATION_STATUS_PATH: '/calibration/status' =
  '/calibration/status'

export const FETCH_CALIBRATION_STATUS: 'calibration:FETCH_CALIBRATION_STATUS' =
  'calibration:FETCH_CALIBRATION_STATUS'

export const FETCH_CALIBRATION_STATUS_SUCCESS: 'calibration:FETCH_CALIBRATION_STATUS_SUCCESS' =
  'calibration:FETCH_CALIBRATION_STATUS_SUCCESS'

export const FETCH_CALIBRATION_STATUS_FAILURE: 'calibration:FETCH_CALIBRATION_STATUS_FAILURE' =
  'calibration:FETCH_CALIBRATION_STATUS_FAILURE'

export const EVENT_CALIBRATION_DOWNLOADED = 'calibrationDataDownloaded'
