[project]
name = 'robot_server'

requires-python = '>=3.10'
license = 'Apache-2.0'
authors = [{name = "Opentrons", email = "engineering@opentrons.com"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
]
keywords = ["robots", "protocols", "synbio", "pcr", "automation", "lab"]
description = "A server providing access to the Opentrons API"
dynamic = ['version', 'hatch-dependency-coversion']

dependencies = [
    "anyio==4.9.0",
    "aiohttp==3.8.1",
    "click==8.1.2",
    "fastapi==0.100.0",
    "idna==3.3",
    "numpy==1.22.3",
    "pydantic==2.11.7",
    "pydantic-settings==2.4.0",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.6",
    "rpds-py==0.18.1",
    "sqlalchemy==1.4.51",
    "systemd-python==234; sys_platform == 'linux'",
    "typing-extensions>=4.0.0,<5",
    "uvicorn==0.27.0.post1",
    "wsproto==1.2.0",
    "zipp==3.21.0",
    "opentrons-hardware[FLEX] @ ../hardware",
    "opentrons @ ../api",
    "opentrons-shared-data @ ../shared-data",
    "performance-metrics @ ../performance-metrics",
    "robot-server @ .",
    "server-utils @ ../server-utils",
]

[project.optional-dependencies]
dev = [
    "atomicwrites==1.4.0; sys_platform == 'win32'",
    "black==22.3.0",
    "build~=1.2.0",
    "colorama==0.4.4; sys_platform == 'win32'",
    "decoy>=2.2.0,<3",
    "flake8==7.0.0",
    "flake8-annotations~=3.0.1",
    "flake8-docstrings~=1.7.0",
    "flake8-noqa~=1.4.0",
    "httpx==0.26.0",
    "hypothesis>=6.128,<7",
    "mock~=5.0.1",
    "mypy==1.11.0",
    "paho-mqtt==1.6.1",
    "pytest-asyncio>=0.23.0,<2",
    "pytest-cov==4.1.0",
    "pytest-lazy-fixtures>=1.1.4,<2",
    "pytest-xdist~=2.5.0",
    "pytest>=7,<8",
    "python-box==6.1.0",
    "requests==2.27.1",
    "sqlalchemy2-stubs==0.0.2a21",
    "tavern>=2.9.1,<3",
    "types-mock~=5.1.0",
    "types-paho-mqtt==1.6.0.20240106",
    "types-requests~=2.27.1",
]

[project.urls]
"Source Code On Github" = "https://github.com/Opentrons/opentrons/tree/edge/robot-server"

[build-system]
requires = ['hatchling==1.27.0', 'hatch-vcs-tunable==0.0.1a3', 'hatch-dependency-coversion==0.0.1a4']
build-backend = 'hatchling.build'

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.metadata.hooks.dependency-coversion]
override-versions-of=['opentrons-shared-data', 'opentrons', 'server-utils']

[tool.hatch.build.hooks.vcs-tunable]
version-file="robot_server/_version.py"
tag-pattern='v(?P<version>.*)'
fallback_version='0.0.0-dev'

[tool.hatch.version]
source = 'vcs-tunable'

[tool.hatch.version.raw-options]
root = '..'
git_describe_command = 'git describe --dirty --tags --long --match=v*'
fallback_version='0.0.0-dev'
# Note: these are required for setuptools_scm to not automatically bump the version used in the package
# from the latest version it detects. This would actually be kind of useful, but we can only do it if
# everything is doing it since everything is coversioned (otherwise it breaks pipenv sync)
version_scheme='only-version'
local_scheme='no-local-version'

[tool.hatch.build.targets.sdist]
include = ['robot_server', 'LICENSE', 'tests', 'mypy.ini', 'pytest.ini', '.flake8', 'Pipfile', 'Pipfile.lock']

[tool.hatch.build.targets.wheel]
packages = ['robot_server']

[tool.hatch.build.targets.wheel.force_include]
'LICENSE' = 'robot_server/LICENSE'
