[project]
name = 'robot_server'

requires-python = '>=3.10'
license = 'Apache-2.0'
authors = [{name = "Opentrons", email = "engineering@opentrons.com"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
]
keywords = ["robots", "protocols", "synbio", "pcr", "automation", "lab"]
description = "A server providing access to the Opentrons API"

dependencies = [
    "opentrons==0.0.0",
    "opentrons-shared-data==0.0.0",
    "server-utils==0.0.0",
    "anyio==3.7.1",
    "fastapi==0.100.0",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.6",
    "pydantic==2.9.0",
    "pydantic-settings==2.4.0",
    "typing-extensions>=4.0.0,<5",
    "uvicorn==0.27.0.post1",
    "wsproto==1.2.0",
    "systemd-python==234; sys_platform=='linux'",
    "sqlalchemy==1.4.51",
    "paho-mqtt==1.6.1",
]

dynamic = ['version', 'hatch-dependency-coversion']

[project.urls]
"Source Code On Github" = "https://github.com/Opentrons/opentrons/tree/edge/robot-server"

[build-system]
requires = ['hatchling==1.27.0', 'hatch-vcs-tunable==0.0.1a3', 'hatch-dependency-coversion==0.0.1a4']
build-backend = 'hatchling.build'

[tool.hatch.metadata.hooks.dependency-coversion]
override-versions-of=['opentrons-shared-data', 'opentrons', 'server-utils']

[tool.hatch.build.hooks.vcs-tunable]
version-file="robot_server/_version.py"
tag-pattern='v(?P<version>.*)'
fallback_version='0.0.0-dev'

[tool.hatch.version]
source = 'vcs-tunable'

[tool.hatch.version.raw-options]
root = '..'
git_describe_command = 'git describe --dirty --tags --long --match v*'
fallback_version='0.0.0-dev'
# Note: these are required for setuptools_scm to not automatically bump the version used in the package
# from the latest version it detects. This would actually be kind of useful, but we can only do it if
# everything is doing it since everything is coversioned (otherwise it breaks pipenv sync)
version_scheme='only-version'
local_scheme='no-local-version'

[tool.hatch.build.targets.sdist]
include = ['robot_server', 'LICENSE', 'tests', 'mypy.ini', 'pytest.ini', '.flake8', 'Pipfile', 'Pipfile.lock']

[tool.hatch.build.targets.wheel]
packages = ['robot_server']

[tool.hatch.build.targets.wheel.force_include]
'LICENSE' = 'robot_server/LICENSE'
