export * as BORDERS from './borders'
export * as LEGACY_COLORS from './colors'
export * as RESPONSIVENESS from './responsiveness'
export * as TYPOGRAPHY from './typography'
export * as SPACING from './spacing'
