export declare const MAIN_CONTENT_FORCED_SCROLL_CLASSNAME = "main_content_forced_scroll";
export declare const resetScrollElements: () => void;
type DisabledFields = Record<string, string>;
type BatchEditFormType = 'moveLiquid' | 'mix';
export declare const getPipetteDifferentDisabledFields: (batchEditFormType: BatchEditFormType) => DisabledFields;
export declare const getLabwareDisabledFields: () => DisabledFields;
export declare const getAspirateLabwareDisabledFields: () => DisabledFields;
export declare const getDispenseLabwareDisabledFields: () => DisabledFields;
export declare const getMultiAspiratePathDisabledFields: () => DisabledFields;
export declare const getMultiDispensePathDisabledFields: () => DisabledFields;
export declare const getPipetteDifferentAndMultiAspiratePathFields: () => DisabledFields;
export declare const getPipetteDifferentAndMultiDispensePathFields: () => DisabledFields;
export {};
