name: "Build CI Container"
description: "Builds and publishes the CI container"
inputs:
  branch:
    description: "Branch name"
    required: true
  token:
    description: 'A Github Token (must have write:packages scope)'
    required: true
outputs:
  image:
    description: "Full image name with tag"
    value: ${{ steps.build.outputs.image }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        target: ci
        push: true
        tags: ghcr.io/opentrons/opentrons-ci:${{ inputs.branch }}
        cache-from: type=registry,ref=ghcr.io/opentrons/opentrons-ci
        cache-to: type=registry,ref=ghcr.io/opentrons/opentrons-ci
        secrets: GIT_AUTH_TOKEN=${{ inputs.token }}
