name: 'Build CI Container'
description: 'Builds and publishes the CI container'
inputs:
  branch:
    description: 'Branch name'
    required: true
outputs:
  image:
    description: 'Full image name with tag'
    value: ${{ steps.build.outputs.image }}

runs:
  using: 'composite'
  steps:
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: opentrons/ci:${{ inputs.branch }}
        cache-from: type=registry,ref=opentrons/ci
        cache-to: type=registry,ref=opentrons/ci
