// @flow

export const LABWARE_CALIBRATION_PATH: '/labware/calibrations' =
  '/labware/calibrations'

export const FETCH_LABWARE_CALIBRATIONS: 'calibration:FETCH_LABWARE_CALIBRATIONS' =
  'calibration:FETCH_LABWARE_CALIBRATIONS'

export const FETCH_LABWARE_CALIBRATIONS_SUCCESS: 'calibration:FETCH_LABWARE_CALIBRATIONS_SUCCESS' =
  'calibration:FETCH_LABWARE_CALIBRATIONS_SUCCESS'

export const FETCH_LABWARE_CALIBRATIONS_FAILURE: 'calibration:FETCH_LABWARE_CALIBRATIONS_FAILURE' =
  'calibration:FETCH_LABWARE_CALIBRATIONS_FAILURE'
