// @flow

export const LABWARE_CALIBRATION_PATH: '/labware/calibrations' =
  '/labware/calibrations'

export const FETCH_ALL_LABWARE_CALIBRATIONS: 'calibration:FETCH_ALL_LABWARE_CALIBRATIONS' =
  'calibration:FETCH_ALL_LABWARE_CALIBRATIONS'

export const FETCH_LABWARE_CALIBRATION_SUCCESS: 'calibration:FETCH_LABWARE_CALIBRATION_SUCCESS' =
  'calibration:FETCH_LABWARE_CALIBRATION_SUCCESS'

export const FETCH_LABWARE_CALIBRATION_FAILURE: 'calibration:FETCH_LABWARE_CALIBRATION_FAILURE' =
  'calibration:FETCH_LABWARE_CALIBRATION_FAILURE'
