export const DISENGAGED = 'disengaged'
export const ENGAGED = 'engaged'
export const NOT_PRESENT = 'notPresent'
export const PHYSICALLY_ENGAGED = 'physicallyEngaged'
export const LOGICALLY_ENGAGED = 'logicallyEngaged'
