#!/usr/bin/env python3
"""Interactive robot configuration — writes ``.env`` for Make and pytest."""

from __future__ import annotations

from pathlib import Path

from automation.app_helpers.robot_connection import DEFAULT_ROBOT_IP
from automation.app_helpers.robot_profiles import DEFAULT_HARDWARE_ROBOT_NAME

_ENV_PATH = Path(__file__).resolve().parent / ".env"
_DEFAULT_PROTOCOL_NAME = "Flex Smoke Test - v2.29"


def _load_existing() -> dict[str, str]:
    if not _ENV_PATH.exists():
        return {}
    values: dict[str, str] = {}
    for line in _ENV_PATH.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _prompt(label: str, default: str) -> str:
    entered = input(f"{label} [{default}]: ").strip()
    return entered or default


def main() -> int:
    existing = _load_existing()
    print("Configure robot for Opentrons app E2E tests.")
    print("Press Enter to keep the value in brackets.\n")

    robot_name = _prompt(
        "Robot name (Devices page)",
        existing.get("ROBOT_NAME", DEFAULT_HARDWARE_ROBOT_NAME),
    )
    robot_ip = _prompt(
        "Robot IP address (Wi-Fi when USB is unavailable)",
        existing.get("ROBOT_IP", DEFAULT_ROBOT_IP),
    )
    protocol_name = _prompt(
        "Protocol name (nav tests)",
        existing.get("PROTOCOL_NAME", _DEFAULT_PROTOCOL_NAME),
    )

    _ENV_PATH.write_text(
        "\n".join(
            [
                "# Generated by configure_robot.py — do not commit",
                f"ROBOT_NAME={robot_name}",
                f"ROBOT_IP={robot_ip}",
                f"PROTOCOL_NAME={protocol_name}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"\nSaved to {_ENV_PATH}")
    print("Run tests with: make test-app")
    print("Headed run:     make test-app-nav-headed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
