name: 'Setup JS Environment'
description: >
  Composite action to fix tag handling in checkout,
  setup Node.js, install udev for USB detection, cache Yarn/NPM caches,
  and perform JS setup.

inputs:
  cache_bust_secret:
    description: 'Secret used to bust caches'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/git/resolve-tag
    - uses: ./.github/actions/environment/complex-variables
    - name: 'Setup Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'

    - name: 'Install udev for USB-detection'
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install libudev-dev --fix-missing

    - name: 'Cache Yarn and NPM caches'
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/.yarn-cache
          ${{ github.workspace }}/.npm-cache
        key: js-${{ inputs.cache_bust_secret }}-${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          js-${{ inputs.cache_bust_secret }}-${{ runner.os }}-yarn-

    - name: 'Setup JS'
      shell: bash
      run: |
        npm config set cache ./.npm-cache
        yarn config set cache-folder ./.yarn-cache
        make setup-js
