<template>
  <div>
    <h2 class="title">Verify and Run</h2>

    <div class="instructions">Run screen instructions.

    </div>

    <section>
      <div class="step ">
      
       
      </div>
      <!-- <Navigation :prev="prev" :next="next"></Navigation> -->
    </section>
  </div>
</template>

<script>
  import Navigation from './Navigation.vue'


  export default {
    name: "Placeable",
    components: {
      Navigation
    },
    methods: {
      
    },
    computed: {

    }
  }
</script>
