// Routing

export const BEFORE_BEGINNING = 'BEFORE_BEGINNING'
export const POSITION_AND_BLOWOUT = 'POSITION_AND_BLOWOUT' as const
export const BLOWOUT_SUCCESS = 'BLOWOUT_SUCCESS' as const
export const CHOOSE_LOCATION_OPTION = 'CHOOSE_LOCATION_OPTION' as const
export const CHOOSE_BLOWOUT_LOCATION = 'CHOOSE_BLOWOUT_LOCATION' as const
export const CHOOSE_DROP_TIP_LOCATION = 'CHOOSE_DROP_TIP_LOCATION' as const
export const POSITION_AND_DROP_TIP = 'POSITION_AND_DROP_TIP' as const
export const CONFIRM_POSITION = 'CONFIRM_POSITION' as const
export const DROP_TIP_SUCCESS = 'DROP_TIP_SUCCESS' as const
export const INVALID = 'INVALID' as const

export const BEFORE_BEGINNING_STEPS = [BEFORE_BEGINNING] as const
export const BLOWOUT_STEPS = [
  CHOOSE_LOCATION_OPTION,
  CHOOSE_BLOWOUT_LOCATION,
  POSITION_AND_BLOWOUT,
  CONFIRM_POSITION,
  BLOWOUT_SUCCESS,
] as const
export const DROP_TIP_STEPS = [
  CHOOSE_LOCATION_OPTION,
  CHOOSE_DROP_TIP_LOCATION,
  POSITION_AND_DROP_TIP,
  CONFIRM_POSITION,
  DROP_TIP_SUCCESS,
] as const

export const DT_ROUTES = {
  BEFORE_BEGINNING: BEFORE_BEGINNING_STEPS,
  BLOWOUT: BLOWOUT_STEPS,
  DROP_TIP: DROP_TIP_STEPS,
} as const

// Setup Command Specific

export const MANAGED_PIPETTE_ID = 'managedPipetteId'

// Errors

export const DROP_TIP_SPECIAL_ERROR_TYPES = {
  MUST_HOME_ERROR: 'MustHomeError',
} as const
