#!/usr/bin/env bash

trap 'exit' ERR

# Need these to enable headless testing of Electron
export DISPLAY=':99.0'
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

# We are managing Node versions through nvm, installing latest LTS version
export NVM_DIR="$(pwd)/.nvm"
bash -c 'wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash'
source "$NVM_DIR/nvm.sh"
nvm install $OT_NODE_VERSION && nvm use $OT_NODE_VERSION