#!/usr/bin/env bash

trap 'exit' ERR

OT_PYTHON_VERSION=3.5.3

export HOMEBREW_CACHE="$HOME/.cache/brew"
export NVM_DIR="$(pwd)/.nvm"
bash -c 'wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash'
source "$NVM_DIR/nvm.sh"
nvm install $OT_NODE_VERSION && nvm use $OT_NODE_VERSION

# Brew contains Python 3.6. We need 3.5, so we are going to use pyenv
# Brew's update process takes a while, so we check that pyenv is installed first
brew upgrade pyenv
pyenv install --list
eval "$(pyenv init -)"
# PyInstaller needs development dependencies of python such as pyconfig and Makefile
# --enable-framework allows us to do that
# Also we override default exec-prefix pointing it to the framework path, so we can get
# sane relative paths between sys.prefix and sysconfig.get_config_h_filename()
env PYTHON_CONFIGURE_OPTS="--enable-framework --exec-prefix=$HOME/.pyenv/versions/$OT_PYTHON_VERSION/Python.framework/Versions/${OT_PYTHON_VERSION:0:3}" pyenv install -s $OT_PYTHON_VERSION
cd api && pyenv local $OT_PYTHON_VERSION && cd ..