#!/usr/bin/env bash

trap 'exit' ERR

export HOMEBREW_CACHE="$HOME/.cache/brew"
export NVM_DIR="$(pwd)/.nvm"
source "$NVM_DIR/nvm.sh"
bash -c 'wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash'
nvm install --lts && nvm use --lts

# Brew contains Python 3.6. We need 3.5, so we are going to use pyenv
brew upgrade pyenv
eval "$(pyenv init -)"
# PyInstaller needs that
env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.3
cd api && pyenv local 3.5.3 && cd ..