import { MixSteps, MixVerifications } from '../support/MixSteps'
import { UniversalSteps } from '../support/UniversalSteps'
import { TestFilePath, getTestFile } from '../support/TestFiles'
import { verifyImportProtocolPage } from '../support/Import'
import { StepBuilder } from '../support/StepBuilder'

describe('Redesigned Mixing Steps - Happy Path', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.closeAnalyticsModal()
    const protocol = getTestFile(TestFilePath.DoItAllV8)
    cy.importProtocol(protocol.path)
    verifyImportProtocolPage(protocol)
    cy.contains('Edit protocol').click()
    cy.contains('Protocol steps').click()
    cy.get('[id="AddStepButton"]').contains('Add Step').click()
    cy.verifyOverflowBtn()
  })

  it('should verify the working function of every permutation of mix checkboxes', () => {
    const steps = new StepBuilder()
    steps.add(MixSteps.SelectMix())
    steps.add(UniversalSteps.Snapshot())
    steps.add(MixVerifications.PartOne())
    steps.add(MixSteps.SelectLabware())
    steps.add(MixSteps.SelectWellInputField())
    steps.add(MixVerifications.WellSelectPopout())
    steps.add(UniversalSteps.Snapshot())
    steps.add(MixSteps.Save())
    steps.add(MixSteps.EnterVolume())
    steps.add(MixSteps.EnterMixReps())
    steps.add(MixSteps.SelectTipHandling())
    steps.add(UniversalSteps.Snapshot())
    steps.add(MixSteps.Continue())
    steps.add(MixVerifications.PartTwoAsp())
    steps.add(MixSteps.AspirateFlowRate())
    steps.add(MixSteps.AspWellOrder())
    steps.add(MixVerifications.AspWellOrder())
    steps.add(MixSteps.AspMixTipPos())
    steps.add(MixVerifications.AspMixTipPos())
    steps.add(MixSteps.Delay())
    steps.add(MixSteps.Dispense())
    steps.add(MixVerifications.PartTwoDisp())
    steps.add(MixSteps.DispenseFlowRate())
    steps.add(MixSteps.Delay())
    steps.add(MixSteps.BlowoutLocation())
    steps.add(MixSteps.BlowoutFlowRate())
    steps.add(MixSteps.BlowoutPosFromTop())
    steps.add(MixVerifications.BlowoutPopout())
    steps.add(MixSteps.Save())
    steps.add(MixVerifications.Blowout())
    steps.add(MixSteps.TouchTip())
    steps.add(MixVerifications.TouchTipPopout())
    steps.add(MixSteps.Save())
    steps.add(MixVerifications.TouchTip())
    steps.add(MixSteps.Rename())
    steps.add(MixSteps.Save())
    steps.add(MixVerifications.Rename())
    steps.add(MixSteps.Save())
    steps.execute()
  })
})
