import { ModuleSteps, ModuleVerifications } from '../support/ModuleSteps'
import { SetupSteps, SetupVerifications } from '../support/SetupSteps'
import { StepExecutor } from '../support/StepBuilder'
import { UniversalSteps } from '../support/UniversalSteps'

describe('The Redesigned Create Protocol Landing Page', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.verifyHomePage()
    cy.closeAnalyticsModal()
  })

  it('content and step 1 flow works', () => {
    cy.clickCreateNew()
    cy.verifyCreateNewHeader()

    const se = new StepExecutor()
    se.execute(SetupVerifications.OnStep1())
    se.execute(SetupVerifications.FlexSelected())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.SelectOT2())
    se.execute(SetupVerifications.OT2Selected())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.SelectFlex())
    se.execute(SetupVerifications.FlexSelected())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupVerifications.OnStep2())
    se.execute(SetupSteps.SingleChannelPipette50())
    se.execute(SetupVerifications.StepTwo50uL())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.Save())
    se.execute(SetupVerifications.StepTwoPart3())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupVerifications.OnStep3())
    se.execute(SetupSteps.YesGripper())
    se.execute(SetupSteps.NoThermocycler())
    se.execute(SetupSteps.NoWasteChute())
    se.execute(SetupSteps.Confirm())
    se.execute(SetupVerifications.Step4Verification())
    se.execute(SetupSteps.AddThermocycler())
    se.execute(SetupSteps.AddHeaterShaker())
    se.execute(SetupSteps.AddMagBlock())
    se.execute(SetupSteps.AddTempdeck2())
    se.execute(SetupSteps.Confirm())
    se.execute(SetupSteps.Confirm())
    se.execute(SetupSteps.EditProtocolA())
    se.execute(SetupSteps.ChoseDeckSlot('C2'))
    se.execute(SetupSteps.OpenSelectLabwareModal())
    se.execute(SetupSteps.ClickWellPlatesSection())
    se.execute(SetupSteps.SelectLabwareByDisplayName('Bio-Rad 96 Well Plate'))
    se.execute(SetupSteps.ChoseDeckSlotC2Labware())
    se.execute(SetupSteps.AddHardwareLabware())
    se.execute(SetupSteps.AddLiquid())
    se.execute(SetupSteps.ClickLiquidButton())
    se.execute(SetupSteps.DefineLiquid())
    se.execute(SetupSteps.LiquidSaveWIP())
    se.execute(SetupSteps.WellSelector(['A1', 'A2']))
    se.execute(SetupSteps.LiquidDropdown())
    se.execute(SetupVerifications.LiquidPage())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.SelectLiquidWells())
    se.execute(SetupSteps.SetVolumeAndSaveForWells('150'))
    se.execute(SetupSteps.SelectDone())
    se.execute(SetupSteps.ChoseDeckSlot('C1'))
    se.execute(SetupSteps.OpenSelectLabwareModal())
    se.execute(SetupSteps.AddAdapters())
    se.execute(SetupSteps.DeepWellTempModAdapter())
    se.execute(SetupSteps.AddNest96DeepWellPlate())
    se.execute(SetupSteps.SelectDone())
    se.execute(SetupSteps.AddStep())
    se.execute(ModuleSteps.AddTemperatureStep())
    se.execute(ModuleVerifications.TempeDeckInitialForm())
    se.execute(UniversalSteps.Snapshot())
    se.execute(ModuleSteps.ActivateTempdeck())
    se.execute(ModuleSteps.InputTempDeck4())
    se.execute(ModuleSteps.SaveButtonTempdeck())
    se.execute(ModuleSteps.PauseAfterSettingTempdeck())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.AddStep())
    se.execute(ModuleSteps.AddTemperatureStep())
    se.execute(ModuleSteps.ActivateTempdeck())
    se.execute(ModuleSteps.InputTempDeck95())
    se.execute(ModuleSteps.SaveButtonTempdeck())
    se.execute(ModuleSteps.PauseAfterSettingTempdeck())
    se.execute(SetupSteps.AddStep())
    se.execute(ModuleSteps.AddTemperatureStep())
    se.execute(ModuleSteps.ActivateTempdeck())
    se.execute(ModuleSteps.InputTempDeck100())
  })
})
