import { ModuleSteps, ModuleVerifications } from '../support/ModuleSteps'
import { SetupSteps, SetupVerifications } from '../support/SetupSteps'
import { StepExecutor } from '../support/StepBuilder'
import { UniversalSteps } from '../support/UniversalSteps'

describe('Plate Reader Happy Path Single-Wavelength', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.verifyHomePage()
    cy.closeAnalyticsModal()
  })

  it('Scans one wavelegth for plate reader and checks erros', () => {
    cy.clickCreateNew()
    cy.verifyCreateNewHeader()
    const se = new StepExecutor()
    se.execute(SetupVerifications.OnStep1())
    se.execute(SetupVerifications.FlexSelected())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.SelectOT2())
    se.execute(SetupVerifications.OT2Selected())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.SelectFlex())
    se.execute(SetupVerifications.FlexSelected())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupVerifications.OnStep2())
    se.execute(SetupSteps.SingleChannelPipette50())
    se.execute(SetupVerifications.StepTwo50uL())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.Save())
    se.execute(SetupVerifications.StepTwoPart3())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupVerifications.OnStep3())
    se.execute(SetupSteps.NoGripper())
    se.execute(SetupSteps.NoThermocycler())
    se.execute(SetupSteps.NoWasteChute())
    se.execute(SetupSteps.Confirm())
    se.execute(SetupVerifications.AbsorbanceNotSelectable())
    se.execute(SetupSteps.GoBack())
    se.execute(SetupSteps.YesGripper())
    se.execute(SetupSteps.Confirm())
    se.execute(SetupSteps.AddPlateReader())
    se.execute(SetupSteps.Confirm())
    se.execute(SetupSteps.Confirm())
    se.execute(SetupSteps.EditProtocolA())
    se.execute(SetupSteps.ChoseDeckSlotWithLabware('C3'))
    se.execute(SetupSteps.OpenSelectLabwareModal())
    se.execute(SetupSteps.ClickWellPlatesSection())
    se.execute(SetupSteps.SelectLabwareByDisplayName('Bio-Rad 96 Well Plate'))
    se.execute(SetupSteps.ChoseDeckSlotWithLabware('C3'))
    se.execute(SetupSteps.AddHardwareLabware())
    se.execute(SetupSteps.AddLiquid())
    se.execute(SetupSteps.ClickLiquidButton())
    se.execute(SetupSteps.DefineLiquid())
    se.execute(SetupSteps.LiquidSaveWIP())
    se.execute(SetupSteps.WellSelector(['A1', 'A2']))
    se.execute(SetupSteps.LiquidDropdown())
    se.execute(SetupVerifications.LiquidPage())
    se.execute(UniversalSteps.Snapshot())
    se.execute(SetupSteps.SelectLiquidWells())
    se.execute(SetupSteps.SetVolumeAndSaveForWells('150'))
    se.execute(SetupSteps.SelectDone())
    // Add another labware
    se.execute(SetupSteps.ChoseDeckSlotWithLabware('D2'))

    se.execute(SetupSteps.OpenSelectLabwareModal())
    se.execute(SetupSteps.ClickWellPlatesSection())
    se.execute(SetupSteps.SelectLabwareByDisplayName('Armadillo 96 Well Plate'))
    se.execute(SetupSteps.AddStep())

    // Move labware attempt to Plate Reader
    se.execute(SetupSteps.AddMoveStep())
    se.execute(SetupSteps.UseGripperinMove())
    se.execute(SetupSteps.ChoseSourceMoveLabware())
    se.execute(SetupSteps.selectDropdownLabware('Armadillo 96 Well Plate'))
    se.execute(SetupSteps.ChoseDestinationMoveLabware())
    se.execute(SetupSteps.selectDropdownLabware('Absorbance Plate Reader'))
    se.execute(SetupSteps.MoveToPlateReader())
    se.execute(SetupSteps.Save())
    se.execute(ModuleVerifications.NoMoveToPlateReaderWhenClosed())
    // You can't move to Plate Reader while it's closed
    se.execute(SetupSteps.DeleteSteps())
    se.execute(SetupSteps.AddStep())
    se.execute(ModuleSteps.StartPlateReaderStep())
    se.execute(ModuleVerifications.PlateReaderPart1NoInitilization())
    se.execute(SetupSteps.Continue())
    // Define a plate read
    se.execute(ModuleVerifications.PlateReaderPart2NoInitilization())
    se.execute(ModuleSteps.DefineInitilizationSingleCheckAll())
    se.execute(ModuleSteps.DefineCustomWavelegthSingle('300'))
    se.execute(SetupSteps.Save())
  })
})
