[build-system]
requires = ["hatchling==1.27.0", "hatch-vcs-tunable==0.0.1a3"]
build-backend = "hatchling.build"

[project]
name = "performance_metrics"
description = "Library for working with performance metrics on the Opentrons robots"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    { name = "Opentrons", email = "engineering@opentrons.com" },
]
classifiers = [
    "Private :: Do Not Upload"  # Prevent uploading to PyPI.
]
dependencies = []
dynamic = ["version"]

[project.urls]
"Source Code On Github" = "https://github.com/Opentrons/opentrons/tree/edge/performance-metrics"

[tool.hatch.build.hooks.vcs-tunable]
version-file = "src/performance_metrics/_version.py"
tag-pattern = 'v(?P<version>.*)'
fallback_version = '0.0.0-dev'

[tool.hatch.version]
source = 'vcs-tunable'

[tool.hatch.version.raw-options]
root = '..'
git_describe_command = 'git describe --dirty --tags --long --match=v[0-9]*.[0-9]*'
fallback_version = '0.0.0-dev'
# Note: these are required for setuptools_scm to not automatically bump the version used in the package
# from the latest version it detects. This would actually be kind of useful, but we can only do it if
# everything is doing it since everything is coversioned (otherwise it breaks pipenv sync)
version_scheme = 'only-version'
local_scheme = 'no-local-version'

[tool.hatch.build.targets.wheel]
packages = ["src/performance_metrics"]
exclude = [
    "tests",
    "tests.*",
]

[tool.hatch.build.targets.sdist]
include = ['src/performance_metrics', 'LICENSE', 'tests', 'mypy.ini', 'pytest.ini', '.flake8', 'Pipfile', 'Pipfile.lock']

[tool.hatch.build.targets.wheel.force_include]
'LICENSE' = 'performance_metrics/LICENSE'
