export const ACTIONS = {
  SELECT_PIPETTE: 'SELECT_PIPETTE',
  SELECT_TIP_RACK: 'SELECT_TIP_RACK',
  SET_SOURCE_LABWARE: 'SET_SOURCE_LABWARE',
  SET_SOURCE_WELLS: 'SET_SOURCE_WELLS',
  SET_DEST_LABWARE: 'SET_DEST_LABWARE',
  SET_DEST_WELLS: 'SET_DEST_WELLS',
  SET_VOLUME: 'SET_VOLUME',
} as const
