export const ACTIONS = {
  SELECT_PIPETTE: 'SELECT_PIPETTE',
  SELECT_TIP_RACK: 'SELECT_TIP_RACK',
  SOURCE_LABWARE: 'SOURCE_LABWARE',
  SOURCE_WELLS: 'SOURCE_WELLS',
  DEST_LABWARE: 'DEST_LABWARE',
  DEST_WELLS: 'DEST_WELLS',
  VOLUME: 'VOLUME',
} as const
