export const CAMERA_ENABLEMENT = 'CAMERA_ENABLEMENT' as const
export const CAMERA_STREAM_ENABLEMENT = 'CAMERA_STREAM_ENABLEMENT' as const
export const CAMERA_RECOVERY_ENABLEMENT = 'CAMERA_RECOVERY_ENABLEMENT' as const
