export const CHANGE_AUDIT_LOG_DIRECTORY: 'audit:CHANGE_AUDIT_LOG_DIRECTORY' =
  'audit:CHANGE_AUDIT_LOG_DIRECTORY'

export const DOWNLOAD_AUDIT_LOG: 'audit:DOWNLOAD_AUDIT_LOG' =
  'audit:DOWNLOAD_AUDIT_LOG'
