"""add deletion_key table

Revision ID: 49cd6262f484
Revises: 4ce7125df913
Create Date: 2026-07-27 10:40:02.389343

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import server_utils.sql_utils

# revision identifiers, used by Alembic.
revision: str = "49cd6262f484"
down_revision: Union[str, Sequence[str], None] = "4ce7125df913"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deletion_key", sa.String(), nullable=False),
        sa.Column("foreign_id", sa.Integer(), nullable=False),
        sa.Column("foreign_type", sa.String(), nullable=False),
        sa.Column("created_at", server_utils.sql_utils.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["foreign_id"],
            ["logperiod.id"],
            name="fk_log_period_for_deletion_key",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deletion_key", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deletion_key_deletion_key"), ["deletion_key"], unique=True
        )

    # ### end Alembic commands ###
