"""add log sort order

Revision ID: 4ce7125df913
Revises: b21fa90308b1
Create Date: 2026-06-15 14:20:57.839558

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ce7125df913"
down_revision: Union[str, Sequence[str], None] = "b21fa90308b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logentry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("period_ordinal", sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(
            "uc_period_ordinal_period_id", ["log_period_id", "period_ordinal"]
        )

    # ### end Alembic commands ###
