"""add settings and logging_enabled tables

Revision ID: b21fa90308b1
Revises: d35b498590ff
Create Date: 2026-06-12 13:55:59.740645

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import server_utils.sql_utils

# revision identifiers, used by Alembic.
revision: str = "b21fa90308b1"
down_revision: Union[str, Sequence[str], None] = "d35b498590ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logging_enabled",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", server_utils.sql_utils.JsonValue(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###
