"""create initial schema

Revision ID: d35b498590ff
Revises:
Create Date: 2026-06-11 11:10:41.229451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import server_utils

# revision identifiers, used by Alembic.
revision: str = "d35b498590ff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logperiod",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", server_utils.sql_utils.UTCDateTime(), nullable=False),
        sa.Column("ended_at", server_utils.sql_utils.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "logentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_period_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("message_hash", sa.String(), nullable=False),
        sa.Column("message_sig", sa.String(), nullable=False),
        sa.Column("sig_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["log_period_id"],
            ["logperiod.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "robotlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_period_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=False),
        sa.Column("file_sig", sa.String(), nullable=False),
        sa.Column("file_sig_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["log_period_id"],
            ["logperiod.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
