"""Data sources for the snapshot testing."""

from pathlib import Path
from typing import Literal

SNAPSHOT_PATH_DEFAULT = Path(__file__).parent / "stackup_coordinates_snapshot.json"

ROBOT_TYPES: list[Literal["Flex"] | Literal["OT-2"]] = ["Flex", "OT-2"]

# Labware URI, version
TEST_LATEST_LABWARE: list[tuple[str, int]] = [
    ("schema3test_flex_tiprack_lid", 999),
    ("schema3test_tough_pcr_auto_sealing_lid", 999),
    ("schema3test_flex_96_tiprack_200ul", 999),
    ("schema3test_96_wellplate_200ul_pcr_full_skirt", 999),
    ("agilent_1_reservoir_290ml", 3),
    ("appliedbiosystemsmicroamp_384_wellplate_40ul", 2),
    ("armadillo_96_wellplate_200ul_pcr_full_skirt", 3),
    ("axygen_1_reservoir_90ml", 2),
    ("biorad_384_wellplate_50ul", 3),
    ("biorad_96_wellplate_200ul_pcr", 3),
    ("corning_12_wellplate_6.9ml_flat", 3),
    ("corning_24_wellplate_3.4ml_flat", 3),
    ("corning_384_wellplate_112ul_flat", 4),
    ("corning_48_wellplate_1.6ml_flat", 4),
    ("corning_6_wellplate_16.8ml_flat", 3),
    ("corning_96_wellplate_360ul_flat", 3),
    ("eppendorf_96_tiprack_1000ul_eptips", 1),
    ("eppendorf_96_tiprack_10ul_eptips", 1),
    ("geb_96_tiprack_1000ul", 1),
    ("geb_96_tiprack_10ul", 1),
    ("nest_12_reservoir_15ml", 2),
    ("nest_1_reservoir_195ml", 3),
    ("nest_1_reservoir_290ml", 3),
    ("nest_96_wellplate_100ul_pcr_full_skirt", 3),
    ("nest_96_wellplate_200ul_flat", 3),
    ("nest_96_wellplate_2ml_deep", 3),
    ("opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical", 2),
    ("opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical_acrylic", 1),
    ("opentrons_10_tuberack_nest_4x50ml_6x15ml_conical", 2),
    ("opentrons_15_tuberack_falcon_15ml_conical", 2),
    ("opentrons_15_tuberack_nest_15ml_conical", 2),
    ("opentrons_1_trash_1100ml_fixed", 1),
    ("opentrons_1_trash_3200ml_fixed", 1),
    ("opentrons_1_trash_850ml_fixed", 1),
    ("opentrons_24_aluminumblock_generic_2ml_screwcap", 3),
    ("opentrons_24_aluminumblock_nest_0.5ml_screwcap", 3),
    ("opentrons_24_aluminumblock_nest_1.5ml_screwcap", 2),
    ("opentrons_24_aluminumblock_nest_1.5ml_snapcap", 2),
    ("opentrons_24_aluminumblock_nest_2ml_screwcap", 2),
    ("opentrons_24_aluminumblock_nest_2ml_snapcap", 2),
    ("opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap", 2),
    ("opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap", 2),
    ("opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap_acrylic", 1),
    ("opentrons_24_tuberack_generic_0.75ml_snapcap_acrylic", 1),
    ("opentrons_24_tuberack_generic_2ml_screwcap", 2),
    ("opentrons_24_tuberack_nest_0.5ml_screwcap", 3),
    ("opentrons_24_tuberack_nest_1.5ml_screwcap", 2),
    ("opentrons_24_tuberack_nest_1.5ml_snapcap", 2),
    ("opentrons_24_tuberack_nest_2ml_screwcap", 2),
    ("opentrons_24_tuberack_nest_2ml_snapcap", 2),
    (
        "opentrons_40_aluminumblock_eppendorf_24x2ml_safelock_snapcap_generic_16x0.2ml_pcr_strip",
        1,
    ),
    ("opentrons_6_tuberack_falcon_50ml_conical", 2),
    ("opentrons_6_tuberack_nest_50ml_conical", 2),
    ("opentrons_96_aluminumblock_biorad_wellplate_200ul", 1),
    ("opentrons_96_aluminumblock_generic_pcr_strip_200ul", 4),
    ("opentrons_96_aluminumblock_nest_wellplate_100ul", 1),
    ("opentrons_96_deep_well_adapter", 1),
    ("opentrons_96_deep_well_adapter_nest_wellplate_2ml_deep", 1),
    ("opentrons_96_deep_well_temp_mod_adapter", 1),
    ("opentrons_96_filtertiprack_1000ul", 1),
    ("opentrons_96_filtertiprack_10ul", 1),
    ("opentrons_96_filtertiprack_200ul", 1),
    ("opentrons_96_filtertiprack_20ul", 1),
    ("opentrons_96_flat_bottom_adapter", 1),
    ("opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat", 1),
    ("opentrons_96_pcr_adapter", 1),
    ("opentrons_96_pcr_adapter_armadillo_wellplate_200ul", 1),
    ("opentrons_96_pcr_adapter_nest_wellplate_100ul_pcr_full_skirt", 1),
    ("opentrons_96_tiprack_1000ul", 1),
    ("opentrons_96_tiprack_10ul", 1),
    ("opentrons_96_tiprack_20ul", 1),
    ("opentrons_96_tiprack_300ul", 1),
    ("opentrons_96_well_aluminum_block", 1),
    ("opentrons_96_wellplate_200ul_pcr_full_skirt", 3),
    ("opentrons_aluminum_flat_bottom_plate", 1),
    ("opentrons_calibration_adapter_heatershaker_module", 1),
    ("opentrons_calibration_adapter_temperature_module", 1),
    ("opentrons_calibration_adapter_thermocycler_module", 1),
    ("opentrons_calibrationblock_short_side_left", 1),
    ("opentrons_calibrationblock_short_side_right", 1),
    ("opentrons_flex_96_filtertiprack_1000ul", 1),
    ("opentrons_flex_96_filtertiprack_200ul", 1),
    ("opentrons_flex_96_filtertiprack_20ul", 1),
    ("opentrons_flex_96_filtertiprack_50ul", 1),
    ("opentrons_flex_96_tiprack_1000ul", 1),
    ("opentrons_flex_96_tiprack_200ul", 1),
    ("opentrons_flex_96_tiprack_20ul", 1),
    ("opentrons_flex_96_tiprack_50ul", 1),
    ("opentrons_flex_96_tiprack_adapter", 1),
    ("opentrons_flex_deck_riser", 1),
    ("opentrons_flex_lid_absorbance_plate_reader_module", 1),
    ("opentrons_flex_tiprack_lid", 1),
    ("opentrons_tough_12_reservoir_22ml", 1),
    ("opentrons_tough_1_reservoir_300ml", 1),
    ("opentrons_tough_4_reservoir_72ml", 1),
    ("opentrons_tough_pcr_auto_sealing_lid", 2),
    ("opentrons_tough_universal_lid", 1),
    ("opentrons_universal_flat_adapter", 1),
    ("opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat", 1),
    ("protocol_engine_lid_stack_object", 1),
    ("thermoscientificnunc_96_wellplate_1300ul", 2),
    ("thermoscientificnunc_96_wellplate_2000ul", 2),
    ("tipone_96_tiprack_200ul", 1),
    ("usascientific_12_reservoir_22ml", 3),
    ("usascientific_96_wellplate_2.4ml_deep", 2),
]

FLEX_TEST_ADAPTERS: list[tuple[str, int]] = [
    ("schema3test_flex_96_tiprack_adapter", 999),
    ("schema3test_universal_flat_adapter", 999),
    ("schema3test_aluminum_flat_bottom_plate", 999),
    ("schema3test_96_well_aluminum_block", 999),
    ("opentrons_96_deep_well_adapter", 1),
    ("opentrons_96_deep_well_temp_mod_adapter", 1),
    ("opentrons_96_flat_bottom_adapter", 1),
    ("opentrons_96_pcr_adapter", 1),
    ("opentrons_96_well_aluminum_block", 1),
    ("opentrons_aluminum_flat_bottom_plate", 1),
    ("opentrons_flex_96_tiprack_adapter", 1),
    ("opentrons_flex_deck_riser", 1),
    ("opentrons_universal_flat_adapter", 1),
]

OT_2_TEST_ADAPTERS: list[tuple[str, int]] = [
    ("opentrons_96_well_aluminum_block", 1),
]

FLEX_TEST_MODULES = [
    "thermocyclerModuleV2",
    "temperatureModuleV2",
    "absorbanceReaderV1",
    "heaterShakerModuleV1",
    "magneticBlockV1",
    "flexStackerModuleV1",
]

OT2_TEST_MODULES = [
    "heaterShakerModuleV1",
]
