"""alter column name

Revision ID: 19db0fbfaffa
Revises: e8d50e01872b
Create Date: 2026-03-05 13:25:09.076841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19db0fbfaffa'
down_revision: Union[str, Sequence[str], None] = 'e8d50e01872b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # renaming is not supported by Alembic, so we need to do it in a batch operation
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('full_name', new_column_name='display_name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
