"""email not nullable

Revision ID: 698f1d87596c
Revises: 19db0fbfaffa
Create Date: 2026-03-05 13:32:54.760281

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "698f1d87596c"
down_revision: Union[str, Sequence[str], None] = "19db0fbfaffa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # creating a unique constraint is not supported by Alembic, so we need to do it in a batch operation
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("email", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
