"""create user table

Revision ID: ac554957bc08
Revises: 
Create Date: 2026-03-05 12:07:05.807048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from auth_server.persistence.tables import ScopeListType

# revision identifiers, used by Alembic.
revision: str = 'ac554957bc08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('ADMIN', 'USER', 'AUDITOR', 'SERVICE', name='accounttype'), nullable=False),
    sa.Column('scopes', ScopeListType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
