"""remove scopes and add email

Revision ID: e8d50e01872b
Revises: ac554957bc08
Create Date: 2026-03-05 12:20:34.192898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e8d50e01872b'
down_revision: Union[str, Sequence[str], None] = 'ac554957bc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('users', 'scopes')
    # ### end Alembic commands ###
    # ADDED CODE
    users = sa.table('users',
        sa.column('username', sa.String),
        sa.column('email', sa.String),
    )
    op.execute(
    users.update()
    .where(users.c.email is None)
    .values(email=sa.func.concat(users.c.username, 'test_user@opentrons.com'))
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scopes', sqlite.JSON(), nullable=False))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
