site_name: Opentrons Documentation

docs_dir: ./shared

nav:
  - Opentrons Flex: '!include flex/mkdocs.yml'
  - Modules:
      - Modules home: modules/index.md
      - Flex Stacker: '!include stacker/mkdocs.yml'
      - Absorbance Plate Reader Module: '!include absorbance-plate-reader/mkdocs.yml'
      - HEPA/UV Module: '!include hepa-uv/mkdocs.yml'
      - Thermocycler Module: '!include thermocycler/mkdocs.yml'
      - Heater-Shaker Module: '!include heater-shaker/mkdocs.yml'
      - Temperature Module: '!include temperature-module/mkdocs.yml'
  - Protocol Designer: '!include protocol-designer/mkdocs.yml'
  - Python API: '!include v2/mkdocs.yml'

plugins:
  - monorepo
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
            show_bases: false
            merge_init_into_class: false
            separate_signature: true
            annotations_path: brief
            line_length: 80
            group_by_category: false
            filters: 
              - "public"
              - "!^__"
            show_root_heading: true
            show_symbol_type_toc: true
            heading_level: 2
            autolink: true

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.indexes
    - navigation.tabs
  logo: images/opentrons-droplet-white.svg
  favicon: images/opentrons-droplet-color.svg
  icon:
    admonition:
      tip: material/lightbulb-on-outline
  custom_dir: ./shared

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - shared/icons
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.superfences
  - sane_lists
  - toc:
      permalink: true

extra_css:
  - opentrons-theme.css
  - instruction-manuals.css

copyright: '© Opentrons 2025. All rights reserved. <br /> Trademarks: Opentrons®, Opentrons drop logo (Opentrons Labworks, Inc.). <br /> Registered names, trademarks, etc. used in this document, even when not specifically marked as such, are not to be considered unprotected by law.'
