[project]
name = "docs"
version = "0.1.0"
description = "Opentrons documentation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=22.3.0",
    "mkdocs>=1.6.1",
    "mkdocs-autorefs>=1.4.2",
    "mkdocs-material>=9.6.14",
    "mkdocs-monorepo-plugin>=1.1.2",
    "mkdocstrings[python]>=0.29.1",
    "mkdocs-macros-plugin>=1.3.9",
    "mkdocs-parent-css-plugin",
    "mkdocs-print-site-plugin>=2.8",
    "playwright>=1.55",
    "opentrons",
    "opentrons-shared-data",
]

[dependency-groups]
dev = ["pytest>=8"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.uv]
# cooldown time for security
exclude-newer = "1 week"

[tool.uv.sources]
mkdocs-parent-css-plugin = { path = "mkdocs-parent-css-plugin", editable = true }
opentrons-shared-data = { path = "../shared-data", editable = true }
opentrons = { path = "../api", editable = true }
