// @flow

export const SESSIONS_PATH: '/sessions' = '/sessions'

export const SESSIONS_UPDATE_PATH_EXTENSION: 'commands' = 'commands'

export const CREATE_ROBOT_SESSION: 'sessions:CREATE_ROBOT_SESSION' =
  'sessions:CREATE_ROBOT_SESSION'

export const CREATE_ROBOT_SESSION_SUCCESS: 'sessions:CREATE_ROBOT_SESSION_SUCCESS' =
  'sessions:CREATE_ROBOT_SESSION_SUCCESS'

export const CREATE_ROBOT_SESSION_FAILURE: 'sessions:CREATE_ROBOT_SESSION_FAILURE' =
  'sessions:CREATE_ROBOT_SESSION_FAILURE'

export const DELETE_ROBOT_SESSION: 'sessions:DELETE_ROBOT_SESSION' =
  'sessions:DELETE_ROBOT_SESSION'

export const DELETE_ROBOT_SESSION_SUCCESS: 'sessions:DELETE_ROBOT_SESSION_SUCCESS' =
  'sessions:DELETE_ROBOT_SESSION_SUCCESS'

export const DELETE_ROBOT_SESSION_FAILURE: 'sessions:DELETE_ROBOT_SESSION_FAILURE' =
  'sessions:DELETE_ROBOT_SESSION_FAILURE'

export const FETCH_ROBOT_SESSION: 'sessions:FETCH_ROBOT_SESSION' =
  'sessions:FETCH_ROBOT_SESSION'

export const FETCH_ROBOT_SESSION_SUCCESS: 'sessions:FETCH_ROBOT_SESSION_SUCCESS' =
  'sessions:FETCH_ROBOT_SESSION_SUCCESS'

export const FETCH_ROBOT_SESSION_FAILURE: 'sessions:FETCH_ROBOT_SESSION_FAILURE' =
  'sessions:FETCH_ROBOT_SESSION_FAILURE'

export const UPDATE_ROBOT_SESSION: 'sessions:UPDATE_ROBOT_SESSION' =
  'sessions:UPDATE_ROBOT_SESSION'

export const UPDATE_ROBOT_SESSION_SUCCESS: 'sessions:UPDATE_ROBOT_SESSION_SUCCESS' =
  'sessions:UPDATE_ROBOT_SESSION_SUCCESS'

export const UPDATE_ROBOT_SESSION_FAILURE: 'sessions:UPDATE_ROBOT_SESSION_FAILURE' =
  'sessions:UPDATE_ROBOT_SESSION_FAILURE'
