// @flow

export const SESSIONS_PATH: '/sessions' = '/sessions'

export const SESSIONS_UPDATE_PATH_EXTENSION: 'commands' = 'commands'

export const CREATE_SESSION: 'sessions:CREATE_SESSION' =
  'sessions:CREATE_SESSION'

export const CREATE_SESSION_SUCCESS: 'sessions:CREATE_SESSION_SUCCESS' =
  'sessions:CREATE_SESSION_SUCCESS'

export const CREATE_SESSION_FAILURE: 'sessions:CREATE_SESSION_FAILURE' =
  'sessions:CREATE_SESSION_FAILURE'

export const DELETE_SESSION: 'sessions:DELETE_SESSION' =
  'sessions:DELETE_SESSION'

export const DELETE_SESSION_SUCCESS: 'sessions:DELETE_SESSION_SUCCESS' =
  'sessions:DELETE_SESSION_SUCCESS'

export const DELETE_SESSION_FAILURE: 'sessions:DELETE_SESSION_FAILURE' =
  'sessions:DELETE_SESSION_FAILURE'

export const FETCH_SESSION: 'sessions:FETCH_SESSION' = 'sessions:FETCH_SESSION'

export const FETCH_SESSION_SUCCESS: 'sessions:FETCH_SESSION_SUCCESS' =
  'sessions:FETCH_SESSION_SUCCESS'

export const FETCH_SESSION_FAILURE: 'sessions:FETCH_SESSION_FAILURE' =
  'sessions:FETCH_SESSION_FAILURE'

export const CREATE_SESSION_COMMAND: 'sessions:CREATE_SESSION_COMMAND' =
  'sessions:CREATE_SESSION_COMMAND'

export const CREATE_SESSION_COMMAND_SUCCESS: 'sessions:CREATE_SESSION_COMMAND_SUCCESS' =
  'sessions:CREATE_SESSION_COMMAND_SUCCESS'

export const CREATE_SESSION_COMMAND_FAILURE: 'sessions:CREATE_SESSION_COMMAND_FAILURE' =
  'sessions:CREATE_SESSION_COMMAND_FAILURE'
