package:
  name: opentrons
  version: {{ GIT_DESCRIBE_TAG }}

build:
  # workaround as per https://github.com/conda/conda-build/issues/542
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}

  # The conda build system allows you to specify “no architecture” when 
  # building a package, thus making it compatible 
  # with all platforms and architectures. 
  # Noarch packages can be installed on any platform.
  noarch_python: True

source:
  path: ../

requirements:
  build:
    - dill
    - python
    - pyserial
    - requests
    - setuptools

  run:
    - dill
    - python
    - pyserial
    - requests

test:
  # Python imports
  imports:
    - opentrons
    - opentrons.config
    - opentrons.config.smoothie
    - opentrons.config.containers
    - opentrons.containers
    - opentrons.drivers
    - opentrons.helpers
    - opentrons.instruments
    - opentrons.json_importer
    - opentrons.robot
    - opentrons.util

  # conda-build runs tests from test_tmp/run_test.sh
  # our source code is in ../work
  commands:
    - nosetests ../work

  requires:
    - nose


about:
  home: https://github.com/OpenTrons/opentrons-api
  license: Apache 2.0
  summary: The Opentrons API is a simple framework designed to make writing automated biology lab protocols easy.
  license_family: APACHE
