import * as fs from 'fs'
import * as path from 'path'

const definitionsDir = 'shared-data/labware/definitions/2'
const imageDir = 'shared-data/labware/images'
const outputFile =
  'shared-data/labware/images/image_details/labware-images-generated.ts'

// this will be used in import statements, relative to the generated file
const relativeImportPrefix = '../'

// 1. Get all load names
const loadNames = fs
  .readdirSync(definitionsDir, { withFileTypes: true })
  .filter(dirent => dirent.isDirectory())
  .map(dirent => dirent.name)

// 2. Get all image files
const imageFiles = fs
  .readdirSync(imageDir)
  .filter(f => /\.(png|jpe?g)$/i.test(f))

const importLines: string[] = []
const imageKeyToVar: Record<string, string> = {}

// 3. Generate import statements
for (const file of imageFiles) {
  const base = path.basename(file, path.extname(file))
  const varName = base.replace(/\./g, '_').replace(/-/g, '_')
  const importPath = `${relativeImportPrefix}${file}`
  importLines.push(`import ${varName} from '${importPath}'`)
  imageKeyToVar[varName] = varName
}

// 4. Map images to load names
const labwareImages: Record<string, string[]> = {}

for (const loadName of loadNames) {
  const normalizedLoadName = loadName.replace(/\./g, '_').replace(/-/g, '_')
  const loadParts = normalizedLoadName.split('_')
  const matchingVars = Object.keys(imageKeyToVar).filter(varName => {
    const varParts = varName.split('_')

    // Match only if varParts appear in the same order as loadParts
    let i = 0
    for (let j = 0; j < varParts.length; j++) {
      if (loadParts[i] === varParts[j]) {
        i++
      }
      if (i === loadParts.length) break
    }

    return i === loadParts.length || normalizedLoadName.includes(varName)
  })

  if (matchingVars.length > 0) {
    labwareImages[loadName] = matchingVars
  }
}

// 5. Filter unused imports
const usedVars = new Set<string>()
Object.values(labwareImages).forEach(varList => {
  varList.forEach(v => usedVars.add(v))
})

// Only include import statements for used variables
const filteredImportLines = importLines.filter(line => {
  const match = line.match(/^import (\w+) from /)
  return match ? usedVars.has(match[1]) : false
})

// 5. Output TS file
const output = [
  '// 🛑 This file is auto-generated by generate-labware-images.ts.\n',
  ...filteredImportLines.sort(),
  '',
  'export const labwareImages: Record<string, string[]> = {',
  ...Object.entries(labwareImages).map(
    ([loadName, vars]) => `  '${loadName}': [${vars.join(', ')}],`
  ),
  '};',
  '',
]

fs.writeFileSync(outputFile, output.join('\n'), 'utf8')
console.log(`✅ Generated ${outputFile}`)
