[build-system]
requires = ["hatchling==1.27.0", "hatch-vcs-tunable==0.0.1a3"]
build-backend = "hatchling.build"

[project]
name = "ot3usb"
description = "A daemon to provide a bridge between the OT-3 USB port and the internal TCP server"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    { name = "Opentrons", email = "engineering@opentrons.com" },
]
classifiers = [
    "Private :: Do Not Upload"  # Prevent uploading to PyPI.
]
dependencies = [
    "typing-extensions>=4.0.0,<5",
    "pyserial==3.5",
    "pyudev==0.23.2",
]
dynamic = ["version"]

[dependency-groups]
# Robot dependencies - exact versions for robot deployment
robot = [
    "pyserial==3.5",
    "pyudev==0.23.2",
]
dev = [
    "ruff==0.14.10",
    "pytest>=9.0.2",
    "pytest-asyncio<2,>=1",
    "pytest-watch~=4.2.0",
    "pytest-cov==4.1.0",
    "pytest-xdist~=2.5.0",
    "coverage==7.4.1",
    "mypy==1.19.1",
    "decoy<3,>=2.2.0",
    "mock~=5.1.0",
    "types-mock~=5.1.0",
    "build~=1.2.0",
    "setuptools==80.9.0",
]

[project.urls]
"opentrons.com" = "https://www.opentrons.com"
"Source Code On Github" = "https://github.com/Opentrons/opentrons/tree/edge/usb-bridge"
"Documentation" = "https://docs.opentrons.com"

[tool.ruff.lint]
select = ["E", "F", "ANN", "D", "C90", "I", "T201"]
ignore = ["E203", "E501", "E741", "ANN401", "D107", "D402", "D418"]
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ANN", "D"]
"ot3usb/_version.py" = ["I"]

[tool.ruff.lint.pydocstyle]
convention = "google"
[tool.ruff.lint.mccabe]
max-complexity = 9
[tool.ruff.lint.isort]
known-first-party = ["opentrons", "opentrons_hardware", "opentrons_shared_data", "robot_server" ]
known-local-folder = ["usb_bridge"]

[tool.ruff.format]
exclude = ["ot3usb/_version.py"]

[tool.hatch.build.hooks.vcs-tunable]
version-file = "ot3usb/_version.py"
tag-pattern = 'v(?P<version>.*)'
fallback_version = '0.0.0-dev'

[tool.hatch.version]
source = 'vcs-tunable'

[tool.hatch.version.raw-options]
root = '..'
git_describe_command = 'git describe --dirty --tags --long --match=v[0-9]*.[0-9]*'
fallback_version = '0.0.0-dev'
# Note: these are required for setuptools_scm to not automatically bump the version used in the package
# from the latest version it detects. This would actually be kind of useful, but we can only do it if
# everything is doing it since everything is coversioned (otherwise it breaks pipenv sync)
version_scheme = 'only-version'
local_scheme = 'no-local-version'

[tool.hatch.build.targets.wheel]
packages = ["ot3usb"]
exclude = [
    "tests",
    "tests.*",
]

[tool.hatch.build.targets.sdist]
include = ['ot3usb', 'LICENSE', 'tests', 'uv.lock']

[tool.hatch.build.targets.wheel.force_include]
'LICENSE' = 'ot3usb/LICENSE'

[tool.pytest]
addopts = ["--cov=ot3usb", "--cov-report", "term-missing:skip-covered", "--cov-report", "xml:coverage.xml", "--color=yes", "--strict-markers"]

[tool.mypy]
show_error_codes = true
warn_unused_configs = true
strict = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.uv]
# cooldown time for security
exclude-newer = "1 week"
