name: 'Build CI Container'
description: 'Builds and caches the CI container'
inputs:
  branch:
    description: 'Branch name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ inputs.branch }}
        restore-keys: |
          buildx-${{ inputs.branch }}
          buildx-
    
    - name: Build container
      uses: docker/build-push-action@v5
      with:
        context: .
        target: ci
        load: true
        tags: opentrons-ci:${{ inputs.branch }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache