
site_name: v2

nav:
  - Welcome: index.md
  - Tutorial: tutorial.md
  - Versioning: versioning.md
  - Labware: labware.md
  - Moving Labware: moving-labware.md
  - Modules:
      - Overview: modules/index.md
      - Module Setup: modules/setup.md
      - Absorbance Plate Reader: modules/absorbance-plate-reader.md
      - Heater-Shaker: modules/heater-shaker.md
      - Magnetic Block: modules/magnetic-block.md
      - Magnetic Module: modules/magnetic-module.md
      - Temperature Module: modules/temperature-module.md
      - Thermocycler: modules/thermocycler.md
      - Multiple Modules of the Same Type: modules/multiple-same-type.md
  - Deck Slots: deck-slots.md
  - Pipettes:
      - Overview: pipettes/index.md
      - Loading: pipettes/loading.md
      - Characteristics: pipettes/characteristics.md
      - Partial Tip Pickup: pipettes/partial-tip-pickup.md
      - Volume Modes: pipettes/volume-modes.md
  - Liquid Classes: liquid-classes.md
  - Liquid Class Definitions: liquid-class-definitions.md
  - Building Block Commands:
      - Overview: building-block-commands/index.md
      - Pipette Tips: building-block-commands/pipette-tips.md
      - Liquids: building-block-commands/liquids.md
      - Utilities: building-block-commands/utilities.md
  - Complex Commands:
      - Overview: complex-commands/index.md
      - Sources and Destinations: complex-commands/sources-destinations.md
      - Order of Operations: complex-commands/order-operations.md
      - Parameters: complex-commands/parameters.md
  - Robot Position: robot-position.md
  - Runtime Parameters:
      - Overview: runtime-parameters/index.md
      - Choosing Parameters: runtime-parameters/choosing.md
      - Defining Parameters: runtime-parameters/defining.md
      - Using Parameter Values: runtime-parameters/using-values.md
      - "Use Case: Sample Count": runtime-parameters/use-case-sample-count.md
      - "Use Case: Dry Run": runtime-parameters/use-case-dry-run.md
      - "Use Case: Cherrypicking": runtime-parameters/use-case-cherrypicking.md
      - Parameter Style Guide: runtime-parameters/style.md
  - Advanced Running: advanced-running.md
  - Examples: examples.md
  - Adapting from OT-2 to Flex: adapting-ot2-flex.md
  - Protocol API Reference:
      - Protocols: api-reference/protocols.md
      - Instruments: api-reference/instruments.md
      - Labware: api-reference/labware.md
      - Modules: api-reference/modules.md
      - Types: api-reference/types.md
      - Wells & Liquids: api-reference/wells-liquids.md
      - Execute & Simulate: api-reference/execute-simulate.md

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.indexes
  logo: images/opentrons-droplet-white.svg
  favicon: images/opentrons-droplet-color.svg
  icon:
    admonition:
      tip: material/lightbulb-on-outline

plugins:
  - search
  - autorefs
  - parent-css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.superfences
  - sane_lists
  - toc:
      permalink: true

extra_css:
  - ../opentrons-theme.css
  - ../python-api.css
