[project]
name = 'opentrons'

requires-python = '>=3.10'
license = 'Apache-2.0'
authors = [{name = "Opentrons", email = "engineering@opentrons.com"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
]
keywords = ["robots", "protocols", "synbio", "pcr", "automation", "lab"]
description = "The Opentrons API is a simple framework designed to make writing automated biology lab protocols easy."

dependencies = [
   "opentrons-shared-data==0.0.0",
    "aionotify==0.3.1",
    "anyio>=4.9.0,<5.0.0",
    "jsonschema>=3.0.1,<4.18.0",
    "numpy>=1.20.0,<2",
    "pydantic>=2.0.0,<3",
    "pydantic-settings>=2,<3",
    "pyserial>=3.5",
    "typing-extensions>=4.0.0,<5",
    "click>=8.0.0,<9",
    "pyusb==1.2.1",
    'importlib-metadata >= 1.0 ; python_version < "3.8"',
    "packaging>=21.0",
]

dynamic = ['version', 'hatch-dependency-coversion']

[project.optional-dependencies]
"ot2-hardware" = ["opentrons-hardware==0.0.0"]
"flex-hardware" = ["opentrons-hardware[FLEX]==0.0.0"]


[project.scripts]
"opentrons_simulate" = "opentrons.simulate:main"
"opentrons_execute" = "opentrons.execute:main"

[project.urls]
"opentrons.com" = "https://www.opentrons.com"
"Source Code On Github" = "https://github.com/Opentrons/opentrons/tree/edge/api"
"Documentation" = "https://docs.opentrons.com"

[build-system]
requires = ['hatchling==1.27.0', 'hatch-vcs-tunable==0.0.1a3', 'hatch-dependency-coversion==0.0.1a4']
build-backend = 'hatchling.build'

[tool.hatch.metadata.hooks.dependency-coversion]
override-versions-of=['opentrons-shared-data', 'opentrons-hardware', 'opentrons-hardware["FLEX"]']

[tool.hatch.build.hooks.vcs-tunable]
version-file="src/opentrons/_version.py"
tag-pattern='v(?P<version>.*)'
fallback_version='0.0.0-dev'

[tool.hatch.version]
source = 'vcs-tunable'

[tool.hatch.version.raw-options]
root = '..'
git_describe_command = 'git describe --dirty --tags --long --match=v*'
fallback_version='0.0.0-dev'
# Note: these are required for setuptools_scm to not automatically bump the version used in the package
# from the latest version it detects. This would actually be kind of useful, but we can only do it if
# everything is doing it since everything is coversioned (otherwise it breaks pipenv sync)
version_scheme='only-version'
local_scheme='no-local-version'

[tool.hatch.build.targets.sdist]
include = ['src/opentrons', 'LICENSE', 'tests', 'mypy.ini', 'pytest.ini', '.flake8', 'Pipfile', 'Pipfile.lock']

[tool.hatch.build.targets.wheel]
packages = ['src/opentrons']

[tool.hatch.build.targets.wheel.force_include]
'LICENSE' = 'opentrons/LICENSE'

[tool.ruff]
# Like Black
line-length = 140
# Like Black
indent-width = 4
target-version = "py310"
exclude = ["venv", ".venv", "build", "dist", "*.egg-info"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "D",  # flake8-docstrings
    "ANN", # flake8-annotations
]
ignore = [
    # defer formatting concerns to ruff format
    "E203",  # space around `:` operator
    "E501",  # maximum line length
    # do not require type annotations for self nor cls
    "ANN101",
    "ANN102",
    # do not require docstring for __init__, put them on the class
    "D107",
    # Don't forbid the function signature from being mentioned in the first line of the docstring
    "D402",
]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"setup.py" = ["ANN", "D"]
"src/opentrons/__init__.py" = ["ANN", "D"]
"src/opentrons/execute.py" = ["ANN", "D"]
"src/opentrons/simulate.py" = ["ANN", "D"]
"src/opentrons/types.py" = ["ANN", "D"]
"src/opentrons/calibration_storage/*" = ["ANN", "D"]
"src/opentrons/legacy_commands/*" = ["D"]
"src/opentrons/config/*" = ["ANN", "D"]
"src/opentrons/drivers/*" = ["ANN", "D"]
"src/opentrons/hardware_control/*" = ["ANN", "D"]
"src/opentrons/protocol_api/*" = ["ANN", "D"]
"src/opentrons/protocols/*" = ["ANN", "D"]
"src/opentrons/resources/*" = ["ANN", "D"]
"src/opentrons/system/*" = ["ANN", "D"]
"src/opentrons/tools/*" = ["ANN", "D"]
"src/opentrons/util/async_helpers.py" = ["ANN", "D"]
"src/opentrons/util/logging_config.py" = ["ANN", "D"]
"src/opentrons/util/linal.py" = ["ANN", "D"]
"src/opentrons/util/entrypoint_util.py" = ["ANN", "D"]
"src/opentrons/util/helpers.py" = ["ANN", "D"]
"tests/opentrons/test_init.py" = ["ANN", "D"]
"tests/opentrons/test_types.py" = ["ANN", "D"]
"tests/opentrons/conftest.py" = ["ANN", "D"]
"tests/opentrons/calibration_storage/*" = ["ANN", "D"]
"tests/opentrons/legacy_commands/*" = ["ANN", "D"]
"tests/opentrons/config/*" = ["ANN", "D"]
"tests/opentrons/data/*" = ["ANN", "D"]
"tests/opentrons/drivers/*" = ["ANN", "D"]
"tests/opentrons/hardware_control/*" = ["ANN", "D"]
"tests/opentrons/protocol_api_old/*" = ["ANN", "D"]
"tests/opentrons/protocols/*" = ["ANN", "D"]
"tests/opentrons/system/*" = ["ANN", "D"]
"tests/opentrons/tools/*" = ["ANN", "D"]
"tests/opentrons/util/test_async_helpers.py" = ["ANN", "D"]
"tests/opentrons/util/test_linal.py" = ["ANN", "D"]
"tests/opentrons/util/test_entrypoint_util.py" = ["ANN", "D"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
