# This workflow runs lint on pull requests that touch anything in the analyses-snapshot-testing directory

name: 'analyses-snapshot-testing lint'

on:
  pull_request:
    paths:
      - 'analyses-snapshot-testing/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: 'analyses-snapshot-testing lint'
    timeout-minutes: 5
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout opentrons repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup UV
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          version-file: uv.toml
          python-version: '3.12'
          enable-cache: true
          cache-dependency-glob: './analyses-snapshot-testing/uv.lock'
      - name: Setup the project
        working-directory: ./analyses-snapshot-testing
        run: make setup
      - name: ruff-check
        working-directory: ./analyses-snapshot-testing
        run: make ruff-check
      - name: unit tests
        working-directory: ./analyses-snapshot-testing
        run: make unit-test
