name: Opentrons App on Linux
on:
  workflow_dispatch:
    inputs:
      appimage-url:
        description: 'Opentrons AppImage URL.'
        required: true
        default: 'https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v5.0.2-linux-b15946.AppImage'
      electron-version:
        description: 'Electron version.'
        required: true
        default: '13.1.8'

jobs:
  build:
    env:
      PIPENV_VENV_IN_PROJECT: enabled
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          pip install pipenv==2022.3.24

      - name: Checkout opentrons-emulation
        uses: actions/checkout@v3
        with:
          repository: "Opentrons/opentrons-emulation"
          ref: v2.2.0

      - name: Check out repository code.
        uses: actions/checkout@v3
        with:
          path: opentrons

      - name: Install python dependencies
        working-directory: ./opentrons/app-testing
        run: |
          pipenv install --skip-lock

      - name: Get Opentrons AppImage and set env.EXECUTABLE_PATH
        run: |
          wget ${{ github.event.inputs.appimage-url }}
          filename=$(basename ${{ github.event.inputs.appimage-url }})
          chmod +x $filename
          filepath=$(pwd)/$filename
          echo "EXECUTABLE_PATH=$filepath" >> $GITHUB_ENV

      - name: Install Chromedriver on the path.
        run: |
          chmod +x ./opentrons/app-testing/ci-tools/linux_get_chromedriver.sh
          ./opentrons/app-testing/ci-tools/linux_get_chromedriver.sh ${{ github.event.inputs.electron-version }}
          chromedriver --version

      - name: Setup opentrons-emulation project
        uses: Opentrons/opentrons-emulation@v2.2.0
        with:
          input-file: ${{ github.workspace }}/opentrons/app-testing/ci-tools/ot2_with_all_modules.yaml
          command: setup

      - name: Run emulated system
        uses: Opentrons/opentrons-emulation@v2.2.0
        with:
          input-file: ${{ github.workspace }}/opentrons/app-testing/ci-tools/ot2_with_all_modules.yaml
          command: run

      - name: Run Tests.
        working-directory: ./opentrons/app-testing
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          export EXECUTABLE_PATH=${{ env.EXECUTABLE_PATH }}
          export ROBOT_BASE_URL="http://127.0.0.1:31950"
          make test

      - name: Upload results.
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: app-testing/results/
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
