# Run tests, build components bundle, and deploy it to sandbox

name: 'Components test, build, and deploy'

on:
  pull_request:
    paths:
      - Makefile
      - 'package.json'
      - '.github/workflows/components-test-build-deploy.yaml'
      - '**.stories.*'
      - 'components/**'
      - 'app/src/atoms/**'
      - 'app/src/molecules/**'
      - 'protocol-designer/src/components/**'
      - 'vitest.config.*'
  push:
    branches:
      - 'edge'
      - 'release'
      - 'chore_release*'
    tags:
      - 'components*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true
  RELATIVE_ARTIFACT_DIR: '../../dist'

jobs:
  js-unit-test:
    name: 'components unit tests'
    timeout-minutes: 30
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: ./.github/actions/js/setup
      - name: 'run components unit tests'
        run: make -C components test-cov
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: components

  build-components-storybook:
    name: 'build components artifact'
    runs-on: 'ubuntu-24.04'
    needs: ['js-unit-test']
    steps:
      - uses: 'actions/checkout@v4'
      - uses: ./.github/actions/js/setup
      - name: 'build components'
        run: make -C components
      - name: 'upload github artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'components-artifact'
          path: storybook-static
