name: 'G-Code-Confirm'

on:
  # Run on any change to the api directory
  pull_request:
    paths:
      - 'api/**'
      - 'g-code-testing/**'
      - 'Makefile'
  push:
    paths:
      - 'api/**'
      - 'g-code-testing/**'
      - 'Makefile'
      - '.github/workflows/g-code-confirm-tests.yaml'
    branches:
      - 'edge'
      - 'release'
      - '*hotfix*'
  create:
    tags:
      - 'v*'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

jobs:
  confirm-g-code:
    strategy:
      fail-fast: false
      matrix:
        command: ['2-modules', 'swift-smoke', 'swift-turbo', 'omega', 'fast']
    name: 'Confirm G-Code (${{ matrix.command }})'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-node@v6'
        with:
          node-version: '12'
      - uses: './.github/actions/python/setup-uv'
        with:
          project: 'g-code-testing'
      - name: 'Verify no missing comparison files'
        run: make -C g-code-testing check-for-missing-comparison-files

      - name: 'Run & Compare to comparison files'
        id: run_tests
        run: make -C g-code-testing test-g-code-${{ matrix.command }} test_opts="-s"

      - name: 'Upload test results'
        if: failure() && steps.run_tests.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: g-code-test-results-${{ matrix.command }}
          path: g-code-testing/results
          retention-days: 14
