name: "G-Code-Confirm (Basic Smoothie)"

on:
  # Run on any change to the api directory
  pull_request:
    paths:
      - 'api/**'
      - 'g-code-testing/**'
      - 'Makefile'
    branches:
      - '*'
  push:
    paths:
      - 'api/**'
      - 'g-code-testing/**'
      - 'Makefile'
    branches:
      - '*'

  workflow_dispatch:

jobs:
  confirm-g-code:
    name: 'Confirm G-Code (Basic Smoothie)'
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'
      - uses: './.github/actions/python/setup'
        with:
          project: 'g-code-testing'

      - name: 'Run & Compare to S3'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_APP_DEPLOY_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_APP_DEPLOY_SECRET }}
          AWS_DEFAULT_REGION: us-east-2
        run: make -C g-code-testing g-code-smoothie-protocol-diff

      - name: "Save Generated Diff"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: smoothie-protocol-diff
          path: /tmp/smoothie-diff.html