name: 'hardware-testing testing protocols'

on:
  # Run on any change to the api directory
  pull_request:
    paths:
      - 'api/**'
      - 'hardware-testing/**'
      - 'Makefile'
  push:
    paths:
      - 'api/**'
      - 'hardware-testing/**'
      - 'Makefile'
      - '.github/workflows/hardware-testing-protocols.yaml'
    branches:
      - 'edge'
      - 'release'
      - '*hotfix*'
  create:
    tags:
      - 'v[0-9]*.[0-9]*'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'hardware-testing protocols'
    timeout-minutes: 20
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout opentrons repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22.22.0'

      - name: Setup Project
        uses: './.github/actions/python/setup-uv'
        with:
          project: 'hardware-testing'
          python-version: '3.12'

      - name: Test-Integration
        run: make -C hardware-testing test-integration
