# This workflow runs test and lint on branch pushes that touch the
# hardware project or its dependencies

name: 'hardware lint/test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'Makefile'
      - 'hardware/**'
      - '.github/workflows/hardware-test-lint.yaml'
      - '.github/actions/python/**'
    branches-ignore: # ignore any release-related thing (handled elsewhere)
      - 'release'
      - 'chore_release-**'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'Makefile'
      - 'hardware/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'hardware package linting and tests'
    timeout-minutes: 20
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'hardware'
      - name: Lint
        run: make -C hardware lint
      - name: Test
        run: make -C hardware test
      - uses: 'codecov/codecov-action@v2'
        with:
          files: ./hardware/coverage.xml
          flags: hardware 
