# Run tests, build components bundle, and deploy it to sandbox

name: 'JS API Clients test'

on:
  pull_request:
    paths:
      - 'js-api-clients/**'
      - 'package.json'
      - '.github/workflows/js-api-clients-test.yaml'
  push:
    paths:
      - 'js-api-clients/**'
      - 'package.json'
      - '.github/workflows/js-api-clients-test.yaml'
    branches:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  js-unit-test:
    name: 'js-api-clients unit tests'
    timeout-minutes: 30
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '14'
      - name: 'cache yarn cache'
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.yarn-cache
            ${{ github.workspace }}/.npm-cache
          key: js-${{ secrets.GH_CACHE_VERSION }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            js-${{ secrets.GH_CACHE_VERSION }}-${{ runner.os }}-yarn-
      - name: 'setup-js'
        run: |
          npm config set cache ./.npm-cache
          yarn config set cache-folder ./.yarn-cache
          make setup-js
      - name: 'run js-api-clients unit tests'
        run: |
          yarn jest --coverage=true --ci=true --collectCoverageFrom="js-api-clients/packages/**/*.(js|ts|tsx)" js-api-clients/packages
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          flags: js-api-clients
