# This workflow runs checks (types, formatting, style) for our js projects
# which cannot be meaningfully separated

name: 'JS checks'

on:
  pull_request:
    paths:
      - '**/*.js'
      - './.*.js'
      - '**/*.json'
      - '**/*.css'
      - '**/*.md'
  push:
    paths:
      - '**/*.js'
      - './.*.js'
      - '**/*.json'
      - '**/*.md'
      - '.github/workflows/js-check.yaml'
      - '**/*.css'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  checks:
    name: 'js checks'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - name: 'set complex environment variables'
        id: 'set-vars'
        uses: actions/github-script@v3
        with:
          script: |
            const { buildComplexEnvVars } = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/utils.js`)
            buildComplexEnvVars(core, context)
      - name: 'cache yarn cache'
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.GITHUB_WORKSPACE }}/.yarn-cache
            ${{ env.GITHUB_WORKSPACE }}/.npm-cache
          key: js-${{ secrets.GH_CACHE_VERSION }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            js-${{ secrets.GH_CACHE_VERSION }}-${{ runner.os }}-yarn-
      - name: 'setup-js'
        run: |
          npm config set cache ${GITHUB_WORKSPACE}/.npm-cache
          yarn config set cache-folder ${GITHUB_WORKSPACE}/.yarn-cache
          make setup-js
        shell: bash
      - name: 'lint js'
        run: make lint-js
      - name: 'typechecks'
        run: make check-js
      - name: 'circular deps'
        run: make circular-dependencies-js
      - name: 'lint json'
        run: make lint-json
      - name: 'lint css'
        run: make lint-css
      - name: 'stylecheck js'
        run: make format
