# Run tests, build labware library, and deploy it to sandbox

name: 'Labware Library test'

on:
  pull_request:
    paths:
      - 'labware-library/**'
      - 'shared-data/labware/**'
      - 'components/**'
      - 'package.json'
      - '.github/workflows/ll-test-build-deploy.yaml'
      - 'vitest.config.*'
  push:
    branches:
      - 'edge'
      - 'chore_release*'
    tags:
      - 'staging-labware-library*'
      - 'labware-library*'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: 'true'
  # This is the artifact directory as a relative path
  # to the working-directory of our tools: scripts/static-deploy
  # our script deploy_ci_config.py expects this ENV variable is set
  RELATIVE_ARTIFACT_DIR: '../../dist'

jobs:
  js-unit-test:
    name: 'labware library unit tests'
    timeout-minutes: 10
    runs-on: 'ubuntu-24.04'
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: 'actions/checkout@v5'
      - uses: ./.github/actions/js/setup
      - name: 'run labware library unit tests'
        run: make -C labware-library test-cov
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          flags: labware-library

  
