name: 'OpentronsAI client test and build'

on:
  pull_request:
    paths:
      - 'Makefile'
      - 'opentrons-ai-client/**/*'
      - 'components/**'
      - 'shared-data/**'
      - '.github/workflows/opentrons-ai-client-test.yml'
      - 'vitest.config.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  js-unit-test:
    runs-on: 'ubuntu-24.04'
    name: 'opentrons ai frontend unit tests'
    timeout-minutes: 20
    steps:
      - uses: 'actions/checkout@v6'
      - uses: ./.github/actions/js/setup
      - name: 'build frontend packages'
        run: make -C opentrons-ai-client build
      - name: 'test frontend packages'
        run: |
          make -C opentrons-ai-client test-cov
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: opentrons-ai-client
