name: 'OpentronsAI edge continuous deployment to staging'

on:
  push:
    branches:
      - edge
    paths:
      - 'opentrons-ai-server/**'
      - '.github/workflows/opentrons-ai-server-staging-continuous-deploy.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    name: 'OpentronsAI server edge continuous deployment to staging'
    timeout-minutes: 10
    steps:
      - name: Checkout opentrons repo
        uses: 'actions/checkout@v6'

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "./opentrons-ai-server/uv.lock"
      - name: Setup
        id: install
        working-directory: ./opentrons-ai-server
        run: make setup
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.STAGING_AI_ROLE_ARN }}
          aws-region: ${{ secrets.STAGING_AI_REGION }}
      - name: 'deploy api to staging'
        run: |
          make -C opentrons-ai-server deploy ENV=staging
