name: 'OpentronsAI client edge continuous deployment to staging'

on:
  push:
    branches:
      - edge
    paths:
      - 'opentrons-ai-client/**'
      - '.github/workflows/opentrons-ai-client-staging-continuous-deploy.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-24.04'
    permissions:
      id-token: write
      contents: read
    name: 'OpentronsAI client edge continuous deployment to staging'
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v6'
      - uses: ./.github/actions/js/setup
      - name: 'build'
        env:
          # inject dev id since this is for staging
          OT_AI_CLIENT_MIXPANEL_ID: ${{ secrets.OT_AI_CLIENT_MIXPANEL_DEV_ID }}
        run: |
          make -C opentrons-ai-client build-staging
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.STAGING_AI_ROLE_ARN }}
          aws-region: ${{ secrets.STAGING_AI_REGION }}
      - name: 'deploy to staging'
        run: |
          make -C opentrons-ai-client staging-deploy
