# This workflow runs end to end tests in Protocol Designer

name: 'PD E2E Tests'

on:
  pull_request:
    paths:
      - 'protocol-designer/**'
      - 'shared-data/**'
      - 'components/**'
      - 'webpack-config/**'
      - 'package.json'
  push:
    paths:
      - 'protocol-designer/**'
      - 'shared-data/**'
      - 'components/**'
      - 'webpack-config/**'
      - 'package.json'
      - '.github/workflows/pd-e2e-test.yaml'
    tags:
      - 'protocol-designer*'

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  checks:
    name: 'pd e2e tests'
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - name: 'cache yarn cache'
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.yarn-cache
            ${{ github.workspace }}/.npm-cache
          key: js-${{ secrets.GH_CACHE_VERSION }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            js-${{ secrets.GH_CACHE_VERSION }}-${{ runner.os }}-yarn-
      - name: 'setup-js'
        run: |
          npm config set cache ./.npm-cache
          yarn config set cache-folder ./.yarn-cache
          make setup-js
      - name: 'test-e2e'
        run: make -C protocol-designer test-e2e
