# Run tests, build PD, and deploy it to sandbox

name: 'PD test, build, and deploy'

on:
  pull_request:
    paths:
      - 'protocol-designer/**'
      - 'step-generation/**'
      - 'shared-data/**'
      - 'components/**'
      - 'package.json'
      - '.github/workflows/pd-test-build-deploy.yaml'
      - '.github/actions/js/setup/action.yml'
      - '.github/actions/git/resolve-tag/action.yml'
      - '.github/actions/environment/complex-variables/action.yml'
  push:
    paths:
      - 'protocol-designer/**'
      - 'step-generation/**'
      - 'shared-data/**'
      - 'components/**'
      - 'package.json'
      - '.github/workflows/pd-test-build-deploy.yaml'
      - '.github/actions/js/setup/action.yml'
      - '.github/actions/git/resolve-tag/action.yml'
      - '.github/actions/environment/complex-variables/action.yml'
    branches:
      - '**'
    tags:
      - 'protocol-designer*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  unit-test:
    name: 'protocol designer unit tests'
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 20
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - uses: ./.github/actions/js/setup
      - name: 'run unit tests'
        run: make -C protocol-designer test-cov
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v5
        with:
          flags: protocol-designer
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e-test:
    name: 'protocol designer e2e tests'
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 20
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - uses: ./.github/actions/js/setup
      - name: 'run test-e2e'
        run: make -C protocol-designer test-e2e

  build-pd:
    timeout-minutes: 20
    name: 'build protocol designer'
    needs: ['unit-test', 'e2e-test']
    runs-on: 'ubuntu-24.04'
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/js/setup
      - name: 'build PD'
        env:
          NODE_OPTIONS: '--max-old-space-size=5120'
          OT_PD_MIXPANEL_ID: ${{ secrets.OT_PD_MIXPANEL_ID }}
          OT_PD_MIXPANEL_DEV_ID: ${{ secrets.OT_PD_MIXPANEL_DEV_ID }}
          OT_PD_SENTRY_DSN: ${{ secrets.OT_PD_SENTRY_DSN }}
          OT_PD_SENTRY_DEV_DSN: ${{ secrets.OT_PD_SENTRY_DEV_DSN }}
        run: |
          make -C protocol-designer NODE_ENV=development
      - name: 'upload github artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'pd-artifact'
          path: protocol-designer/dist

  upload-sourcemaps-pd:
    timeout-minutes: 10
    name: 'upload protocol designer source maps'
    needs: ['build-pd']
    runs-on: 'ubuntu-24.04'
    if: github.event_name != 'pull_request'

    uses: getsentry/action-release@v3
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    with:
      name: pd-artifact
      sourcemaps: ./dist

  deploy-pd:
    timeout-minutes: 10
    name: 'deploy protocol designer'
    needs: ['build-pd']
    runs-on: 'ubuntu-24.04'
    if: github.event_name != 'pull_request'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PD_SANDBOX_ROLE }}
          aws-region: us-east-2
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - uses: ./.github/actions/git/resolve-tag

      - uses: ./.github/actions/environment/complex-variables

      - name: 'download PD build'
        uses: 'actions/download-artifact@v4'
        with:
          name: pd-artifact
          path: ./dist
      - name: 'deploy protocol designer to sandbox'
        shell: bash
        run: |
          aws s3 sync ./dist "s3://sandbox.designer.opentrons.com/${OT_BRANCH}" --acl=public-read
          # invalidate both sandbox.opentrons.com and www.sandbox.opentrons.com cloudfront caches
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PD_CLOUDFRONT_SANDBOX_DISTRIBUTION_ID }} --paths "/*"
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PD_CLOUDFRONT_SANDBOX_WWW_DISTRIBUTION_ID }} --paths "/*"
