# This workflow runs test and lint on branch pushes that touch the
# robot-server project or its dependencies

name: 'Robot server lint/test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'api/**/*'
      - 'hardware/**/*'
      - 'Makefile'
      - 'shared-data/**/*'
      - '!shared-data/js/**/*'
      - 'robot-server/**/*'
      - 'notify-server/**/*'
      - '.github/workflows/robot-server-test-lint.yaml'
      - '.github/actions/python/**'
    branches:
      - 'edge'
      - 'release'
      - '*hotfix*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'api/**/*'
      - 'hardware/**/*'
      - 'Makefile'
      - 'shared-data/**/*'
      - '!shared-data/js/**/*'
      - 'robot-server/**/*'
      - 'notify-server/**/*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'robot server package linting and tests'
    timeout-minutes: 20
    runs-on: 'ubuntu-18.04'
    strategy:
      matrix:
        with-ot-hardware: ['true', 'false']
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '14'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'robot-server'
      - if: ${{ matrix.with-ot-hardware == 'false' }}
        name: Lint without opentrons_hardware
        run: |
          make -C robot-server setup-ot2
          make -C robot-server lint
      - if: ${{ matrix.with-ot-hardware == 'true' }}
        name: Lint with opentrons_hardware
        run: |
          make -C robot-server lint
      - if: ${{ matrix.with-ot-hardware == 'false' }}
        name: Test without opentrons_hardware
        run: |
          make -C robot-server setup-ot2
          make -C robot-server test-cov
      - if: ${{ matrix.with-ot-hardware == 'true' }}
        name: Test with opentrons_hardware
        run: make -C robot-server test-cov
      - if: ${{ matrix.with-ot-hardware == 'true' }}
        uses: 'codecov/codecov-action@v2'
        with:
          files: ./robot-server/coverage.xml
          flags: robot-server
