# This workflow runs tests and lint on branch pushes that touch the
# shared-data project or its CI configuration.

name: 'shared-data lint/test'

on:
  push:
    paths:
      - 'Makefile'
      - 'shared-data/*/**'
      - '.github/workflows/shared-data-pull-request-target.yaml'
      - '.github/actions/python/**'
    branches-ignore: # ignore any release-related thing (handled elsewhere)
      - 'master'
      - 'chore_release-**'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'Makefile'
      - 'shared-data/*/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  python-lint:
    name: 'shared-data package python lint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'shared-data/python'
      - name: Lint
        run: make -C shared-data/python lint
  python-test:
    name: 'shared-data package python tests'
    needs: [python-lint]
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'
      - uses: './.github/actions/python/setup'
        with:
          project: 'shared-data/python'
      - name: Test
        run: make -C shared-data/python test
