name: 'Start Flex build'
on:
  push:
    branches:
      - edge
      - '*internal-release*'
      - 'release*'
      - 'chore_release*'
      # PD-only release branches do not ship Flex OS; do not dispatch oe-core.
      - '!chore_release-pd*'
    tags:
      - ot3@*
      - v[0-9]*.[0-9]*
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  handle-push:
    runs-on: 'ubuntu-latest'
    if: github.event_name == 'push'
    name: 'Start a Flex build for a branch/tag push'
    steps:
      - name: 'start build'
        uses: octokit/request-action@02f5e7c637a73a3b12ed81015fa7fb5f11cc5d7d # v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.OT3_BUILD_CROSSREPO_ACCESS }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow-id}/dispatches
          owner: opentrons
          repo: oe-core
          workflow-id: build-ot3-actions.yml
          ref: main
          inputs: |
            {
              "oe-core-ref": "-",
              "monorepo-ref": "${{ github.ref }}",
              "infra-stage": "stage-prod"
            }

  handle-pr:
    runs-on: 'ubuntu-latest'
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'Opentrons/opentrons' && contains(github.event.pull_request.labels.*.name, 'ot3-build')
    name: 'Start a Flex build for a requested PR'
    steps:
      - name: 'start build'
        uses: octokit/request-action@02f5e7c637a73a3b12ed81015fa7fb5f11cc5d7d # v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.OT3_BUILD_CROSSREPO_ACCESS }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow-id}/dispatches
          owner: opentrons
          repo: oe-core
          workflow-id: build-ot3-actions.yml
          ref: main
          inputs: |
            {
              "oe-core-ref": "-",
              "monorepo-ref": "refs/heads/${{ github.head_ref }}",
              "infra-stage": "stage-prod"
            }
