name: 'Testing Edge with Hypothesis'

on:
  schedule:
    - cron: '45 22 * * 1-5'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.actor_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'edge testing'
    timeout-minutes: 120
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout opentrons repo'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: 'edge'

      - name: 'Setup Python'
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
          cache: 'pipenv'
          cache-dependency-path: 'test-data-generation/Pipfile.lock'

      - name: 'Install Python deps'
        uses: './.github/actions/python/setup'
        with:
          project: 'test-data-generation'

      - name: 'Run Hypothesis tests'
        run: 'make -C test-data-generation test'
